"""
erc4626-share-inflation-at-zero-total — generated from skeleton `name_match_missing_call`
Ported from: Morpho Cantina H-C4 (borrow-share inflation when totalBorrowAssets==0) + generic ERC-4626 first-depositor pattern
Severity: HIGH
Pattern: function whose name matches the target regex reads a state var
matching the read regex, but does NOT contain an internal/high-level call
matching the required-call regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/erc4626-share-inflation-at-zero-total.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper

from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class Erc4626ShareInflationAtZeroTotal(AbstractDetector):
    ARGUMENT = "erc4626-share-inflation-at-zero-total"
    HELP = "Share-denominated function writes totalShares when totalAssets is zero — classic inflation/first-depositor attack surface"
    IMPACT = DetectorClassification.HIGH
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "ERC-4626/share-based accounting inflation when total assets is zero"
    WIKI_DESCRIPTION = "When totalAssets (or totalBorrowAssets, totalSupplyAssets, etc.) is zero, a deposit/mint/borrow that writes to totalShares without a virtual-offset guard allows the first depositor to manipulate the share price by donating assets before or after. This is the canonical ERC-4626 first-depositor inflation attack."
    WIKI_EXPLOIT_SCENARIO = "Attacker front-runs the first legitimate depositor: attacker mints 1 wei of shares, donates a large amount of underlying directly to the vault, then the next depositor's deposit is worth ~0 shares due to the inflated share price. Attacker redeems and takes the depositor's funds."
    WIKI_RECOMMENDATION = "Use virtual shares/assets offset (e.g., OpenZeppelin's _decimalsOffset or Morpho's VIRTUAL_SHARES/VIRTUAL_ASSETS pattern) to prevent share-price manipulation when totalAssets is near zero."

    _FN_NAME_REGEX = re.compile(r".*(deposit|mint|borrow|supply).*", re.IGNORECASE)
    _READ_VAR_REGEX = re.compile(r".*(totalShares|totalSupplyShares|totalBorrowShares|totalSupply).*", re.IGNORECASE)
    _REQUIRED_CALL_REGEX = re.compile(r".*(virtual|VIRTUAL|_decimalsOffset|initialDeposit).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                # Skip pure/view leaf helpers — they trivially "don't call the
                # required helper" because they don't call anything. See
                # SKILL_ISSUE #55.
                if is_leaf_helper(f):
                    continue

                # Check that the function reads at least one state var matching the regex
                reads_target = False
                for sv in f.state_variables_read:
                    if self._READ_VAR_REGEX.search(sv.name):
                        reads_target = True
                        break
                if not reads_target:
                    continue

                # Check for the required internal/high-level call (presence = safe)
                has_required_call = False
                for ic in f.internal_calls:
                    callee = ic.function if hasattr(ic, "function") else ic
                    callee_name = getattr(callee, "name", "") or ""
                    if self._REQUIRED_CALL_REGEX.search(callee_name):
                        has_required_call = True
                        break
                if not has_required_call:
                    for hc_tuple in f.high_level_calls:
                        hc = hc_tuple[1] if isinstance(hc_tuple, tuple) else hc_tuple
                        callee_name = (
                            getattr(hc.function, "name", "") if hasattr(hc, "function") else ""
                        ) or ""
                        if self._REQUIRED_CALL_REGEX.search(callee_name):
                            has_required_call = True
                            break

                if has_required_call:
                    continue

                info = [
                    f,
                    f" — erc4626-share-inflation-at-zero-total: reads `{{{{}}}}`-matching state but does not call a `.*(virtual|VIRTUAL|_decimalsOffset|initialDeposit).*` guard. ",
                    f"Ported from Morpho Cantina H-C4 (borrow-share inflation when totalBorrowAssets==0) + generic ERC-4626 first-depositor pattern. See reference/bug_patterns_observed.md.",
                ]
                res = self.generate_result(info)
                results.append(res)
        return results
