"""
a-malicious-user-can-add-themselves-as-a-referrer-in-the-referra — generated from skeleton `name_match_missing_call`
Ported from: Solodit #45620 (Zokyo/Filament)
Severity: MEDIUM
Pattern: function whose name matches the target regex reads a state var
matching the read regex, but does NOT contain an internal/high-level call
matching the required-call regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/a-malicious-user-can-add-themselves-as-a-referrer-in-the-referra.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper

from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class AMaliciousUserCanAddThemselvesAsAReferrerInTheReferra(AbstractDetector):
    ARGUMENT = "a-malicious-user-can-add-themselves-as-a-referrer-in-the-referra"
    HELP = "A malicious user can add themselves as a referrer in the Referral contract to aid phishing attacks"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "A malicious user can add themselves as a referrer in the Referral contract to aid phishing attacks"
    WIKI_DESCRIPTION = "**Severity**: Medium\n\n**Status**: Resolved\n\n**Description**\n\nThe Referral contract is responsible for the referral program which allows users to refer others to earn rewards for introducing users to the protocol. The issue lies within the registerReferral function where a malicious user can add them"
    WIKI_EXPLOIT_SCENARIO = "Per Solodit #45620: **Severity**: Medium\n\n**Status**: Resolved\n\n**Description**\n\nThe Referral contract is responsible for the referral program which allows users to refer others to earn rewards for introducing users to t"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(registerReferral|getReferrer).*", re.IGNORECASE)
    _READ_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _REQUIRED_CALL_REGEX = re.compile(r".*(accrue|update|sync|validate|check|refresh).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                # Skip pure/view leaf helpers — they trivially "don't call the
                # required helper" because they don't call anything. See
                # SKILL_ISSUE #55.
                if is_leaf_helper(f):
                    continue

                # Check that the function reads at least one state var matching the regex
                reads_target = False
                for sv in f.state_variables_read:
                    if self._READ_VAR_REGEX.search(sv.name):
                        reads_target = True
                        break
                if not reads_target:
                    continue

                # Check for the required internal/high-level call (presence = safe)
                has_required_call = False
                for ic in f.internal_calls:
                    callee = ic.function if hasattr(ic, "function") else ic
                    callee_name = getattr(callee, "name", "") or ""
                    if self._REQUIRED_CALL_REGEX.search(callee_name):
                        has_required_call = True
                        break
                if not has_required_call:
                    for hc_tuple in f.high_level_calls:
                        hc = hc_tuple[1] if isinstance(hc_tuple, tuple) else hc_tuple
                        callee_name = (
                            getattr(hc.function, "name", "") if hasattr(hc, "function") else ""
                        ) or ""
                        if self._REQUIRED_CALL_REGEX.search(callee_name):
                            has_required_call = True
                            break

                if has_required_call:
                    continue

                info = [
                    f,
                    f" — a-malicious-user-can-add-themselves-as-a-referrer-in-the-referra: reads `{{{{}}}}`-matching state but does not call a `.*(accrue|update|sync|validate|check|refresh).*` guard. ",
                    f"Ported from Solodit #45620 (Zokyo/Filament). See reference/bug_patterns_observed.md.",
                ]
                res = self.generate_result(info)
                results.append(res)
        return results
