"""
approve-function-return-value-not-validated — generated from skeleton `name_match_missing_call`
Ported from: Hexens Glider AST: missing-approve-return-validations
Severity: MEDIUM
Pattern: function whose name matches the target regex reads a state var
matching the read regex, but does NOT contain an internal/high-level call
matching the required-call regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/approve-function-return-value-not-validated.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class ApproveFunctionReturnValueNotValidated(AbstractDetector):
    ARGUMENT = "approve-function-return-value-not-validated"
    HELP = "Approve function return value not validated"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Approve function return value not validated"
    WIKI_DESCRIPTION = "When approving tokens for transfer to another address, a contract should validate the return value of the approve function to ensure that the transfer was successful. If the return value is not validated, the contract will continue operations even if the approval failed. This can lead to unexpected"
    WIKI_EXPLOIT_SCENARIO = "Tags [ERC-20, ERC-721, approval, call patterns]: When approving tokens for transfer to another address, a contract should validate the return value of the approve function to ensure that the transfer was successful. If the return value is not valida"
    WIKI_RECOMMENDATION = "Apply the access check implied by the Glider query filter."

    _FN_NAME_REGEX = re.compile(r".*", re.IGNORECASE)
    _READ_VAR_REGEX = re.compile(r".*approve.*", re.IGNORECASE)
    _REQUIRED_CALL_REGEX = re.compile(r".*(validate|check|verify|require).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                # Check that the function reads at least one state var matching the regex
                reads_target = False
                for sv in f.state_variables_read:
                    if self._READ_VAR_REGEX.search(sv.name):
                        reads_target = True
                        break
                if not reads_target:
                    continue

                # Check for the required internal/high-level call (presence = safe)
                has_required_call = False
                for ic in f.internal_calls:
                    callee = ic.function if hasattr(ic, "function") else ic
                    callee_name = getattr(callee, "name", "") or ""
                    if self._REQUIRED_CALL_REGEX.search(callee_name):
                        has_required_call = True
                        break
                if not has_required_call:
                    for hc_tuple in f.high_level_calls:
                        hc = hc_tuple[1] if isinstance(hc_tuple, tuple) else hc_tuple
                        callee_name = (
                            getattr(hc.function, "name", "") if hasattr(hc, "function") else ""
                        ) or ""
                        if self._REQUIRED_CALL_REGEX.search(callee_name):
                            has_required_call = True
                            break

                if has_required_call:
                    continue

                info = [
                    f,
                    f" — approve-function-return-value-not-validated: reads `{{{{}}}}`-matching state but does not call a `.*(validate|check|verify|require).*` guard. ",
                    f"Ported from Hexens Glider AST: missing-approve-return-validations. See reference/bug_patterns_observed.md.",
                ]
                res = self.generate_result(info)
                results.append(res)
        return results
