#!/usr/bin/env python3
"""capv3-iter8-T3 + FIX-8C — tests for `tools/symbolic-ce-to-forge.py`.

Nine hermetic tests locking the CE-replay *scaffold* (not replay):

Original iter-v3-8 T3 suite (3 tests, preserved):

  1. `test_ce_with_counterexample_produces_forge_test_matching_golden`
     Runs the tool on a synthetic halmos CE fixture (1 CE, 2 symbolic
     values, 1-step call sequence) and asserts the emitted forge-test
     file matches the committed golden byte-for-byte. Locks the
     rendering template (header, function body, value-decode rules,
     call-sequence formatting) against drift. Also asserts the
     ADVISORY header comment is present. Golden was regenerated by
     FIX-8C to pick up the reworded docstring ("Scaffold renders"
     instead of "Replays") — see docs/FIX8C_CE_REPLAY_SAFETY.md §Bug-2.

  2. `test_ce_no_counterexample_emits_cannot_run_and_no_file`
     Runs the tool on an empty-CE halmos manifest (`counterexamples:
     []`). Asserts: stdout empty, stderr is a single JSON object with
     `status: cannot-run` and `reason: no-counterexample`, exit code
     0 (honest-zero), and NO file was written to the output path.
     This is the gate-safe behavior for the common case today
     (0 CEs across 5 wired harnesses).

  3. `test_malformed_input_exits_nonzero`
     Runs the tool on a garbage-input file (not JSON). Asserts a
     non-zero exit code and an informative stderr error message.
     This locks the tool from silent failures on corrupt input.

FIX-8C regression suite (7 new tests, added):

  4. `test_output_path_in_submissions_packaged_rejected` (Bug 1)
     Writing to `.../submissions/packaged/...` must be rejected with
     non-zero exit, structured cannot-run JSON with reason
     `output-path-in-submissions`, and NO output file written.

  5. `test_output_path_in_submissions_ready_rejected` (Bug 1)
     Same as #4, but for the `submissions/ready/` subtree.

  6. `test_output_path_in_submissions_staging_rejected` (Bug 1)
     Same as #4, but for the `submissions/staging/` subtree.

  7. `test_output_path_traversal_into_packaged_rejected` (Bug 1)
     Traversal such as `submissions/tmp/../packaged/...` must also be
     rejected before any output file is created.

  8. `test_malformed_counterexample_schema_exits_cleanly` (Bug 3)
     A CE document with `counterexamples: ["bad"]` (non-dict entries)
     MUST exit non-zero with a structured `cannot-run` reason of
     `malformed-counterexample-schema` — NOT crash with an
     `AttributeError` traceback.

  9. `test_counterexample_without_values_does_not_crash` (Bug 3)
     A CE entry with no `values` key (and/or `call_sequence` key) but
     otherwise well-formed MUST render successfully and the emitted
     file must explicitly note the absence (no decls / no sequence).

  10. `test_unknown_value_emits_todo_not_invalid_assignment` (Bug 4)
     A CE with an unparseable value like `"foo"` MUST emit a TODO
     comment + a commented-out declaration, NOT a compile-broken
     assignment like `uint256 x = "foo";`.

See docs/SYMBOLIC_PROMOTION_GATE.md §S2 — this tool is scaffold, not
promotion. The tests verify the scaffold behaves, not that S2 is met.
"""
from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TOOL = ROOT / "tools" / "symbolic-ce-to-forge.py"
FIXTURES = ROOT / "tools" / "tests" / "fixtures" / "symbolic_ce_replay"
CE_WITH = FIXTURES / "ce_with_counterexample.json"
CE_EMPTY = FIXTURES / "ce_no_counterexample.json"
GOLDEN = FIXTURES / "expected_reproduce_7591121a.t.sol"


def _run(*args):
    return subprocess.run(
        [sys.executable, str(TOOL), *args],
        capture_output=True,
        text=True,
    )


class TestSymbolicCeToForge(unittest.TestCase):
    def test_ce_with_counterexample_produces_forge_test_matching_golden(self):
        """CE fixture → byte-for-byte match against committed golden."""
        self.assertTrue(CE_WITH.exists(), f"missing fixture: {CE_WITH}")
        self.assertTrue(GOLDEN.exists(), f"missing golden: {GOLDEN}")
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "reproduce.t.sol"
            res = _run(
                "--input", str(CE_WITH),
                "--output", str(out),
                "--contract-under-test", "Vault",
            )
            self.assertEqual(res.returncode, 0, res.stderr)
            self.assertTrue(out.exists(), "tool did not write an output file")
            emitted = out.read_text()
            expected = GOLDEN.read_text()
            self.assertEqual(
                emitted,
                expected,
                "emitted forge test does not match golden byte-for-byte",
            )
            # Belt-and-braces: the ADVISORY header MUST be present.
            self.assertIn(
                "ADVISORY — auto-generated from halmos CE",
                emitted,
                "ADVISORY header missing from emitted forge test",
            )

    def test_ce_no_counterexample_emits_cannot_run_and_no_file(self):
        """Empty-CE fixture → honest-zero, no file emitted."""
        self.assertTrue(CE_EMPTY.exists(), f"missing fixture: {CE_EMPTY}")
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "should_not_exist.t.sol"
            res = _run(
                "--input", str(CE_EMPTY),
                "--output", str(out),
                "--contract-under-test", "Vault",
            )
            self.assertEqual(
                res.returncode,
                0,
                f"expected exit 0 on empty-CE (honest-zero), got {res.returncode}; stderr={res.stderr}",
            )
            self.assertFalse(
                out.exists(),
                "tool wrote an output file on empty-CE input; must be honest-zero",
            )
            # stderr is a JSON object with cannot-run + no-counterexample.
            err = res.stderr.strip()
            self.assertTrue(err, "expected stderr to carry a cannot-run JSON")
            payload = json.loads(err)
            self.assertEqual(payload.get("status"), "cannot-run")
            self.assertEqual(payload.get("reason"), "no-counterexample")

    def test_malformed_input_exits_nonzero(self):
        """Garbage input → non-zero exit + informative stderr."""
        with tempfile.TemporaryDirectory() as td:
            bad = Path(td) / "garbage.json"
            bad.write_text("this is not { json at all")
            out = Path(td) / "should_not_exist.t.sol"
            res = _run(
                "--input", str(bad),
                "--output", str(out),
                "--contract-under-test", "Vault",
            )
            self.assertNotEqual(
                res.returncode,
                0,
                "expected non-zero exit on malformed JSON input",
            )
            self.assertFalse(
                out.exists(),
                "tool wrote an output file on malformed input; must not",
            )
            self.assertIn(
                "error",
                res.stderr.lower(),
                f"expected an informative error on stderr; got: {res.stderr!r}",
            )

    # ----- FIX-8C regression tests --------------------------------------

    def _assert_rejected_submission_path(self, subtree: str) -> None:
        """Shared assertion: a `submissions/<subtree>/` --output is rejected.

        Verifies all of:
          * exit code non-zero (Codex repro for Bug 1 must return non-zero),
          * no file created at the target path,
          * stderr contains a cannot-run JSON with reason
            `output-path-in-submissions`.
        """
        self.assertTrue(CE_WITH.exists(), f"missing fixture: {CE_WITH}")
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "submissions" / subtree / "demo" / "reproduce.t.sol"
            # NOTE: we intentionally do NOT pre-create parents — the
            # tool MUST refuse before it ever tries to mkdir anything.
            res = _run(
                "--input", str(CE_WITH),
                "--output", str(out),
                "--contract-under-test", "Vault",
            )
            self.assertNotEqual(
                res.returncode,
                0,
                f"expected non-zero exit when writing into submissions/{subtree}/; "
                f"got {res.returncode}; stderr={res.stderr}",
            )
            self.assertFalse(
                out.exists(),
                f"tool wrote into reserved submissions/{subtree}/ subtree",
            )
            # stderr ends with a JSON line — find it.
            err_lines = [ln for ln in res.stderr.splitlines() if ln.strip()]
            self.assertTrue(err_lines, "expected a stderr line with cannot-run JSON")
            # The cannot-run JSON is the last non-empty stderr line (an
            # optional human-readable `error: …` precedes it).
            payload = json.loads(err_lines[-1])
            self.assertEqual(payload.get("status"), "cannot-run")
            self.assertEqual(
                payload.get("reason"),
                "output-path-in-submissions",
                f"unexpected reason; stderr={res.stderr}",
            )

    def test_output_path_in_submissions_packaged_rejected(self):
        """Bug-1 regression: --output under submissions/packaged/ rejected."""
        self._assert_rejected_submission_path("packaged")

    def test_output_path_in_submissions_ready_rejected(self):
        """Bug-1 regression: --output under submissions/ready/ rejected."""
        self._assert_rejected_submission_path("ready")

    def test_output_path_in_submissions_staging_rejected(self):
        """Bug-1 regression: --output under submissions/staging/ rejected."""
        self._assert_rejected_submission_path("staging")

    def test_output_path_traversal_into_packaged_rejected(self):
        """Bug-1 hardening: traversal into submissions/packaged/ rejected."""
        self.assertTrue(CE_WITH.exists(), f"missing fixture: {CE_WITH}")
        with tempfile.TemporaryDirectory() as td:
            out = (
                Path(td)
                / "submissions"
                / "tmp"
                / ".."
                / "packaged"
                / "demo"
                / "reproduce.t.sol"
            )
            res = _run(
                "--input", str(CE_WITH),
                "--output", str(out),
                "--contract-under-test", "Vault",
            )
            self.assertNotEqual(res.returncode, 0, res.stderr)
            self.assertFalse(out.resolve().exists())
            err_lines = [ln for ln in res.stderr.splitlines() if ln.strip()]
            self.assertTrue(err_lines, "expected cannot-run JSON on stderr")
            payload = json.loads(err_lines[-1])
            self.assertEqual(payload.get("status"), "cannot-run")
            self.assertEqual(payload.get("reason"), "output-path-in-submissions")

    def test_malformed_counterexample_schema_exits_cleanly(self):
        """Bug-3 regression: CE array of strings → controlled cannot-run.

        The raw Codex repro was:
            {"counterexamples":["bad"]}
        which used to blow up with `AttributeError: 'str' object has
        no attribute 'get'` inside `render_forge_test`. After FIX-8C it
        must emit a structured `cannot-run` JSON with reason
        `malformed-counterexample-schema` and exit non-zero — no
        traceback.
        """
        with tempfile.TemporaryDirectory() as td:
            bad = Path(td) / "malformed.json"
            bad.write_text('{"counterexamples":["bad"]}')
            out = Path(td) / "should_not_exist.t.sol"
            res = _run(
                "--input", str(bad),
                "--output", str(out),
                "--contract-under-test", "Vault",
            )
            self.assertNotEqual(
                res.returncode,
                0,
                f"expected non-zero exit on malformed CE schema; stderr={res.stderr}",
            )
            self.assertFalse(
                out.exists(),
                "tool wrote an output file on malformed-schema input",
            )
            self.assertNotIn(
                "Traceback",
                res.stderr,
                f"tool must NOT crash with traceback on malformed CE; got: {res.stderr}",
            )
            err_lines = [ln for ln in res.stderr.splitlines() if ln.strip()]
            self.assertTrue(err_lines, "expected a stderr line with cannot-run JSON")
            payload = json.loads(err_lines[-1])
            self.assertEqual(payload.get("status"), "cannot-run")
            self.assertEqual(
                payload.get("reason"),
                "malformed-counterexample-schema",
                f"unexpected reason; stderr={res.stderr}",
            )

    def test_counterexample_without_values_does_not_crash(self):
        """Bug-3 regression: CE without `values`/`call_sequence` renders OK.

        A halmos CE may legitimately omit `values` (no symbolic
        bindings) and/or `call_sequence` (synthesized violation with
        no explicit call chain). The renderer must treat both as empty
        and emit the `// no symbolic values in this CE` /
        `// no call_sequence in this CE` breadcrumbs rather than
        raising or emitting invalid Solidity.
        """
        ce_doc = {
            "schema_version": 1,
            "_generated_at": "2026-04-24T00:00:00+00:00",
            "counterexamples": [{}],  # no values, no call_sequence
        }
        with tempfile.TemporaryDirectory() as td:
            inp = Path(td) / "ce_no_values.json"
            inp.write_text(json.dumps(ce_doc))
            out = Path(td) / "reproduce.t.sol"
            res = _run(
                "--input", str(inp),
                "--output", str(out),
                "--contract-under-test", "Vault",
            )
            self.assertEqual(
                res.returncode,
                0,
                f"expected exit 0 on empty-shaped CE; got {res.returncode}; "
                f"stderr={res.stderr}",
            )
            self.assertTrue(
                out.exists(),
                "tool did not write output for a well-formed empty-shape CE",
            )
            emitted = out.read_text()
            self.assertIn("no symbolic values in this CE", emitted)
            self.assertIn("no call_sequence in this CE", emitted)
            # And the file must still be advisory-tagged.
            self.assertIn(
                "ADVISORY — auto-generated from halmos CE",
                emitted,
                "ADVISORY header missing from emitted forge test",
            )

    def test_unknown_value_emits_todo_not_invalid_assignment(self):
        """Bug-4 regression: unparseable value → TODO, not `= "foo"`.

        Pre-FIX-8C the tool emitted:
            uint256 weird = "foo" /* UNRECOGNIZED — review */;
        which is invalid Solidity (can't assign a string literal to
        `uint256`). Post-FIX-8C the tool must emit a TODO comment +
        commented-out declaration instead.
        """
        ce_doc = {
            "schema_version": 1,
            "_generated_at": "2026-04-24T00:00:00+00:00",
            "counterexamples": [
                {
                    "values": {
                        "weird": {"type": "uint256", "value": "foo"},
                    },
                    "call_sequence": [],
                }
            ],
        }
        with tempfile.TemporaryDirectory() as td:
            inp = Path(td) / "ce_unknown.json"
            inp.write_text(json.dumps(ce_doc))
            out = Path(td) / "reproduce.t.sol"
            res = _run(
                "--input", str(inp),
                "--output", str(out),
                "--contract-under-test", "Vault",
            )
            self.assertEqual(
                res.returncode,
                0,
                f"expected exit 0 on unparseable value; stderr={res.stderr}",
            )
            self.assertTrue(out.exists(), "tool did not write output")
            emitted = out.read_text()
            # Must NOT contain the invalid-Solidity shape.
            self.assertNotIn(
                '= "foo"',
                emitted,
                "emitted an invalid `= \"foo\"` assignment — Bug 4 regressed",
            )
            self.assertNotIn(
                'UNRECOGNIZED — review',
                emitted,
                "pre-fix UNRECOGNIZED sentinel leaked into output",
            )
            # Must contain the TODO + commented declaration.
            self.assertIn(
                "// TODO: decode value for 'weird'",
                emitted,
                "expected a TODO comment for the unparseable value",
            )
            self.assertIn(
                "// uint256 weird;",
                emitted,
                "expected a commented-out placeholder declaration",
            )


if __name__ == "__main__":
    unittest.main()
