#!/usr/bin/env python3
"""Regression tests for the per-UNIT non-economic-surface disposition mechanism.

Covers:
  * tools/lib/non_economic_disposition.py - the validating loader + the
    never-false-pass guards (bounded class, min-rationale, on-disk CUT, REJECT
    any transfer-mover) + the file/all-files matchers.
  * the three deep-audit gate integrations that CREDIT a dispositioned unit
    instead of forcing a vacuous assert(true) scaffold:
      - invariant-fuzz-completeness.py   (harness-dir credit)
      - cross-function-invariant-coverage.py (requirement credit)
      - audit-honesty-check.py           (value-moving floor drop + stub drop)

Design assertion under test (the WHOLE point): a disposition can credit a
LEGITIMATELY non-economic unit (pure config-write, no transfer) WITHOUT a vacuous
harness, but can NEVER silently credit a genuine custody mover (transfer_hit) nor
a phantom/rubber-stamp disposition. ZERO workspace hardcoding.
"""
import importlib.util
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent.parent
_LIB = _TOOLS / "lib" / "non_economic_disposition.py"

# Hermetic HMAC secret so issue/verify share the same key regardless of the
# host's ~/.auditooor/mcp_secret. Must be set BEFORE the token module reads it.
os.environ.setdefault("AUDITOOOR_MCP_SECRET", "test-secret-for-non-economic-disposition")


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


ned = _load("non_economic_disposition", _LIB)
_tok = _load("auditooor_mcp_token", _TOOLS / "auditooor_mcp_token.py")


def _operator_approval_token(ws_dir):
    """Mint a genuine operator-issued, HMAC-signed token carrying the dedicated
    disposition-approve scope for ``ws_dir`` (the same primitive the loader
    verifies)."""
    token, _payload = _tok.issue_token(
        str(ws_dir), owner="operator",
        scope=[ned.APPROVAL_SCOPE], log=False,
    )
    return token


def _agent_write_token(ws_dir):
    """Mint a DEFAULT agent session token (scope 'write', no disposition-approve)
    - the exact token an agent already holds; it must NOT credit a disposition."""
    token, _payload = _tok.issue_token(
        str(ws_dir), owner="claude",
        scope=["read", "write", "remember"], log=False,
    )
    return token

_SCAFFOLD = """// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.0;
// Auto-generated by tools/per-function-invariant-gen.py.
// Function under test: {cut_name} at {cut_path}:10
import "x";
contract H {{
    function check_does_not_break_core_invariant() public {{ assert(true); }}
    function test_does_not_break_core_invariant() public {{ assert(true); }}
}}
"""


def _good_rationale(extra=""):
    return ("this is a deliberately long rationale that clears the minimum char "
            "floor and states why no fund/share conservation invariant applies " + extra)


class _WS:
    def __init__(self):
        self.dir = Path(tempfile.mkdtemp())
        (self.dir / ".auditooor").mkdir()
        (self.dir / "src").mkdir()

    def file(self, rel, body):
        p = self.dir / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body, encoding="utf-8")
        return p

    def value_moving(self, fns):
        self.file(".auditooor/value_moving_functions.json",
                  json.dumps({"function_count": len(fns), "functions": fns}))

    def dispositions(self, rows, approve=True):
        """Write the disposition artifact. By default inject a valid operator
        approval token at the top level (the OTHER guards are what most tests
        exercise). Pass approve=False / approve=<token> to exercise the
        approval gate itself."""
        doc = {"schema": ned.SCHEMA, "dispositions": rows}
        if approve is True:
            doc["approval_ref"] = _operator_approval_token(self.dir)
        elif approve:  # an explicit token string
            doc["approval_ref"] = approve
        self.file(".auditooor/non_economic_dispositions.json", json.dumps(doc))


class TestLibGuards(unittest.TestCase):
    def test_accepts_config_write_rejects_transfer_mover(self):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        ws.file("src/vault/src/Vault.sol", "contract Vault {}")
        ws.value_moving([
            {"file": "src/cfg/src/Cfg.sol", "function": "setCfg",
             "transfer_hit": False, "ledger_write_hit": True},
            {"file": "src/vault/src/Vault.sol", "function": "withdraw",
             "transfer_hit": True, "ledger_write_hit": True},
        ])
        ws.dispositions([
            {"repo": "cfg", "classification": "non-economic-rationale",
             "rationale": _good_rationale("cfg")},
            {"repo": "vault", "classification": "non-economic-rationale",
             "rationale": _good_rationale("vault")},  # MUST be rejected (transfer)
        ])
        accepted = ned.load_dispositions(ws.dir)
        repos = {d["repo"] for d in accepted}
        self.assertIn("cfg", repos)
        self.assertNotIn("vault", repos,
                         "a transfer-mover disposition must NEVER be accepted")

    def test_rejects_invalid_classification(self):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        ws.dispositions([{"repo": "cfg", "classification": "totally-made-up",
                          "rationale": _good_rationale()}])
        self.assertEqual(ned.load_dispositions(ws.dir), [])

    def test_rejects_short_rationale(self):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        ws.dispositions([{"repo": "cfg", "classification": "oos",
                          "rationale": "too short"}])
        self.assertEqual(ned.load_dispositions(ws.dir), [])

    def test_rejects_phantom_cut(self):
        ws = _WS()  # no source file on disk for the repo
        ws.dispositions([{"repo": "ghost", "classification": "oos",
                          "rationale": _good_rationale()}])
        self.assertEqual(ned.load_dispositions(ws.dir), [])

    def test_rejects_wrong_schema(self):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        ws.file(".auditooor/non_economic_dispositions.json",
                json.dumps({"schema": "wrong.schema",
                            "dispositions": [{"repo": "cfg",
                                              "classification": "oos",
                                              "rationale": _good_rationale()}]}))
        self.assertEqual(ned.load_dispositions(ws.dir), [])

    def test_matchers(self):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        ws.dispositions([{"repo": "cfg", "classification": "oos",
                          "rationale": _good_rationale()}])
        d = ned.load_dispositions(ws.dir)
        self.assertIsNotNone(ned.file_is_dispositioned("src/cfg/src/Cfg.sol", d))
        self.assertIsNone(ned.file_is_dispositioned("src/other/X.sol", d))
        self.assertTrue(ned.all_files_dispositioned(
            ["src/cfg/src/A.sol", "src/cfg/src/B.sol"], d))
        self.assertFalse(ned.all_files_dispositioned(
            ["src/cfg/src/A.sol", "src/other/X.sol"], d))
        self.assertFalse(ned.all_files_dispositioned([], d))

    def test_missing_artifact_is_empty(self):
        ws = _WS()
        self.assertEqual(ned.load_dispositions(ws.dir), [])


class TestInvariantFuzzIntegration(unittest.TestCase):
    def setUp(self):
        self.mod = _load("ifc", _TOOLS / "invariant-fuzz-completeness.py")

    def _ws_with_scaffold_dir(self, repo, cut_rel):
        ws = _WS()
        ws.file(cut_rel, "contract C {}")
        # Auto-gen per-function scaffolds live under poc-tests/ - NOT src/**/test,
        # which _is_audited_project_test_dir (invariant-fuzz-completeness) correctly
        # excludes as the AUDITED PROJECT's own hand-written suite. The old fixture at
        # src/{repo}/test was silently skipped by that exclusion; a realistic
        # poc-tests location is enumerated by _find_harness_dirs, and repo-mapping
        # rides the scaffold header's `Function under test: ... at <cut_path>` line.
        ws.file(f"src/{repo}/poc-tests/Halmos_C_fn.t.sol",
                _SCAFFOLD.format(cut_name="C.fn",
                                 cut_path=str(ws.dir / cut_rel)))
        return ws

    def test_scaffold_dir_credited_when_dispositioned(self):
        repo = "cfgrepo"
        cut = f"src/{repo}/src/C.sol"
        ws = self._ws_with_scaffold_dir(repo, cut)
        ws.dispositions([{"repo": repo, "classification": "non-economic-rationale",
                          "rationale": _good_rationale()}])
        res = self.mod.evaluate(ws.dir)
        hd = [h for h in res["harnesses"]
              if h.get("non_economic_disposition")]
        self.assertEqual(len(hd), 1)
        self.assertEqual(hd[0]["fail"], "")
        self.assertEqual(hd[0]["non_economic_disposition"]["credit"],
                         ned.CREDIT_LABEL)

    def test_scaffold_dir_NOT_credited_without_disposition(self):
        repo = "cfgrepo"
        cut = f"src/{repo}/src/C.sol"
        ws = self._ws_with_scaffold_dir(repo, cut)
        # no disposition artifact -> the scaffold dir must FAIL as before.
        res = self.mod.evaluate(ws.dir)
        credited = [h for h in res["harnesses"]
                    if h.get("non_economic_disposition")]
        self.assertEqual(credited, [])
        self.assertTrue(any(h.get("fail") for h in res["harnesses"]))

    def test_genuine_harness_in_dispositioned_repo_NOT_credited(self):
        # A hand-authored property_ harness (no autogen marker) in a dispositioned
        # repo must STILL be evaluated on the real bar - the disposition only
        # credits scaffold-only dirs.
        repo = "cfgrepo"
        cut = f"src/{repo}/src/C.sol"
        ws = _WS()
        ws.file(cut, "contract C {}")
        ws.file(f"src/{repo}/test/RealHarness.sol",
                "pragma solidity ^0.8.0;\ncontract R {\n"
                "  function property_solvency() public {}\n"
                "  function property_two() public {}\n}\n")
        ws.dispositions([{"repo": repo, "classification": "oos",
                          "rationale": _good_rationale()}])
        res = self.mod.evaluate(ws.dir)
        credited = [h for h in res["harnesses"]
                    if h.get("non_economic_disposition")]
        self.assertEqual(credited, [],
                         "a genuine hand-authored harness must not be disposition-credited")


class TestCrossFunctionIntegration(unittest.TestCase):
    def setUp(self):
        self.mod = _load("xfi_disp", _TOOLS / "cross-function-invariant-coverage.py")

    def test_requirement_over_dispositioned_files_credited(self):
        ws = _WS()
        # an add/remove sibling pair entirely inside a dispositioned config repo.
        ws.file("src/reg/src/Registry.sol",
                "pragma solidity ^0.8.0;\ncontract Registry {\n"
                "  function addEntry(uint x) external { items[x] = true; }\n"
                "  function removeEntry(uint x) external { items[x] = false; }\n"
                "  mapping(uint=>bool) items;\n}\n")
        ws.dispositions([{"repo": "reg", "classification": "non-economic-rationale",
                          "rationale": _good_rationale("allow-list, no transfer")}])
        res = self.mod.evaluate(ws.dir)
        disp_cov = [c for c in res.get("covered", [])
                    if c.get("evidence", {}).get("reason") == ned.CREDIT_LABEL]
        self.assertTrue(disp_cov, "requirement over dispositioned files must be credited")
        # and it must NOT appear in uncovered.
        self.assertFalse(any(
            u.get("evidence", {}).get("reason") == ned.CREDIT_LABEL
            for u in res.get("uncovered", [])))

    def test_requirement_with_transfer_mover_NOT_credited(self):
        ws = _WS()
        ws.file("src/reg/src/Registry.sol",
                "pragma solidity ^0.8.0;\ncontract Registry {\n"
                "  function addEntry(uint x) external { items[x] = true; }\n"
                "  function removeEntry(uint x) external { items[x] = false; }\n"
                "  mapping(uint=>bool) items;\n}\n")
        # mark the file a transfer-mover -> disposition rejected -> requirement
        # cannot be credited as non-economic.
        ws.value_moving([{"file": "src/reg/src/Registry.sol", "function": "addEntry",
                          "transfer_hit": True, "ledger_write_hit": True}])
        ws.dispositions([{"repo": "reg", "classification": "non-economic-rationale",
                          "rationale": _good_rationale()}])
        res = self.mod.evaluate(ws.dir)
        disp_cov = [c for c in res.get("covered", [])
                    if c.get("evidence", {}).get("reason") == ned.CREDIT_LABEL]
        self.assertEqual(disp_cov, [],
                         "a transfer-mover must never be credited as non-economic")


class TestAuditHonestyIntegration(unittest.TestCase):
    def setUp(self):
        self.mod = _load("ah_disp", _TOOLS / "audit-honesty-check.py")

    def test_floor_drops_only_dispositioned_config_write(self):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        ws.file("src/vault/src/Vault.sol", "contract Vault {}")
        vmf = {"function_count": 2, "functions": [
            {"file": "src/cfg/src/Cfg.sol", "function": "setCfg", "language": "sol",
             "transfer_hit": False, "ledger_write_hit": True},
            {"file": "src/vault/src/Vault.sol", "function": "withdraw",
             "language": "sol", "transfer_hit": True, "ledger_write_hit": True},
        ]}
        ws.value_moving(vmf["functions"])
        ws.dispositions([{"repo": "cfg", "classification": "non-economic-rationale",
                          "rationale": _good_rationale()}])
        filtered = self.mod._vmf_drop_non_economic_dispositioned(ws.dir, vmf)
        files = {f["file"] for f in filtered["functions"]}
        self.assertNotIn("src/cfg/src/Cfg.sol", files)
        self.assertIn("src/vault/src/Vault.sol", files,
                      "a transfer-mover must stay in the value-moving floor")

    def test_floor_unchanged_without_dispositions(self):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        vmf = {"function_count": 1, "functions": [
            {"file": "src/cfg/src/Cfg.sol", "function": "setCfg", "language": "sol",
             "transfer_hit": False, "ledger_write_hit": True}]}
        out = self.mod._vmf_drop_non_economic_dispositioned(ws.dir, vmf)
        self.assertEqual(len(out["functions"]), 1)

    def test_stub_count_drops_dispositioned_scaffold(self):
        ws = _WS()
        cut = "src/cfg/src/Cfg.sol"
        ws.file(cut, "contract Cfg {}")
        scaffold = ws.file("src/cfg/test/Halmos_Cfg_fn.t.sol",
                           _SCAFFOLD.format(cut_name="Cfg.fn",
                                            cut_path=str(ws.dir / cut)))
        ws.dispositions([{"repo": "cfg", "classification": "non-economic-rationale",
                          "rationale": _good_rationale()}])
        n = self.mod._non_economic_dispositioned_stub_count(ws.dir, [scaffold])
        self.assertEqual(n, 1)

    def test_stub_count_zero_without_disposition(self):
        ws = _WS()
        cut = "src/cfg/src/Cfg.sol"
        ws.file(cut, "contract Cfg {}")
        scaffold = ws.file("src/cfg/test/Halmos_Cfg_fn.t.sol",
                           _SCAFFOLD.format(cut_name="Cfg.fn",
                                            cut_path=str(ws.dir / cut)))
        self.assertEqual(
            self.mod._non_economic_dispositioned_stub_count(ws.dir, [scaffold]), 0)


class TestOperatorApprovalGate(unittest.TestCase):
    """FIX 1: a disposition shrinks a required gate's denominator (a per-gate
    rebuttal) so it must carry an operator-signed approval token. Fail-closed."""

    def _ws_one_config_disposition(self, approve):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        ws.dispositions([{"repo": "cfg", "classification": "non-economic-rationale",
                          "rationale": _good_rationale()}], approve=approve)
        return ws

    def test_agent_authored_no_approval_NOT_credited(self):
        # An agent-authored disposition with NO operator approval must be dropped:
        # the gate denominator is unchanged, the unit stays in the floor.
        ws = self._ws_one_config_disposition(approve=False)
        self.assertEqual(ned.load_dispositions(ws.dir), [],
                         "an unapproved disposition must NEVER credit")

    def test_default_agent_write_token_NOT_credited(self):
        # The exact token an agent already holds (scope 'write') must not green it:
        # only the deliberate 'disposition-approve' scope credits.
        ws = self._ws_one_config_disposition(approve=_agent_write_token(
            _WS().dir))  # wrong-ws + wrong-scope token
        self.assertEqual(ned.load_dispositions(ws.dir), [])

    def test_operator_approved_IS_credited(self):
        ws = self._ws_one_config_disposition(approve=True)
        accepted = ned.load_dispositions(ws.dir)
        self.assertEqual({d["repo"] for d in accepted}, {"cfg"},
                         "an operator-approved disposition must be credited")

    def test_per_entry_approval_ref_credits(self):
        # approval_ref may live on the row itself (not just the artifact top level).
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        tok = _operator_approval_token(ws.dir)
        ws.file(".auditooor/non_economic_dispositions.json", json.dumps(
            {"schema": ned.SCHEMA, "dispositions": [
                {"repo": "cfg", "classification": "oos",
                 "rationale": _good_rationale(), "approval_ref": tok}]}))
        self.assertEqual({d["repo"] for d in ned.load_dispositions(ws.dir)}, {"cfg"})

    def test_wrong_scope_token_NOT_credited(self):
        # A validly-signed operator token WITHOUT the disposition-approve scope
        # (fail-closed on scope).
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        bad, _ = _tok.issue_token(str(ws.dir), owner="operator",
                                  scope=["read", "write"], log=False)
        ws.dispositions([{"repo": "cfg", "classification": "oos",
                          "rationale": _good_rationale()}], approve=bad)
        self.assertEqual(ned.load_dispositions(ws.dir), [])

    def test_wrong_workspace_token_NOT_credited(self):
        # A token minted for a DIFFERENT workspace must not credit here.
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        other = _operator_approval_token(_WS().dir)
        ws.dispositions([{"repo": "cfg", "classification": "oos",
                          "rationale": _good_rationale()}], approve=other)
        self.assertEqual(ned.load_dispositions(ws.dir), [])


class TestValueMovingFloorBreakdown(unittest.TestCase):
    """FIX 2: the honesty-check must expose proven-by-executed-code vs
    dispositioned(operator-approved) vs uncovered as THREE distinct numbers -
    never fold scope-removal into proof/coverage."""

    def setUp(self):
        self.mod = _load("ah_break", _TOOLS / "audit-honesty-check.py")

    def test_three_distinct_counts(self):
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        ws.file("src/vault/src/Vault.sol", "contract Vault {}")
        vmf = {"function_count": 2, "functions": [
            {"file": "src/cfg/src/Cfg.sol", "function": "setCfg", "language": "sol",
             "transfer_hit": False, "ledger_write_hit": True},
            {"file": "src/vault/src/Vault.sol", "function": "withdraw",
             "language": "sol", "transfer_hit": True, "ledger_write_hit": True},
        ]}
        ws.value_moving(vmf["functions"])
        # cfg is dispositioned (operator-approved); vault is a real transfer-mover
        # with NO proof -> uncovered. Nothing is proven by executed code.
        ws.dispositions([{"repo": "cfg", "classification": "non-economic-rationale",
                          "rationale": _good_rationale()}], approve=True)
        detail = self.mod._value_moving_floor_breakdown(ws.dir, vmf)
        self.assertEqual(detail["value_moving_total"], 2)
        self.assertEqual(detail["dispositioned"], 1, "cfg is operator-dispositioned")
        self.assertEqual(detail["uncovered"], 1, "vault has no proof -> uncovered")
        self.assertEqual(detail["proven_by_executed_code"], 0)
        # dispositioned is NEVER folded into proven/uncovered:
        self.assertEqual(
            detail["proven_by_executed_code"] + detail["uncovered"],
            detail["value_moving_total"] - detail["dispositioned"])

    def test_unapproved_disposition_stays_uncovered_not_dispositioned(self):
        # Without operator approval, the config unit is NOT dispositioned - it
        # remains in the floor as uncovered (denominator unchanged).
        ws = _WS()
        ws.file("src/cfg/src/Cfg.sol", "contract Cfg {}")
        vmf = {"function_count": 1, "functions": [
            {"file": "src/cfg/src/Cfg.sol", "function": "setCfg", "language": "sol",
             "transfer_hit": False, "ledger_write_hit": True}]}
        ws.value_moving(vmf["functions"])
        ws.dispositions([{"repo": "cfg", "classification": "non-economic-rationale",
                          "rationale": _good_rationale()}], approve=False)
        detail = self.mod._value_moving_floor_breakdown(ws.dir, vmf)
        self.assertEqual(detail["dispositioned"], 0)
        self.assertEqual(detail["uncovered"], 1)


if __name__ == "__main__":
    unittest.main()
