"""F5: the asymmetry generator no longer uses a private drifted test-regex; it routes
through the single shared classifier (scope_exclusion), so it agrees with every other
gate about what is test/generated scaffolding. Also verifies the head-aware generated
catch (is_oos_dir(head=)) that the heatmap call sites now feed.
"""
import importlib.util
import sys
import unittest
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent.parent
if str(_TOOLS / "lib") not in sys.path:
    sys.path.insert(0, str(_TOOLS / "lib"))
import scope_exclusion as se  # noqa: E402


def _load_asym():
    spec = importlib.util.spec_from_file_location(
        "asym_ctx", str(_TOOLS / "asymmetry-context-extract.py"))
    mod = importlib.util.module_from_spec(spec)
    sys.modules["asym_ctx"] = mod
    spec.loader.exec_module(mod)
    return mod


class TestClassifierUnification(unittest.TestCase):
    def setUp(self):
        self.asym = _load_asym()

    def test_asymmetry_imports_shared_classifier(self):
        self.assertIsNotNone(
            self.asym._shared_is_oos,
            "asymmetry-context-extract must import the shared scope_exclusion.is_oos")

    def test_asymmetry_agrees_with_shared_on_scaffolding(self):
        # exactly the files the polygon asymmetry generator wrongly paired against
        for p in ("consensus/bor/span_mock.go",
                  "accounts/abi/bind/backends/simulated.go"):
            self.assertTrue(self.asym._is_test(p), f"asym should flag {p} as test")
            self.assertEqual(self.asym._is_test(p), se.is_oos(p),
                             f"asym and shared classifier must agree on {p}")

    def test_asymmetry_keeps_production(self):
        for p in ("consensus/bor/bor.go", "core/genesis.go"):
            self.assertFalse(self.asym._is_test(p), f"asym must keep production {p}")

    def test_mock_suffix_is_language_agnostic(self):
        for p in (
            "src/city-aa/old-city-mock.oscript",
            "src/bridge/export_mock.sol",
            "src/protocol-fake.move",
        ):
            self.assertTrue(se.is_test(p), f"scope should drop mock suffix {p}")
            self.assertTrue(se.is_oos(p), f"scope should drop mock suffix {p}")

    def test_generated_header_via_oos_dir_head(self):
        # the exact mechanism the heatmap's 3 call sites now rely on (pass head=)
        head = "// Code generated by abigen. DO NOT EDIT.\npackage bindings\n"
        self.assertTrue(se.is_oos_dir("contracts/bindings/erc20.go", head=head))
        self.assertFalse(se.is_oos_dir("contracts/bindings/erc20.go"),
                         "without head an unconventionally-named binding is not detectable")


if __name__ == "__main__":
    unittest.main(verbosity=2)
