"""Guard tests for skipped-test-marker-scan.py + skipped-test-disposition-gate.py.

Covers the spec's concrete cases incl. the NON-VACUOUS negative (.only is not a
skip; a file with no markers must yield zero rows), scaffold exclusion (the
chimera-scaffold/recon-log-bridge false-positive guard), OOS longest-prefix
exclusion, attribution, artifact shape, and the scope-unreadable error path.
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

_TOOLS = Path(__file__).resolve().parent.parent


def _load(modname: str, filename: str):
    spec = importlib.util.spec_from_file_location(modname, str(_TOOLS / filename))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


scan = _load("_skipscan", "skipped-test-marker-scan.py")
gate = _load("_skipgate", "skipped-test-disposition-gate.py")


def _mk(ws: Path, rel: str, content: str):
    p = ws / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


def _scope(ws: Path, in_scope, out_of_scope=None):
    (ws / "scope.json").write_text(
        json.dumps({"in_scope": in_scope, "out_of_scope": out_of_scope or []}),
        encoding="utf-8",
    )


def _manifest(ws: Path, rows):
    p = ws / ".auditooor" / "inscope_units.jsonl"
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("w", encoding="utf-8") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")


# ---------------------------------------------------------------------------
# POSITIVE go
# ---------------------------------------------------------------------------
def test_positive_go(tmp_path):
    _scope(tmp_path, ["src/foo"])
    _mk(tmp_path, "src/foo/bar_test.go",
        'package foo\n\nfunc TestReset(t *testing.T) {\n\tt.Skip("flaky")\n}\n')
    res = scan.analyze(tmp_path)
    assert res["verdict"] == "found-skipped-tests"
    go_rows = [r for r in res["rows"] if r["lang"] == "go"]
    assert any(r["marker"] == "t.Skip" and r["test_name"] == "TestReset"
               and "flaky" in r["skip_reason"] for r in go_rows)
    art = tmp_path / ".auditooor" / "skipped_test_markers.jsonl"
    assert art.is_file()
    lines = [json.loads(l) for l in art.read_text().splitlines() if l.strip()]
    assert any(r["test_name"] == "TestReset" for r in lines)


# ---------------------------------------------------------------------------
# POSITIVE rust
# ---------------------------------------------------------------------------
def test_positive_rust(tmp_path):
    _scope(tmp_path, ["src/r"])
    _mk(tmp_path, "src/r/lib.rs",
        "#[test]\n#[ignore]\nfn checks_balance() {}\n")
    res = scan.analyze(tmp_path)
    rows = [r for r in res["rows"] if r["lang"] == "rust"]
    assert any(r["marker"] == "#[ignore]" and r["test_name"] == "checks_balance"
               for r in rows)


# ---------------------------------------------------------------------------
# POSITIVE js
# ---------------------------------------------------------------------------
def test_positive_js(tmp_path):
    _scope(tmp_path, ["src/web"])
    _mk(tmp_path, "src/web/a.test.ts",
        'it.skip("reverts on overflow", () => {});\n'
        'xit("old", () => {});\n')
    res = scan.analyze(tmp_path)
    rows = [r for r in res["rows"] if r["lang"] == "js"]
    markers = {r["marker"] for r in rows}
    assert "it.skip" in markers
    assert "xit" in markers
    itskip = next(r for r in rows if r["marker"] == "it.skip")
    assert itskip["test_name"] == "reverts on overflow"


# ---------------------------------------------------------------------------
# EXCLUSION (scaffold)
# ---------------------------------------------------------------------------
def test_exclusion_scaffold(tmp_path):
    _scope(tmp_path, ["poc-tests"])
    _mk(tmp_path, "poc-tests/X-engine-harness/Foo.t.sol",
        "// advisory scaffold generated by auditooor\n"
        "function test_thing() public { vm.skip(true); }\n")
    res = scan.analyze(tmp_path)
    assert all(not r["file"].endswith("Foo.t.sol") for r in res["rows"])
    assert res["n_excluded_scaffold"] >= 1


# ---------------------------------------------------------------------------
# OUT-OF-SCOPE (longest-prefix)
# ---------------------------------------------------------------------------
def test_out_of_scope_prefix(tmp_path):
    _scope(tmp_path, ["src/rust/op-reth"], ["src/rust/kona"])
    _mk(tmp_path, "src/rust/kona/x_test.go",
        'func TestKona(t *testing.T) { t.Skip("oos") }\n')
    _mk(tmp_path, "src/rust/op-reth/y_test.go",
        'func TestReth(t *testing.T) { t.Skip("inscope") }\n')
    res = scan.analyze(tmp_path)
    files = {r["file"] for r in res["rows"]}
    assert not any("kona" in f for f in files)
    assert any("op-reth" in f for f in files)


# ---------------------------------------------------------------------------
# ATTRIBUTION resolved
# ---------------------------------------------------------------------------
def test_attribution_resolved(tmp_path):
    _scope(tmp_path, ["src/foo"])
    _mk(tmp_path, "src/foo/batch_queue.go", "package foo\nfunc Reset() {}\n")
    _mk(tmp_path, "src/foo/batch_queue_test.go",
        'func TestBatchQueue_Reset(t *testing.T) { t.Skip("x") }\n')
    _manifest(tmp_path, [
        {"file": "src/foo/batch_queue.go", "function": "Reset",
         "file_line": "src/foo/batch_queue.go:2", "lang": "go"},
    ])
    res = scan.analyze(tmp_path)
    row = next(r for r in res["rows"] if r["test_name"] == "TestBatchQueue_Reset")
    assert row["attribution"] == "resolved"
    assert row["exercises_symbol"] is not None


# ---------------------------------------------------------------------------
# NEGATIVE / non-vacuous (would FAIL a no-op impl)
# ---------------------------------------------------------------------------
def test_negative_non_vacuous(tmp_path):
    _scope(tmp_path, ["src/x"])
    _mk(tmp_path, "src/x/a.test.ts", 'it.only("runs", () => {});\n')
    _mk(tmp_path, "src/x/b_test.go",
        'func TestX(t *testing.T) { /* no skip */ }\n')
    res = scan.analyze(tmp_path)
    assert res["n_markers"] == 0
    assert res["rows"] == []
    assert res["verdict"] == "pass-skipped-test-scan-clean"


# ---------------------------------------------------------------------------
# ARTIFACT shape
# ---------------------------------------------------------------------------
def test_artifact_shape(tmp_path):
    _scope(tmp_path, ["src/foo"])
    _mk(tmp_path, "src/foo/bar_test.go",
        'func TestReset(t *testing.T) { t.Skip("flaky") }\n')
    scan.analyze(tmp_path, write=True)
    art = tmp_path / ".auditooor" / "skipped_test_markers.jsonl"
    assert art.is_file()
    for line in art.read_text().splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        assert row["schema"] == "auditooor.skipped_test_marker.v1"
        assert row["disposition"] == "open"
        assert row["file"] and isinstance(row["line"], int)
    result = json.loads((tmp_path / ".auditooor" / "skipped_test_markers_result.json").read_text())
    assert "verdict" in result
    assert "n_markers" in result


# ---------------------------------------------------------------------------
# SCOPE-UNREADABLE error path
# ---------------------------------------------------------------------------
def test_scope_unreadable(tmp_path):
    # no scope.json AND no inscope_units.jsonl
    res = scan.analyze(tmp_path)
    assert "no scope" in res["reason"].lower()
    assert res["verdict"] == "scan-error"


def test_scope_unreadable_check_rc(tmp_path, monkeypatch):
    import sys
    monkeypatch.setattr(sys, "argv",
                        ["prog", "--ws", str(tmp_path), "--check"])
    rc = scan.main()
    assert rc == 2


def test_clean_check_rc_zero(tmp_path, monkeypatch):
    import sys
    _scope(tmp_path, ["src/x"])
    _mk(tmp_path, "src/x/b_test.go", 'func TestX(t *testing.T) {}\n')
    monkeypatch.setattr(sys, "argv", ["prog", "--ws", str(tmp_path), "--check"])
    rc = scan.main()
    assert rc == 0  # discovery clean -> rc 0


def test_found_check_rc_zero(tmp_path, monkeypatch):
    import sys
    _scope(tmp_path, ["src/x"])
    _mk(tmp_path, "src/x/b_test.go", 'func TestX(t *testing.T) { t.Skip("y") }\n')
    monkeypatch.setattr(sys, "argv", ["prog", "--ws", str(tmp_path), "--check"])
    rc = scan.main()
    assert rc == 0  # found markers != failure (discovery, not gate)


# ===========================================================================
# Disposition gate
# ===========================================================================
def test_gate_scan_not_run(tmp_path):
    res = gate.evaluate(tmp_path)
    assert res["verdict"] == "fail-scan-not-run"
    assert res["conformance_pass"] is False


def test_gate_empty_passes(tmp_path):
    (tmp_path / ".auditooor").mkdir(parents=True)
    (tmp_path / ".auditooor" / "skipped_test_markers.jsonl").write_text("", encoding="utf-8")
    res = gate.evaluate(tmp_path)
    assert res["verdict"] == "pass-skipped-tests-disposed"
    assert res["conformance_pass"] is True


def test_gate_undisposed_fails(tmp_path):
    _scope(tmp_path, ["src/foo"])
    _mk(tmp_path, "src/foo/bar_test.go",
        'func TestReset(t *testing.T) { t.Skip("flaky") }\n')
    scan.analyze(tmp_path, write=True)
    res = gate.evaluate(tmp_path)
    assert res["verdict"] == "fail-skipped-tests-undisposed"
    assert res["n_open"] >= 1
    assert res["conformance_pass"] is False


def test_gate_disposed_via_rebuttal(tmp_path):
    _scope(tmp_path, ["src/foo"])
    p = _mk(tmp_path, "src/foo/bar_test.go",
            'func TestReset(t *testing.T) { t.Skip("flaky") }\n')
    scan.analyze(tmp_path, write=True)
    # find the row's line
    art = tmp_path / ".auditooor" / "skipped_test_markers.jsonl"
    row = json.loads(art.read_text().splitlines()[0])
    (tmp_path / ".auditooor" / "skipped_test_rebuttals.txt").write_text(
        f"rebut: {row['file']}:{row['line']}: known CI-only flake, behavior covered elsewhere\n",
        encoding="utf-8")
    res = gate.evaluate(tmp_path)
    assert res["verdict"] == "pass-skipped-tests-disposed"
    assert res["conformance_pass"] is True


def test_gate_disposed_via_hunt_sidecar(tmp_path):
    _scope(tmp_path, ["src/foo"])
    _mk(tmp_path, "src/foo/batch_queue.go", "package foo\nfunc Reset() {}\n")
    _mk(tmp_path, "src/foo/batch_queue_test.go",
        'func TestBatchQueue_Reset(t *testing.T) { t.Skip("x") }\n')
    _manifest(tmp_path, [
        {"file": "src/foo/batch_queue.go", "function": "Reset",
         "file_line": "src/foo/batch_queue.go:2", "lang": "go"},
    ])
    scan.analyze(tmp_path, write=True)
    # write a hunt sidecar over the exercised file
    sc = tmp_path / ".auditooor" / "hunt_findings_sidecars"
    sc.mkdir(parents=True, exist_ok=True)
    (sc / "h0.json").write_text(json.dumps({
        "schema": "auditooor.hunt_finding_sidecar.v1",
        "status": "negative",
        "function_anchor": {"file": str(tmp_path / "src/foo/batch_queue.go"), "fn": "Reset"},
        "file_line": "src/foo/batch_queue.go:2",
    }), encoding="utf-8")
    res = gate.evaluate(tmp_path)
    assert res["verdict"] == "pass-skipped-tests-disposed"
    assert res["conformance_pass"] is True


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
