"""Regression tests for the chimera / codegen exploit-queue population drop.

Pins the GENERIC, provably-OOS exclusion that stops Recon chimera
mutation-test scaffolding (chimera_harnesses/, *Mutant*.sol) and protobuf/codegen
(*.pulsar.go / *.pb.go / "Code generated ... DO NOT EDIT") leads from populating
the exploit queue - while guaranteeing REAL in-scope production leads
(src/vault/keeper/*.go, src/nuva-evm-contracts/contracts/*.sol) survive.

Covers:
- lib/synthetic_target_exclusion.py classification + partition helper.
- tools/exploit-queue-source-miner.py run() population-step drop (the direct
  emitter of exploit_queue.source_mined.json that prove-top-leads reads).
"""

from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TOOLS_DIR = ROOT / "tools"
SOURCE_MINER_TOOL = TOOLS_DIR / "exploit-queue-source-miner.py"

if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from lib.synthetic_target_exclusion import (  # noqa: E402
    DROP_REASON_CHIMERA,
    DROP_REASON_CODEGEN,
    DROP_REASON_TEST,
    classify_synthetic_or_codegen,
    is_chimera_mutation_harness_path,
    is_codegen_path,
    partition_synthetic_or_codegen_rows,
)


def _load_source_miner():
    spec = importlib.util.spec_from_file_location("exploit_queue_source_miner", SOURCE_MINER_TOOL)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


class SyntheticTargetPathTests(unittest.TestCase):
    def test_chimera_harness_dir_is_synthetic(self) -> None:
        for path in (
            "chimera_harnesses/CrossChainManager/src/CrossChainManagerMutant.sol",
            "chimera_harnesses/DedicatedVaultRouter/src/DVRMutant_NoReplay.sol",
            "chimera_harnesses/CrossChainManager/src/MockERC20.sol",  # mock in harness dir
            "a/b/chimera_harnesses/Foo.sol",
        ):
            self.assertTrue(is_chimera_mutation_harness_path(path), path)

    def test_mutant_basename_is_synthetic(self) -> None:
        self.assertTrue(is_chimera_mutation_harness_path("out/DVRMutant_RoleEscalation.sol"))
        self.assertTrue(is_chimera_mutation_harness_path("test/DVR_Mutant.t.sol"))

    def test_codegen_suffix_is_generated(self) -> None:
        self.assertTrue(is_codegen_path("src/vault/api/provlabs/vault/v1/events.pulsar.go"))
        self.assertTrue(is_codegen_path("x/types/tx.pb.go"))
        self.assertTrue(is_codegen_path("x/types/query.pb.gw.go"))

    def test_codegen_header_sentinel(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            ws = Path(td)
            gen = ws / "src" / "generated.go"
            gen.parent.mkdir(parents=True, exist_ok=True)
            gen.write_text(
                "// Code generated by mockgen. DO NOT EDIT.\npackage x\n",
                encoding="utf-8",
            )
            # Suffix alone does not match; the header sentinel does.
            self.assertTrue(is_codegen_path("src/generated.go", ws))
            self.assertFalse(is_codegen_path("src/generated.go", None))

    def test_real_production_paths_never_synthetic_or_codegen(self) -> None:
        # ANTI-GREENING GUARDRAIL: real in-scope production sources must survive.
        for path in (
            "src/vault/keeper/reconcile.go",
            "src/vault/keeper/state.go",
            "src/nuva-evm-contracts/contracts/DepositorFactory.sol",
            "src/nuva-evm-contracts/contracts/NuvaVault.sol",
            "contracts/CrossChainManager.sol",  # the real contract, NOT the Mutant
        ):
            self.assertFalse(is_chimera_mutation_harness_path(path), path)
            self.assertFalse(is_codegen_path(path), path)


class PartitionRowsTests(unittest.TestCase):
    def _rows(self) -> list[dict]:
        return [
            {"lead_id": "EQ-1", "contract": "src/vault/keeper/reconcile.go",
             "function": "PerformVaultInterestTransfer"},
            {"lead_id": "EQ-2", "contract": "src/nuva-evm-contracts/contracts/NuvaVault.sol",
             "function": "withdraw"},
            {"lead_id": "EQ-3", "contract": "chimera_harnesses/DedicatedVaultRouter/src/DVRMutant_NoReplay.sol",
             "function": "addAuthorizedCaller"},
            {"lead_id": "EQ-4",
             "contract": "src/vault/api/provlabs/vault/v1/events.pulsar.go",
             "function": "GetCaller"},
            {"lead_id": "EQ-5",
             "impact_path": "chimera_harnesses/CrossChainManager/src/CrossChainManagerMutant.sol.updateCrossChainConfig",
             "function": "updateCrossChainConfig"},
        ]

    def test_partition_drops_only_synthetic_and_codegen(self) -> None:
        survivors, dropped, reasons = partition_synthetic_or_codegen_rows(self._rows())
        surviving_ids = sorted(r["lead_id"] for r in survivors)
        dropped_ids = sorted(r["lead_id"] for r in dropped)
        self.assertEqual(surviving_ids, ["EQ-1", "EQ-2"])  # real production leads survive
        self.assertEqual(dropped_ids, ["EQ-3", "EQ-4", "EQ-5"])  # chimera + codegen dropped
        self.assertEqual(reasons.get(DROP_REASON_CODEGEN), 1)
        self.assertEqual(reasons.get(DROP_REASON_CHIMERA), 2)

    def test_classify_reasons(self) -> None:
        rows = {r["lead_id"]: r for r in self._rows()}
        self.assertEqual(classify_synthetic_or_codegen(rows["EQ-3"])[1], DROP_REASON_CHIMERA)
        self.assertEqual(classify_synthetic_or_codegen(rows["EQ-4"])[1], DROP_REASON_CODEGEN)
        self.assertEqual(classify_synthetic_or_codegen(rows["EQ-1"]), (False, "", ""))

    def test_test_and_poc_scaffold_dropped(self) -> None:
        # Regression (nuva): the 10 remaining non-terminal high leads all targeted
        # Go test files (economic_invariant_test.go, the filed finding's own
        # zz_chainhalt_abci_poc_test.go); test/PoC/mock scaffolding is never
        # deployed and must be dropped, while production Go/Sol survives.
        for p in ("src/vault/keeper/economic_invariant_test.go",
                  "src/vault/keeper/zz_chainhalt_abci_poc_test.go",
                  "test/CrossChainVault.t.sol", "contracts/mocks/MockToken.sol",
                  "src/vault/simulation/operations.go",  # cosmos simd sim ops (SimulateMsg*)
                  "simapp/app.go"):
            drop, reason, _ = classify_synthetic_or_codegen({"contract": p})
            self.assertTrue(drop, p)
            self.assertEqual(reason, DROP_REASON_TEST)
        for p in ("src/vault/keeper/reconcile.go", "src/vault/keeper/valuation_engine.go",
                  "src/nuva-evm-contracts/contracts/CrossChainVault.sol"):
            self.assertEqual(classify_synthetic_or_codegen({"contract": p}), (False, "", ""), p)


class SourceMinerPopulationDropTests(unittest.TestCase):
    def test_source_miner_drops_chimera_and_codegen_keeps_production(self) -> None:
        tool = _load_source_miner()
        with tempfile.TemporaryDirectory() as td:
            ws = Path(td)
            queue_rows = [
                # real in-scope production lead (the dup-of-filed reconcile.go row)
                {"lead_id": "EQ-099", "contract": "src/vault/keeper/reconcile.go",
                 "function": "PerformVaultInterestTransfer",
                 "proof_status": "killed", "quality_gate_status": "disqualified",
                 "title": "reconcile interest transfer"},
                # chimera mutant harness lead
                {"lead_id": "EQ-3",
                 "contract": "chimera_harnesses/DedicatedVaultRouter/src/DVRMutant_NoReplay.sol",
                 "function": "addAuthorizedCaller",
                 "proof_status": "killed", "quality_gate_status": "disqualified",
                 "title": "mutant harness"},
                # protobuf codegen lead
                {"lead_id": "EQ-4",
                 "contract": "src/vault/api/provlabs/vault/v1/events.pulsar.go",
                 "function": "GetCaller",
                 "proof_status": "killed", "quality_gate_status": "disqualified",
                 "title": "pulsar getter"},
            ]
            queue_path = ws / ".auditooor" / "exploit_queue.json"
            queue_path.parent.mkdir(parents=True, exist_ok=True)
            queue_path.write_text(
                json.dumps({"schema": "auditooor.exploit_queue.v1", "queue": queue_rows}),
                encoding="utf-8",
            )

            summary = tool.run(["--workspace", str(ws), "--json"])
            self.assertEqual(summary["synthetic_target_dropped"], 2)
            reasons = summary["synthetic_target_drop_reasons"]
            self.assertEqual(reasons.get("chimera_mutation_test_harness"), 1)
            self.assertEqual(reasons.get("protobuf_or_codegen"), 1)

            patched = json.loads(
                (ws / ".auditooor" / "exploit_queue.source_mined.json").read_text(encoding="utf-8")
            )
            ids = sorted(r["lead_id"] for r in patched["queue"])
            self.assertIn("EQ-099", ids)  # real production lead survived
            self.assertNotIn("EQ-3", ids)  # chimera mutant dropped
            self.assertNotIn("EQ-4", ids)  # codegen dropped

    def test_existing_terminal_chimera_reinjection_is_redropped(self) -> None:
        # Regression: preserve_existing_terminal_rows re-merges rows from a PRIOR
        # exploit_queue.source_mined.json. When that prior file was written before
        # this exclusion existed it carries chimera/codegen terminal rows; the
        # partition on the FRESH queue never sees them, so they silently re-inject
        # into the persisted queue (observed on nuva: 12542 -> a still-polluted
        # 12524 with 6204 chimera). The final persisted queue MUST re-apply the drop.
        tool = _load_source_miner()
        with tempfile.TemporaryDirectory() as td:
            ws = Path(td)
            a = ws / ".auditooor"
            a.mkdir(parents=True, exist_ok=True)
            (a / "exploit_queue.json").write_text(json.dumps({
                "schema": "auditooor.exploit_queue.v1",
                "queue": [{"lead_id": "EQ-099", "contract": "src/vault/keeper/reconcile.go",
                           "function": "PerformVaultInterestTransfer",
                           "proof_status": "killed", "quality_gate_status": "disqualified",
                           "title": "reconcile"}],
            }), encoding="utf-8")
            # PRIOR (pre-exclusion) source_mined.json carrying a chimera terminal row
            (a / "exploit_queue.source_mined.json").write_text(json.dumps({
                "schema": "auditooor.exploit_queue.v1",
                "queue": [{"lead_id": "EQ-OLD-CHIMERA",
                           "contract": "chimera_harnesses/DedicatedVaultRouter/src/DVRMutant_NoReplay.sol",
                           "function": "addAuthorizedCaller", "terminal": True,
                           "proof_status": "killed", "quality_gate_status": "disqualified",
                           "title": "old chimera terminal"}],
            }), encoding="utf-8")
            tool.run(["--workspace", str(ws), "--json"])
            patched = json.loads(
                (a / "exploit_queue.source_mined.json").read_text(encoding="utf-8"))
            ids = sorted(r["lead_id"] for r in patched["queue"])
            self.assertIn("EQ-099", ids)  # real production survives the merge
            self.assertNotIn("EQ-OLD-CHIMERA", ids)  # re-injected chimera terminal re-dropped


if __name__ == "__main__":
    unittest.main()
