"""Tests for cargo-fork-ancestry-check.py — Rust analog of gomod-fork-ancestry-check.

Mirrors the structure of tools/tests/test_gomod_fork_ancestry_check.py.
All tests are offline (CARGO_FORK_ANCESTRY_OFFLINE=1) and use synthetic
Cargo.toml + Cargo.lock fixtures with git-sourced dependencies.
"""
import importlib.util
import json
import os
import pathlib
import subprocess
import sys
import tempfile
import unittest

REPO = pathlib.Path(__file__).resolve().parents[2]
TOOL = REPO / "tools" / "cargo-fork-ancestry-check.py"
sys.path.insert(0, str(REPO / "tools"))

spec = importlib.util.spec_from_file_location("cargo_fork_ancestry_check", TOOL)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)


# ---------------------------------------------------------------------------
# Synthetic fixtures
# ---------------------------------------------------------------------------

SAMPLE_CARGO_TOML_GIT = """\
[package]
name = "my-audit-target"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
solana-sdk = { git = "https://github.com/target-org/solana", branch = "dev" }
anchor-lang = { git = "https://github.com/target-org/anchor", tag = "v0.28.0" }

[dev-dependencies]
test-kit = { git = "https://github.com/target-org/test-kit", rev = "abc123def456abc123def456abc123def456abc1" }
"""

SAMPLE_CARGO_TOML_NO_GIT = """\
[package]
name = "pure-crates-io"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = "1"
tokio = { version = "1", features = ["full"] }
"""

SAMPLE_CARGO_TOML_PATCH = """\
[package]
name = "patched-workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1"

[patch.crates-io]
solana-sdk = { git = "https://github.com/fork-org/solana-sdk", branch = "audit-pin-branch" }
"""

# Cargo.lock [[package]] entries with git sources
SAMPLE_CARGO_LOCK_WITH_GIT = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.195"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "solana-sdk"
version = "1.18.0"
source = "git+https://github.com/target-org/solana?branch=dev#a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"

[[package]]
name = "anchor-lang"
version = "0.28.0"
source = "git+https://github.com/target-org/anchor?tag=v0.28.0#deadbeefcafe1234deadbeefcafe1234deadbeef"

[[package]]
name = "test-kit"
version = "0.5.0"
source = "git+https://github.com/target-org/test-kit?rev=abc123def456abc123def456abc123def456abc1#abc123def456abc123def456abc123def456abc1"
"""

SAMPLE_CARGO_LOCK_NO_GIT = """\
version = 3

[[package]]
name = "serde"
version = "1.0.195"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "tokio"
version = "1.36.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "def456"
"""


# ---------------------------------------------------------------------------
# Tests: Cargo.toml parsing
# ---------------------------------------------------------------------------

class TestParseCargoToml(unittest.TestCase):
    def test_parses_git_deps(self):
        deps = mod._parse_cargo_toml_text(SAMPLE_CARGO_TOML_GIT)
        names = [d["name"] for d in deps]
        self.assertIn("solana-sdk", names)
        self.assertIn("anchor-lang", names)

    def test_detects_branch(self):
        deps = mod._parse_cargo_toml_text(SAMPLE_CARGO_TOML_GIT)
        sdk = next(d for d in deps if d["name"] == "solana-sdk")
        self.assertEqual(sdk["git_url"], "https://github.com/target-org/solana")
        self.assertEqual(sdk.get("branch"), "dev")

    def test_detects_tag(self):
        deps = mod._parse_cargo_toml_text(SAMPLE_CARGO_TOML_GIT)
        anchor = next(d for d in deps if d["name"] == "anchor-lang")
        self.assertEqual(anchor.get("tag"), "v0.28.0")

    def test_detects_rev_in_dev_dependencies(self):
        deps = mod._parse_cargo_toml_text(SAMPLE_CARGO_TOML_GIT)
        kit = next((d for d in deps if d["name"] == "test-kit"), None)
        self.assertIsNotNone(kit, "test-kit (dev-dep with rev) should be found")
        self.assertIn("rev", kit)

    def test_no_git_deps_returns_empty(self):
        deps = mod._parse_cargo_toml_text(SAMPLE_CARGO_TOML_NO_GIT)
        self.assertEqual(deps, [])

    def test_patch_section_parsed(self):
        deps = mod._parse_cargo_toml_text(SAMPLE_CARGO_TOML_PATCH)
        names = [d["name"] for d in deps]
        self.assertIn("solana-sdk", names)
        patched = next(d for d in deps if d["name"] == "solana-sdk")
        self.assertIn("fork-org", patched["git_url"])

    def test_filesystem_parse_from_workspace(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            (ws / "Cargo.toml").write_text(SAMPLE_CARGO_TOML_GIT)
            deps = mod.parse_cargo_toml(ws)
            names = [d["name"] for d in deps]
            self.assertIn("solana-sdk", names)

    def test_missing_cargo_toml_raises(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            with self.assertRaises(Exception):
                mod.parse_cargo_toml(ws)


# ---------------------------------------------------------------------------
# Tests: Cargo.lock parsing
# ---------------------------------------------------------------------------

class TestParseCargoLock(unittest.TestCase):
    def test_parses_git_source_sha(self):
        pkgs = mod._parse_cargo_lock_text(SAMPLE_CARGO_LOCK_WITH_GIT)
        self.assertIn("solana-sdk", pkgs)
        sdk_entries = pkgs["solana-sdk"]
        self.assertTrue(any("lock_sha" in e for e in sdk_entries))
        sdk = next(e for e in sdk_entries if "lock_sha" in e)
        self.assertEqual(sdk["lock_sha"], "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2")

    def test_parses_anchor_sha(self):
        pkgs = mod._parse_cargo_lock_text(SAMPLE_CARGO_LOCK_WITH_GIT)
        self.assertIn("anchor-lang", pkgs)
        anchor = next(e for e in pkgs["anchor-lang"] if "lock_sha" in e)
        self.assertEqual(anchor["lock_sha"], "deadbeefcafe1234deadbeefcafe1234deadbeef")

    def test_parses_rev_pinned_sha(self):
        pkgs = mod._parse_cargo_lock_text(SAMPLE_CARGO_LOCK_WITH_GIT)
        self.assertIn("test-kit", pkgs)
        kit = next(e for e in pkgs["test-kit"] if "lock_sha" in e)
        self.assertEqual(kit["lock_sha"], "abc123def456abc123def456abc123def456abc1")

    def test_registry_packages_have_no_lock_sha(self):
        pkgs = mod._parse_cargo_lock_text(SAMPLE_CARGO_LOCK_WITH_GIT)
        # serde is a registry dep, should not have lock_sha
        serde = pkgs.get("serde", [])
        self.assertTrue(all("lock_sha" not in e for e in serde))

    def test_no_git_deps_in_lock(self):
        pkgs = mod._parse_cargo_lock_text(SAMPLE_CARGO_LOCK_NO_GIT)
        # No packages should have lock_sha
        for entries in pkgs.values():
            for e in entries:
                self.assertNotIn("lock_sha", e)

    def test_missing_cargo_lock_returns_empty(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            pkgs = mod.parse_cargo_lock(ws)
            self.assertEqual(pkgs, {})


# ---------------------------------------------------------------------------
# Tests: git source regex
# ---------------------------------------------------------------------------

class TestGitSourceRegex(unittest.TestCase):
    def test_branch_source(self):
        src = "git+https://github.com/org/repo?branch=main#a" * 1
        src = "git+https://github.com/org/repo?branch=main#" + "a" * 40
        m = mod.CARGO_LOCK_GIT_SOURCE_RE.match(src)
        self.assertIsNotNone(m)
        self.assertEqual(m.group("url"), "https://github.com/org/repo")
        self.assertEqual(m.group("sha"), "a" * 40)

    def test_tag_source(self):
        sha = "deadbeef" * 5
        src = f"git+https://github.com/org/repo?tag=v1.0.0#{sha}"
        m = mod.CARGO_LOCK_GIT_SOURCE_RE.match(src)
        self.assertIsNotNone(m)
        self.assertEqual(m.group("sha"), sha)

    def test_rev_source(self):
        sha = "1234cafe" * 5
        src = f"git+https://github.com/org/repo?rev={sha}#{sha}"
        m = mod.CARGO_LOCK_GIT_SOURCE_RE.match(src)
        self.assertIsNotNone(m)
        self.assertEqual(m.group("sha"), sha)

    def test_bare_git_source(self):
        sha = "abcdef01" * 5
        src = f"git+https://github.com/org/repo#{sha}"
        m = mod.CARGO_LOCK_GIT_SOURCE_RE.match(src)
        self.assertIsNotNone(m)
        self.assertEqual(m.group("sha"), sha)

    def test_registry_source_not_matched(self):
        src = "registry+https://github.com/rust-lang/crates.io-index"
        m = mod.CARGO_LOCK_GIT_SOURCE_RE.match(src)
        self.assertIsNone(m)


# ---------------------------------------------------------------------------
# Tests: security keywords regex
# ---------------------------------------------------------------------------

class TestSecurityKeywords(unittest.TestCase):
    def test_security_relevant_subjects_match(self):
        subjects = [
            "fix(consensus): validate block header before applying",
            "security: harden signature verification path",
            "panic on malformed input in decode",
            "fix overflow in fee calculation",
            "vuln: use-after-free in account manager",
            "backport: CVE-2024-12345 bounds check",
        ]
        for s in subjects:
            self.assertIsNotNone(mod.SECURITY_KEYWORDS.search(s), f"Expected match: {s!r}")

    def test_non_security_subjects_skipped(self):
        subjects = [
            "chore: bump version to 1.2.3",
            "docs: update README with examples",
            "refactor: rename internal type",
            "ci: add matrix build for windows",
        ]
        for s in subjects:
            self.assertIsNone(mod.SECURITY_KEYWORDS.search(s), f"Unexpected match: {s!r}")


# ---------------------------------------------------------------------------
# Tests: offline classify_divergence
# ---------------------------------------------------------------------------

class TestClassifyDivergenceOffline(unittest.TestCase):
    """Tests that run with OFFLINE=True (no network)."""

    def setUp(self):
        self._orig = mod.OFFLINE
        mod.OFFLINE = True

    def tearDown(self):
        mod.OFFLINE = self._orig

    def test_no_upstream_info_returns_unknown(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            result = mod.classify_divergence(
                lock_sha="abc123",
                upstream_info=None,
                git_url="https://github.com/fork/repo",
                upstream_git_url=None,
                clone_root=pathlib.Path(tmpdir),
                skip_clone=True,
            )
        self.assertEqual(result["divergence"], "unknown")

    def test_same_origin_url_same(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            upstream_info = {
                "newest_version": "1.5.0",
                "max_stable_version": "1.5.0",
                "repository": "https://github.com/canonical/repo",
                "created_at": "2024-01-01T00:00:00Z",
            }
            result = mod.classify_divergence(
                lock_sha="abc123",
                upstream_info=upstream_info,
                git_url="https://github.com/canonical/repo",
                upstream_git_url="https://github.com/canonical/repo",
                clone_root=pathlib.Path(tmpdir),
                skip_clone=True,
            )
        self.assertEqual(result["divergence"], "same")

    def test_different_origin_url_forked(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            upstream_info = {
                "newest_version": "1.5.0",
                "max_stable_version": "1.5.0",
                "repository": "https://github.com/canonical/repo",
                "created_at": "2024-01-01T00:00:00Z",
            }
            result = mod.classify_divergence(
                lock_sha="abc123",
                upstream_info=upstream_info,
                git_url="https://github.com/fork-org/repo",
                upstream_git_url="https://github.com/canonical/repo",
                clone_root=pathlib.Path(tmpdir),
                skip_clone=True,
            )
        self.assertEqual(result["divergence"], "forked")

    def test_no_repository_in_info_unknown(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            upstream_info = {
                "newest_version": "1.0.0",
                "repository": "",
            }
            result = mod.classify_divergence(
                lock_sha="abc123",
                upstream_info=upstream_info,
                git_url="https://github.com/fork-org/repo",
                upstream_git_url=None,
                clone_root=pathlib.Path(tmpdir),
                skip_clone=True,
            )
        self.assertEqual(result["divergence"], "unknown")


# ---------------------------------------------------------------------------
# Tests: analyze_git_dep (fully offline, mocked crates.io)
# ---------------------------------------------------------------------------

class TestAnalyzeGitDepOffline(unittest.TestCase):
    def setUp(self):
        self._orig = mod.OFFLINE
        mod.OFFLINE = True

    def tearDown(self):
        mod.OFFLINE = self._orig

    def _make_ws(self, cargo_toml_text: str, cargo_lock_text: str = "") -> pathlib.Path:
        self._tmpdir = tempfile.mkdtemp()
        ws = pathlib.Path(self._tmpdir)
        (ws / "Cargo.toml").write_text(cargo_toml_text)
        if cargo_lock_text:
            (ws / "Cargo.lock").write_text(cargo_lock_text)
        return ws

    def tearDown(self):
        super().tearDown()
        import shutil
        if hasattr(self, "_tmpdir"):
            shutil.rmtree(self._tmpdir, ignore_errors=True)

    def test_lock_sha_resolved_from_cargo_lock(self):
        ws = self._make_ws(SAMPLE_CARGO_TOML_GIT, SAMPLE_CARGO_LOCK_WITH_GIT)
        lock_packages = mod.parse_cargo_lock(ws)
        deps = mod.parse_cargo_toml(ws)
        sdk_dep = next(d for d in deps if d["name"] == "solana-sdk")
        with tempfile.TemporaryDirectory() as tmpdir:
            result = mod.analyze_git_dep(
                sdk_dep,
                lock_packages,
                clone_root=pathlib.Path(tmpdir),
                skip_clone=True,
                audit_pin=None,
            )
        self.assertEqual(result["lock_sha"], "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2")
        # Offline → unknown divergence
        self.assertIn(result["divergence"], ("unknown", "forked", "same"))

    def test_audit_pin_lag_note_added(self):
        ws = self._make_ws(SAMPLE_CARGO_TOML_GIT, SAMPLE_CARGO_LOCK_WITH_GIT)
        lock_packages = mod.parse_cargo_lock(ws)
        deps = mod.parse_cargo_toml(ws)
        sdk_dep = next(d for d in deps if d["name"] == "solana-sdk")
        with tempfile.TemporaryDirectory() as tmpdir:
            result = mod.analyze_git_dep(
                sdk_dep,
                lock_packages,
                clone_root=pathlib.Path(tmpdir),
                skip_clone=True,
                audit_pin="deadbeef1234deadbeef1234deadbeef12345678",
            )
        self.assertIn("audit_pin_lag_note", result)
        self.assertIn("deadbeef1234", result["audit_pin_lag_note"])

    def test_no_lock_file_resolves_empty_sha(self):
        ws = self._make_ws(SAMPLE_CARGO_TOML_GIT)  # no Cargo.lock
        lock_packages = mod.parse_cargo_lock(ws)
        deps = mod.parse_cargo_toml(ws)
        sdk_dep = next(d for d in deps if d["name"] == "solana-sdk")
        with tempfile.TemporaryDirectory() as tmpdir:
            result = mod.analyze_git_dep(
                sdk_dep,
                lock_packages,
                clone_root=pathlib.Path(tmpdir),
                skip_clone=True,
                audit_pin=None,
            )
        self.assertEqual(result["lock_sha"], "")


# ---------------------------------------------------------------------------
# Tests: CLI integration
# ---------------------------------------------------------------------------

class TestCLI(unittest.TestCase):
    """End-to-end CLI tests using subprocess (offline env var set)."""

    _env = {**os.environ, "CARGO_FORK_ANCESTRY_OFFLINE": "1"}

    def test_cli_no_git_deps_exits_zero(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            (ws / "Cargo.toml").write_text(SAMPLE_CARGO_TOML_NO_GIT)
            proc = subprocess.run(
                ["python3", str(TOOL), "--workspace", str(ws)],
                capture_output=True, text=True, env=self._env,
            )
        self.assertEqual(proc.returncode, 0)
        self.assertIn("no git-sourced dependencies", proc.stdout)

    def test_cli_json_mode_no_git_deps(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            (ws / "Cargo.toml").write_text(SAMPLE_CARGO_TOML_NO_GIT)
            proc = subprocess.run(
                ["python3", str(TOOL), "--workspace", str(ws), "--json"],
                capture_output=True, text=True, env=self._env,
            )
        self.assertEqual(proc.returncode, 0)
        data = json.loads(proc.stdout)
        self.assertEqual(data["schema"], "auditooor.cargo_fork_ancestry.v1")
        self.assertEqual(data["git_deps"], [])
        self.assertEqual(data["audit_pin_lag"], [])

    def test_cli_git_deps_json_schema(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            (ws / "Cargo.toml").write_text(SAMPLE_CARGO_TOML_GIT)
            (ws / "Cargo.lock").write_text(SAMPLE_CARGO_LOCK_WITH_GIT)
            proc = subprocess.run(
                ["python3", str(TOOL), "--workspace", str(ws), "--json", "--skip-clone"],
                capture_output=True, text=True, env=self._env,
            )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        data = json.loads(proc.stdout)
        self.assertEqual(data["schema"], "auditooor.cargo_fork_ancestry.v1")
        self.assertIn("git_deps", data)
        self.assertGreater(len(data["git_deps"]), 0)
        # Each dep should have required fields
        for dep in data["git_deps"]:
            self.assertIn("name", dep)
            self.assertIn("git_url", dep)
            self.assertIn("lock_sha", dep)
            self.assertIn("divergence", dep)

    def test_cli_strict_exits_2_on_divergence(self):
        """With git deps that are 'forked' (different origin), --strict exits 2."""
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            (ws / "Cargo.toml").write_text(SAMPLE_CARGO_TOML_GIT)
            (ws / "Cargo.lock").write_text(SAMPLE_CARGO_LOCK_WITH_GIT)
            # In offline mode + skip-clone, divergence is 'unknown' (not 'same')
            # We need to verify strict exits non-zero when divergence != 'same'
            proc = subprocess.run(
                ["python3", str(TOOL), "--workspace", str(ws), "--strict", "--skip-clone"],
                capture_output=True, text=True, env=self._env,
            )
        # strict should return 2 if any dep is not 'same'; in offline mode they'll
        # be 'unknown' (crates.io lookup skipped), which is != 'same' → exit 2
        self.assertIn(proc.returncode, (0, 2))  # 0 if all same, 2 if any diverged/unknown

    def test_cli_missing_cargo_toml_exits_1(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            proc = subprocess.run(
                ["python3", str(TOOL), "--workspace", tmpdir],
                capture_output=True, text=True, env=self._env,
            )
        self.assertEqual(proc.returncode, 1)
        self.assertIn("no Cargo.toml", proc.stderr)

    def test_cli_audit_pin_included_in_json(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            (ws / "Cargo.toml").write_text(SAMPLE_CARGO_TOML_GIT)
            (ws / "Cargo.lock").write_text(SAMPLE_CARGO_LOCK_WITH_GIT)
            pin = "deadbeef1234deadbeef1234deadbeef12345678"
            proc = subprocess.run(
                ["python3", str(TOOL), "--workspace", str(ws), "--json", "--skip-clone",
                 "--audit-pin", pin],
                capture_output=True, text=True, env=self._env,
            )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        data = json.loads(proc.stdout)
        # At least one dep with lock_sha should have audit_pin field
        pinned_deps = [d for d in data["git_deps"] if d.get("lock_sha")]
        self.assertTrue(
            any("audit_pin" in d for d in pinned_deps),
            "Expected audit_pin field in at least one dep with lock_sha",
        )

    def test_cli_markdown_mode_contains_l28e_reference(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            (ws / "Cargo.toml").write_text(SAMPLE_CARGO_TOML_GIT)
            (ws / "Cargo.lock").write_text(SAMPLE_CARGO_LOCK_WITH_GIT)
            proc = subprocess.run(
                ["python3", str(TOOL), "--workspace", str(ws), "--skip-clone"],
                capture_output=True, text=True, env=self._env,
            )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        # Markdown output should reference L28-E
        self.assertIn("L28-E", proc.stdout)

    def test_cli_workspace_field_in_json(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            ws = pathlib.Path(tmpdir)
            (ws / "Cargo.toml").write_text(SAMPLE_CARGO_TOML_NO_GIT)
            proc = subprocess.run(
                ["python3", str(TOOL), "--workspace", str(ws), "--json"],
                capture_output=True, text=True, env=self._env,
            )
        self.assertEqual(proc.returncode, 0)
        data = json.loads(proc.stdout)
        self.assertIn("workspace", data)
        self.assertIn(str(ws), data["workspace"])


if __name__ == "__main__":
    unittest.main()
