#!/usr/bin/env python3
"""Regression tests for tools/docs-check-auto-fix-broken.py.

The auto-fixer is the systematic counterpart to NEG-D's hand-curated
archive rewriter; it has to remain idempotent and never touch CASE-C /
CASE-D links. These tests exercise the classifier on a synthetic repo
that mirrors the post-archive layout (docs/archive/<YYYY-MM>/ buckets
plus a small docs/ keep-list).
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "tools" / "docs-check-auto-fix-broken.py"


def _write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(body).lstrip("\n"), encoding="utf-8")


class DocsCheckAutoFixBrokenTest(unittest.TestCase):
    """End-to-end: build a synthetic repo, write a broken-link report,
    invoke the script with --root pointing at the synth repo, and assert
    the rewrites + audit output match expectations."""

    def setUp(self) -> None:
        # The script hard-codes REPO from its own __file__ location, so we
        # need to invoke a copy of the script that sees the synthetic
        # repo as its parent. We do this by symlinking the script into
        # the synth repo and invoking it from there.
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name) / "repo"
        (self.root / "tools").mkdir(parents=True)
        shutil.copyfile(SCRIPT, self.root / "tools" / "docs-check-auto-fix-broken.py")
        (self.root / "tools" / "docs-check-auto-fix-broken.py").chmod(0o755)

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def _build_synthetic_repo(self) -> None:
        # Keep-list survivors.
        _write(self.root / "docs" / "WORKFLOW.md", "# Workflow keep-list\n")
        _write(self.root / "docs" / "VAULT_MCP_SERVER.md", "# Vault MCP\n")
        # Archive buckets.
        _write(
            self.root / "docs" / "archive" / "2026-04" / "OLD_DOC.md",
            "old doc\n",
        )
        _write(
            self.root / "docs" / "archive" / "2026-05" / "ANOTHER_OLD.md",
            "another old doc\n",
        )
        # CASE-A source (top-level case_study/ keep-list referring to
        # an archived doc).
        _write(
            self.root / "case_study" / "engagement.md",
            """\
            See [old](../docs/OLD_DOC.md) for details.
            """,
        )
        # CASE-B source (archived doc referring to keep-list doc with
        # the old relative depth).
        _write(
            self.root / "docs" / "archive" / "2026-05" / "PLAN.md",
            """\
            See [workflow](WORKFLOW.md) for the canonical flow.
            See [vault](VAULT_MCP_SERVER.md) for callable list.
            """,
        )
        # CASE-B source (archived doc referring to a tool by old depth).
        _write(self.root / "tools" / "real_tool.py", "# real\n")
        _write(
            self.root / "docs" / "archive" / "2026-04" / "POSTMORTEM.md",
            """\
            Tool: [tool](../tools/real_tool.py)
            """,
        )
        # CASE-C source (archived doc with deleted target).
        _write(
            self.root / "docs" / "archive" / "2026-05" / "OBSOLETE.md",
            """\
            Stub: [gone](../reference/gone.jsonl)
            """,
        )
        # CASE-D source (CLAUDE.md stale-as-design at repo root).
        _write(
            self.root / "CLAUDE.md",
            """\
            See [stale](docs/STALE_BY_DESIGN.md) - do not auto-rewrite.
            """,
        )

    def _write_report(self) -> Path:
        # Mirror the CROSS_LINK_REPORT.md format the tool parses.
        body = textwrap.dedent(
            """\
            # Cross-Link Validation Report

            Generated by `tools/cross-link-validator.py`. Do not edit by hand.

            ## Summary

            - Broken: **6**

            ## Broken Links

            | Source | Line | Target |
            |--------|------|--------|
            | `case_study/engagement.md` | 1 | `../docs/OLD_DOC.md` |
            | `docs/archive/2026-05/PLAN.md` | 1 | `WORKFLOW.md` |
            | `docs/archive/2026-05/PLAN.md` | 2 | `VAULT_MCP_SERVER.md` |
            | `docs/archive/2026-04/POSTMORTEM.md` | 1 | `../tools/real_tool.py` |
            | `docs/archive/2026-05/OBSOLETE.md` | 1 | `../reference/gone.jsonl` |
            | `CLAUDE.md` | 1 | `docs/STALE_BY_DESIGN.md` |
            """
        )
        report_path = self.root / "docs" / "CROSS_LINK_REPORT.md"
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(body, encoding="utf-8")
        return report_path

    def _invoke(self, *args: str) -> subprocess.CompletedProcess[str]:
        # Run the copied script so its REPO derivation lands on
        # self.root rather than the real repository.
        return subprocess.run(
            [
                sys.executable,
                str(self.root / "tools" / "docs-check-auto-fix-broken.py"),
                *args,
            ],
            capture_output=True,
            text=True,
            timeout=20,
        )

    def test_dry_run_classifies_all_four_cases(self) -> None:
        self._build_synthetic_repo()
        self._write_report()
        audit_path = self.root / "audit.json"
        result = self._invoke(
            "--dry-run",
            "--audit-out", str(audit_path),
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        audit = json.loads(audit_path.read_text(encoding="utf-8"))
        counts = audit["counts"]
        self.assertEqual(counts.get("CASE-A"), 1)
        self.assertGreaterEqual(counts.get("CASE-B", 0), 3)
        self.assertGreaterEqual(counts.get("CASE-C", 0), 1)
        self.assertEqual(counts.get("CASE-D"), 1)
        # Dry-run never rewrites.
        self.assertEqual(audit["rewrites_applied"], 0)

    def test_apply_rewrites_case_a_and_b_only(self) -> None:
        self._build_synthetic_repo()
        self._write_report()
        audit_path = self.root / "audit.json"
        result = self._invoke("--audit-out", str(audit_path))
        self.assertEqual(result.returncode, 0, result.stderr)

        # CASE-A: case_study/engagement.md rewritten to archive path.
        eng = (self.root / "case_study" / "engagement.md").read_text(
            encoding="utf-8"
        )
        self.assertIn("docs/archive/2026-04/OLD_DOC.md", eng)
        self.assertNotIn("(../docs/OLD_DOC.md)", eng)

        # CASE-B: PLAN.md links rewritten with extra "../" depth.
        plan = (
            self.root / "docs" / "archive" / "2026-05" / "PLAN.md"
        ).read_text(encoding="utf-8")
        self.assertIn("../../WORKFLOW.md", plan)
        self.assertIn("../../VAULT_MCP_SERVER.md", plan)

        # CASE-B repo-fallback: POSTMORTEM.md tool link gets one more "../".
        postmortem = (
            self.root / "docs" / "archive" / "2026-04" / "POSTMORTEM.md"
        ).read_text(encoding="utf-8")
        self.assertIn("../../../tools/real_tool.py", postmortem)

        # CASE-C: OBSOLETE.md left untouched.
        obsolete = (
            self.root / "docs" / "archive" / "2026-05" / "OBSOLETE.md"
        ).read_text(encoding="utf-8")
        self.assertIn("../reference/gone.jsonl", obsolete)

        # CASE-D: CLAUDE.md left untouched.
        claude = (self.root / "CLAUDE.md").read_text(encoding="utf-8")
        self.assertIn("docs/STALE_BY_DESIGN.md", claude)

    def test_idempotent_after_apply(self) -> None:
        """Running the fixer twice does not double-prefix paths."""
        self._build_synthetic_repo()
        self._write_report()
        audit_path = self.root / "audit.json"
        # First run.
        self._invoke("--audit-out", str(audit_path))
        # Rewrite the report to a no-broken-rows form (the rewritten
        # links no longer appear as broken).
        empty_report = textwrap.dedent(
            """\
            # Cross-Link Validation Report

            ## Summary

            - Broken: **0**
            """
        )
        (self.root / "docs" / "CROSS_LINK_REPORT.md").write_text(
            empty_report, encoding="utf-8"
        )
        # Second run.
        result = self._invoke("--audit-out", str(audit_path))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("nothing to do", result.stdout)
        # Confirm rewritten files were not mutated again.
        plan = (
            self.root / "docs" / "archive" / "2026-05" / "PLAN.md"
        ).read_text(encoding="utf-8")
        self.assertEqual(plan.count("../../WORKFLOW.md"), 1)
        self.assertNotIn("../../../../WORKFLOW.md", plan)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
