#!/usr/bin/env python3
"""Tests for tools/llm-pr-review-merge-hook.py — auto-grade-on-merge.

Hermetic: no live `gh`, no real ledger writes. The ledger path is redirected
to a tmp file in every test; subprocess.run for `gh` is mocked. Test inputs
are NEUTRAL (paraphrased) PR comment bodies — no real PR comment text reused
verbatim, to avoid comment-leakage in fixtures (foot-gun #2).
"""
from __future__ import annotations

import importlib.util
import json
import pathlib
import tempfile
import unittest
from unittest.mock import patch

ROOT = pathlib.Path(__file__).resolve().parents[2]
TOOL = ROOT / "tools" / "llm-pr-review-merge-hook.py"


def _load_module():
    """Import the hyphenated tool as a module."""
    spec = importlib.util.spec_from_file_location("llm_pr_review_merge_hook", TOOL)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ---------------------------------------------------------------------------
# Synthetic comment bodies (NEUTRAL — never copy real PR text)
# ---------------------------------------------------------------------------

LEGACY_AGREED_MERGE = """## Multi-LLM review (Codex substitute)

**Kimi K2.6 verdict:**
```
VERDICT: MERGE-OK
JUSTIFICATION: small touch-up, no logic change.
```

**Minimax M2.7 verdict:**
```
VERDICT: MERGE-OK
JUSTIFICATION: confined diff, ok.
```

**Consensus:** AGREED-MERGE
"""

NEW_AGREED_MERGE = """## Dual-LLM PR Review (Codex substitute)

**Consensus:** `AGREED-MERGE-OK`

### Kimi: `MERGE-OK`

ok looks fine.

### Minimax: `MERGE-OK`

agreed, scope is tight.

_Generated by `tools/llm-pr-review.py` for PR #999._
"""

NEW_AGREED_NEEDS_FIX = """## Dual-LLM PR Review

**Consensus:** `AGREED-NEEDS-FIX`

### Kimi: `NEEDS-FIX`

a callsite was missed in renaming.

### Minimax: `NEEDS-FIX`

same — two helpers still call the old name.
"""

LEGACY_DISAGREED = """## Multi-LLM review

**Kimi K2.6 verdict:**
```
VERDICT: NEEDS-FIX
JUSTIFICATION: helper still references the old constant.
```

**Minimax M2.7 verdict:**
```
VERDICT: MERGE-OK
JUSTIFICATION: looks self-consistent.
```

**Consensus:** DISAGREED
"""


# ---------------------------------------------------------------------------
# 1. parse_review_comment — both formats, both consensus shapes
# ---------------------------------------------------------------------------

class ParseReviewCommentTest(unittest.TestCase):
    def setUp(self) -> None:
        self.mod = _load_module()

    def test_legacy_agreed_merge_parses(self) -> None:
        p = self.mod.parse_review_comment(LEGACY_AGREED_MERGE)
        self.assertEqual(p["kimi"], "MERGE-OK")
        self.assertEqual(p["minimax"], "MERGE-OK")
        # Legacy "AGREED-MERGE" gets normalised to "AGREED-MERGE-OK".
        self.assertEqual(p["consensus"], "AGREED-MERGE-OK")

    def test_new_agreed_merge_parses(self) -> None:
        p = self.mod.parse_review_comment(NEW_AGREED_MERGE)
        self.assertEqual(p["kimi"], "MERGE-OK")
        self.assertEqual(p["minimax"], "MERGE-OK")
        self.assertEqual(p["consensus"], "AGREED-MERGE-OK")

    def test_new_agreed_needs_fix_parses(self) -> None:
        p = self.mod.parse_review_comment(NEW_AGREED_NEEDS_FIX)
        self.assertEqual(p["kimi"], "NEEDS-FIX")
        self.assertEqual(p["minimax"], "NEEDS-FIX")
        self.assertEqual(p["consensus"], "AGREED-NEEDS-FIX")

    def test_legacy_disagreed_parses(self) -> None:
        p = self.mod.parse_review_comment(LEGACY_DISAGREED)
        self.assertEqual(p["kimi"], "NEEDS-FIX")
        self.assertEqual(p["minimax"], "MERGE-OK")
        self.assertEqual(p["consensus"], "DISAGREED")

    def test_unknown_body_returns_nones(self) -> None:
        p = self.mod.parse_review_comment("just a normal comment, no markers")
        self.assertIsNone(p["kimi"])
        self.assertIsNone(p["minimax"])
        self.assertIsNone(p["consensus"])


# ---------------------------------------------------------------------------
# 2. grade_outcome — all four consensus paths
# ---------------------------------------------------------------------------

class GradeOutcomeTest(unittest.TestCase):
    def setUp(self) -> None:
        self.mod = _load_module()

    def test_agreed_merge_ok_merged_both_true(self) -> None:
        parsed = {"kimi": "MERGE-OK", "minimax": "MERGE-OK",
                  "consensus": "AGREED-MERGE-OK"}
        out = self.mod.grade_outcome(parsed, "MERGED")
        self.assertEqual(out, {"kimi": "TRUE", "minimax": "TRUE"})

    def test_agreed_needs_fix_merged_both_true(self) -> None:
        # Both flagged correctly + the fix shipped.
        parsed = {"kimi": "NEEDS-FIX", "minimax": "NEEDS-FIX",
                  "consensus": "AGREED-NEEDS-FIX"}
        out = self.mod.grade_outcome(parsed, "MERGED")
        self.assertEqual(out, {"kimi": "TRUE", "minimax": "TRUE"})

    def test_disagreed_merged_as_is_merge_ok_voter_true(self) -> None:
        parsed = {"kimi": "NEEDS-FIX", "minimax": "MERGE-OK",
                  "consensus": "DISAGREED"}
        out = self.mod.grade_outcome(parsed, "MERGED",
                                     fix_up_after_review=False)
        self.assertEqual(out, {"kimi": "FALSE", "minimax": "TRUE"})

    def test_disagreed_merged_after_fix_needs_fix_voter_true(self) -> None:
        parsed = {"kimi": "NEEDS-FIX", "minimax": "MERGE-OK",
                  "consensus": "DISAGREED"}
        out = self.mod.grade_outcome(parsed, "MERGED",
                                     fix_up_after_review=True)
        self.assertEqual(out, {"kimi": "TRUE", "minimax": "FALSE"})

    def test_closed_unmerged_both_indeterminate(self) -> None:
        parsed = {"kimi": "MERGE-OK", "minimax": "MERGE-OK",
                  "consensus": "AGREED-MERGE-OK"}
        out = self.mod.grade_outcome(parsed, "CLOSED")
        self.assertEqual(out, {"kimi": "INDETERMINATE",
                               "minimax": "INDETERMINATE"})

    def test_open_pr_both_indeterminate(self) -> None:
        parsed = {"kimi": "NEEDS-FIX", "minimax": "MERGE-OK",
                  "consensus": "DISAGREED"}
        out = self.mod.grade_outcome(parsed, "OPEN")
        self.assertEqual(out, {"kimi": "INDETERMINATE",
                               "minimax": "INDETERMINATE"})

    def test_llm_failure_consensus_indeterminate(self) -> None:
        parsed = {"kimi": None, "minimax": "MERGE-OK",
                  "consensus": "LLM-FAILURE"}
        out = self.mod.grade_outcome(parsed, "MERGED")
        self.assertEqual(out, {"kimi": "INDETERMINATE",
                               "minimax": "INDETERMINATE"})


# ---------------------------------------------------------------------------
# 3. find_review_comment — multi-comment threads
# ---------------------------------------------------------------------------

class FindReviewCommentTest(unittest.TestCase):
    def setUp(self) -> None:
        self.mod = _load_module()

    def test_picks_review_comment_from_thread(self) -> None:
        comments = [
            {"createdAt": "2026-04-25T10:00:00Z",
             "body": "looks great LGTM"},
            {"createdAt": "2026-04-25T10:05:00Z",
             "body": NEW_AGREED_MERGE},
            {"createdAt": "2026-04-25T10:10:00Z",
             "body": "bumping for visibility"},
        ]
        c = self.mod.find_review_comment(comments)
        self.assertIsNotNone(c)
        self.assertIn("Dual-LLM", c["body"])

    def test_picks_earliest_review_when_multiple(self) -> None:
        # If the dispatcher ran twice, prefer the earliest.
        comments = [
            {"createdAt": "2026-04-25T11:00:00Z",
             "body": NEW_AGREED_NEEDS_FIX},
            {"createdAt": "2026-04-25T10:00:00Z",
             "body": NEW_AGREED_MERGE},
        ]
        c = self.mod.find_review_comment(comments)
        self.assertIn("AGREED-MERGE-OK", c["body"])

    def test_no_review_comment_returns_none(self) -> None:
        comments = [{"body": "nice work"}, {"body": "+1"}]
        self.assertIsNone(self.mod.find_review_comment(comments))


# ---------------------------------------------------------------------------
# 4. process_pr — ledger write side effect (mocked gh)
# ---------------------------------------------------------------------------

class ProcessPrLedgerWriteTest(unittest.TestCase):
    def setUp(self) -> None:
        self.mod = _load_module()
        self.tmp = tempfile.NamedTemporaryFile(
            mode="w", suffix=".jsonl", delete=False
        )
        self.tmp.close()
        self.ledger = pathlib.Path(self.tmp.name)
        # Start with an empty file.
        self.ledger.write_text("", encoding="utf-8")

    def tearDown(self) -> None:
        try:
            self.ledger.unlink()
        except OSError:
            pass

    def _read_ledger(self) -> list[dict]:
        rows = []
        for line in self.ledger.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                rows.append(json.loads(line))
        return rows

    def test_agreed_merge_writes_two_true_rows(self) -> None:
        pr_data = {
            "number": 9001,
            "state": "MERGED",
            "mergedAt": "2026-04-25T12:00:00Z",
            "comments": [{
                "createdAt": "2026-04-25T11:00:00Z",
                "body": NEW_AGREED_MERGE,
            }],
            "commits": [{"committedDate": "2026-04-25T10:00:00Z"}],
        }
        with patch.object(self.mod, "fetch_pr", return_value=pr_data):
            rec = self.mod.process_pr(
                9001,
                ledger_path=self.ledger,
                dry_run=False,
                operator="test",
                session_id="test-session",
            )
        rows = self._read_ledger()
        self.assertEqual(len(rows), 2)
        providers = sorted(r["provider"] for r in rows)
        self.assertEqual(providers, ["kimi", "minimax"])
        for r in rows:
            self.assertEqual(r["task_type"], "pr-review")
            self.assertEqual(r["task_ref"], "PR #9001")
            self.assertEqual(r["verdict"], "TRUE")
            self.assertEqual(r["operator"], "test")
        self.assertEqual(rec["outcomes"],
                         {"kimi": "TRUE", "minimax": "TRUE"})

    def test_disagreed_merged_unchanged_writes_one_true_one_false(self) -> None:
        # No commits AFTER the review timestamp -> merged-as-is.
        pr_data = {
            "number": 9002,
            "state": "MERGED",
            "comments": [{
                "createdAt": "2026-04-25T11:00:00Z",
                "body": LEGACY_DISAGREED,
            }],
            "commits": [{"committedDate": "2026-04-25T10:00:00Z"}],
        }
        with patch.object(self.mod, "fetch_pr", return_value=pr_data):
            self.mod.process_pr(
                9002, ledger_path=self.ledger, dry_run=False,
                operator="test", session_id="test-session",
            )
        rows = self._read_ledger()
        verdicts = {r["provider"]: r["verdict"] for r in rows}
        # Kimi voted NEEDS-FIX -> merged unchanged means Kimi was wrong.
        self.assertEqual(verdicts["kimi"], "FALSE")
        # Minimax voted MERGE-OK -> aligns with merge state.
        self.assertEqual(verdicts["minimax"], "TRUE")

    def test_idempotent_skips_existing(self) -> None:
        # Pre-populate the ledger with a row for kimi PR #9003.
        self.mod._load_calibration_module()  # cache module
        cal = self.mod._load_calibration_module()
        cal.append_entry({
            "ts": "2026-04-25T10:00:00Z",
            "provider": "kimi",
            "task_type": "pr-review",
            "task_ref": "PR #9003",
            "verdict": "TRUE",
            "evidence": "preexisting",
            "operator": "manual",
            "session_id": "prior",
        }, path=self.ledger)
        pr_data = {
            "number": 9003,
            "state": "MERGED",
            "comments": [{
                "createdAt": "2026-04-25T11:00:00Z",
                "body": NEW_AGREED_MERGE,
            }],
            "commits": [],
        }
        with patch.object(self.mod, "fetch_pr", return_value=pr_data):
            rec = self.mod.process_pr(
                9003, ledger_path=self.ledger, dry_run=False,
                operator="test", session_id="test-session",
            )
        rows = self._read_ledger()
        # Still 2 rows total: the preexisting kimi + the new minimax.
        self.assertEqual(len(rows), 2)
        kimi_rows = [r for r in rows if r["provider"] == "kimi"]
        self.assertEqual(len(kimi_rows), 1)
        self.assertEqual(kimi_rows[0]["operator"], "manual")  # untouched
        # The skipped reason was reported.
        self.assertIn("kimi-already-logged", rec["skipped"])

    def test_dry_run_does_not_write(self) -> None:
        pr_data = {
            "number": 9004,
            "state": "MERGED",
            "comments": [{
                "createdAt": "2026-04-25T11:00:00Z",
                "body": NEW_AGREED_MERGE,
            }],
            "commits": [],
        }
        with patch.object(self.mod, "fetch_pr", return_value=pr_data):
            rec = self.mod.process_pr(
                9004, ledger_path=self.ledger, dry_run=True,
                operator="test", session_id="test-session",
            )
        # Ledger is empty.
        self.assertEqual(self._read_ledger(), [])
        # But the record reports the would-be entries.
        self.assertIsNotNone(rec["logged"]["kimi"])
        self.assertIsNotNone(rec["logged"]["minimax"])


# ---------------------------------------------------------------------------
# 5. detect_fix_up — heuristic behaviour
# ---------------------------------------------------------------------------

class DetectFixUpTest(unittest.TestCase):
    def setUp(self) -> None:
        self.mod = _load_module()

    def test_commit_after_review_returns_true(self) -> None:
        pr = {
            "commits": [
                {"committedDate": "2026-04-25T09:00:00Z"},
                {"committedDate": "2026-04-25T12:30:00Z"},
            ],
        }
        review = {"createdAt": "2026-04-25T10:00:00Z"}
        self.assertTrue(self.mod.detect_fix_up(pr, review))

    def test_no_commits_after_review_returns_false(self) -> None:
        pr = {
            "commits": [{"committedDate": "2026-04-25T09:00:00Z"}],
        }
        review = {"createdAt": "2026-04-25T10:00:00Z"}
        self.assertFalse(self.mod.detect_fix_up(pr, review))

    def test_missing_review_timestamp_returns_false(self) -> None:
        pr = {"commits": [{"committedDate": "2026-04-25T12:00:00Z"}]}
        review = {}
        self.assertFalse(self.mod.detect_fix_up(pr, review))


# ---------------------------------------------------------------------------
# 6. CLI plumbing
# ---------------------------------------------------------------------------

class CliTest(unittest.TestCase):
    def setUp(self) -> None:
        self.mod = _load_module()

    def test_subcommand_required(self) -> None:
        p = self.mod.build_arg_parser()
        with self.assertRaises(SystemExit):
            p.parse_args([])

    def test_process_requires_pr_number(self) -> None:
        p = self.mod.build_arg_parser()
        with self.assertRaises(SystemExit):
            p.parse_args(["process"])

    def test_process_recent_accepts_since(self) -> None:
        p = self.mod.build_arg_parser()
        ns = p.parse_args(["process-recent", "--since", "2026-04-01"])
        self.assertEqual(ns.since, "2026-04-01")
        self.assertEqual(ns.cmd, "process-recent")


if __name__ == "__main__":
    unittest.main()
