#!/usr/bin/env python3
# AUTO-GENERATED by tools/advisory-seed-to-dsl.py - DO NOT EDIT BY HAND.
# CLASS-LEVEL detector (mechanism: no_per_peer_throttle); anti-overfit: token-class anchors.
"""no_per_peer_throttle - An inbound request/sync/gossip path consumes a SHARED concurrency slot (Semaphore/acquire) or triggers a GLOBAL reset (restart_sync) with no per-peer keying - a single peer exhausts the resource or stalls discovery for everyone.

Class tag: resource-exhaustion-dos   Language: rust   Severity: MEDIUM
Source advisories: https://github.com/ZcashFoundation/zebra/security/advisories/GHSA-4fc2-h7jh-287c; https://github.com/ZcashFoundation/zebra/security/advisories/GHSA-h9hm-m2xj-4rq9
Mechanism is matched, NOT any single instance (see advisory-seed-to-dsl.py).
"""
from __future__ import annotations
import re
from pathlib import Path

DETECTOR_ID = 'no_per_peer_throttle'
CLASS_TAG = 'resource-exhaustion-dos'
LANGUAGE = 'rust'
SEVERITY = 'MEDIUM'

_SKIP_DIRS = {"target", ".git", "node_modules", "vendor", "_archive", "tests", "test"}
_POSITIVE = re.compile('(?i)(Semaphore::new\\s*\\(|\\.acquire\\s*\\(|\\bin[_-]?flight\\b|restart_sync\\s*\\(|reset_sync\\s*\\()')
_NEGATIVE = re.compile('(?i)(per[_-]?peer|peer[_-]?id|HashMap<\\s*(?:PeerId|SocketAddr)|rate[_-]?limit|\\bquota\\b|\\bbackoff\\b|max[_-]?in[_-]?flight)') if '(?i)(per[_-]?peer|peer[_-]?id|HashMap<\\s*(?:PeerId|SocketAddr)|rate[_-]?limit|\\bquota\\b|\\bbackoff\\b|max[_-]?in[_-]?flight)' else None
_FN_MARKER = re.compile(None) if None else None
_FILE_GLOB = None
_ORDERING = False
_EXT = '.rs'

_FN_HEADER_RE = re.compile(
    r"^[ \t]*(?:pub(?:\s*\([^)]*\))?\s+)?(?:async\s+|unsafe\s+|const\s+)*"
    r"(?:fn|func)\s+(?P<name>[A-Za-z_]\w*)")


def _iter_files(root: Path):
    if _FILE_GLOB:
        for p in root.rglob(_FILE_GLOB):
            if not any(part in _SKIP_DIRS for part in p.parts):
                yield p
        return
    for p in root.rglob("*" + _EXT):
        if any(part in _SKIP_DIRS for part in p.parts):
            continue
        yield p


def _functions(src: str):
    """Yield (name, start_line, body) for each fn/func in src (brace-balanced)."""
    lines = src.splitlines()
    i = 0
    while i < len(lines):
        m = _FN_HEADER_RE.match(lines[i])
        if not m:
            i += 1
            continue
        name = m.group("name")
        depth = 0
        started = False
        body = []
        j = i
        while j < len(lines):
            ln = lines[j]
            depth += ln.count("{") - ln.count("}")
            body.append(ln)
            if "{" in ln:
                started = True
            if started and depth <= 0:
                break
            j += 1
        yield name, i + 1, "\n".join(body)
        i = j + 1 if j > i else i + 1


def scan(root):
    """rust/go runner interface: list[(filepath, line, message)]."""
    root = Path(root)
    hits = []
    for f in _iter_files(root):
        try:
            src = f.read_text(errors="ignore")
        except Exception:
            continue
        if _FILE_GLOB:
            for mm in _POSITIVE.finditer(src):
                ln = src[:mm.start()].count("\n") + 1
                hits.append((str(f), ln, DETECTOR_ID + ": " + mm.group(0)[:80]))
            continue
        for name, start, body in _functions(src):
            if _FN_MARKER and not _FN_MARKER.search(name):
                continue
            pm = _POSITIVE.search(body)
            if not pm:
                continue
            if _NEGATIVE and _NEGATIVE.search(body):
                continue  # canonical guard present -> suppress
            if _ORDERING:
                g = re.search(r"(?:check_|validate_|ensure_|reject|duplicate)", body)
                if not g or g.start() < pm.start():
                    continue
            ln = start + body[:pm.start()].count("\n")
            hits.append((str(f), ln, DETECTOR_ID + ": " + name + " :: " + pm.group(0)[:60]))
    return hits


if __name__ == "__main__":
    import sys
    for fp, ln, msg in scan(sys.argv[1] if len(sys.argv) > 1 else "."):
        print(fp + ":" + str(ln) + ":" + msg)
