"""
changes-to-pyth-entropy-provider-used-by-scaledentropyprovid-x — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2025-11-megapot
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/changes-to-pyth-entropy-provider-used-by-scaledentropyprovid-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class ChangesToPythEntropyProviderUsedByScaledentropyprovidX(AbstractDetector):
    ARGUMENT = "changes-to-pyth-entropy-provider-used-by-scaledentropyprovid-x"
    HELP = "hgrano Finding description and impact When the Jackpot requests entropy from the ScaledEntropyProvider during Jackpot::runJackpot , the ScaledEntropyProvider tracks each request by"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Changes to Pyth entropy provider used by ScaledEntropyProvider allow attacker to fix jackpot result"
    WIKI_DESCRIPTION = "hgrano Finding description and impact When the Jackpot requests entropy from the ScaledEntropyProvider during Jackpot::runJackpot , the ScaledEntropyProvider tracks each request by the sequence number returned from the Pyth Network Entropy contract: function requestAndCallbackScaledRandomness ( uint"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: hgrano Finding description and impact When the Jackpot requests entropy from the ScaledEntropyProvider during Jackpot::runJackpot , the ScaledEntropyProvider tracks each request by the sequence number"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(_bridgeFunds|claimTickets|buyTickets|claimWinnings|runJackpot|getFee|requestV2).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — changes-to-pyth-entropy-provider-used-by-scaledentropyprovid-x: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from code4arena audit 2025-11-megapot.",
                ]
                results.append(self.generate_result(info))
        return results
