"""
clob-config-invariant-can-be-broken-by-updating-clobmanager--x — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2025-07-gte-spot-clob-and-router
Severity: LOW
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/clob-config-invariant-can-be-broken-by-updating-clobmanager--x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class ClobConfigInvariantCanBeBrokenByUpdatingClobmanagerX(AbstractDetector):
    ARGUMENT = "clob-config-invariant-can-be-broken-by-updating-clobmanager--x"
    HELP = "[L-05] CLOB config invariant can be broken by updating CLOBManager validates the following invariant before deploying a CLOB: File: contracts/clob/CLOBManager.sol 289 : function _a"
    IMPACT = DetectorClassification.LOW
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "CLOB config invariant can be broken by updating CLOBManager validates the following invariant before deploying a CLOB: File: contracts/clob/CLOBManager.sol"
    WIKI_DESCRIPTION = "[L-05] CLOB config invariant can be broken by updating CLOBManager validates the following invariant before deploying a CLOB: File: contracts/clob/CLOBManager.sol 289 : function _assertValidSettings ( SettingsParams calldata settings uint256 baseSize ) internal pure { 290 :@> if ( settings . tickSiz"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: [L-05] CLOB config invariant can be broken by updating CLOBManager validates the following invariant before deploying a CLOB: File: contracts/clob/CLOBManager.sol 289 : function _assertValidSettings ("
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(baseSize|tickSize|fullMulDiv).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — clob-config-invariant-can-be-broken-by-updating-clobmanager--x: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from code4arena audit 2025-07-gte-spot-clob-and-router.",
                ]
                results.append(self.generate_result(info))
        return results
