"""
flawed-zero-cost-trade-prevention — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2025-07-gte-spot-clob-and-router
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/flawed-zero-cost-trade-prevention.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class FlawedZeroCostTradePrevention(AbstractDetector):
    ARGUMENT = "flawed-zero-cost-trade-prevention"
    HELP = "VulnViper , also found by 0xAura 0xDeoGratias 0xDetermination 0xhanu58 0xPhantom 0xterrah Almanax anonymousjoe axelot BenRai boredpukar ChainSentry DDEENNY dhank EVDoc Gosho guri j"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Flawed Zero-Cost Trade Prevention"
    WIKI_DESCRIPTION = "VulnViper , also found by 0xAura 0xDeoGratias 0xDetermination 0xhanu58 0xPhantom 0xterrah Almanax anonymousjoe axelot BenRai boredpukar ChainSentry DDEENNY dhank EVDoc Gosho guri jerry0422 lirezArAzAvi lodelux Neeloy Pexy random1106 Riceee sharonphiliplima solhhj Tofu v2110 , and Zibounne clob/CLOB."
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: VulnViper , also found by 0xAura 0xDeoGratias 0xDetermination 0xhanu58 0xPhantom 0xterrah Almanax anonymousjoe axelot BenRai boredpukar ChainSentry DDEENNY dhank EVDoc Gosho guri jerry0422 lirezArAzAv"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(addOrderToBook|lirezArAzAvi|baseTokenAmountReceived|quoteTokenAmountSent).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — flawed-zero-cost-trade-prevention: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from code4arena audit 2025-07-gte-spot-clob-and-router.",
                ]
                results.append(self.generate_result(info))
        return results
