"""
fulfillredeem-may-corrupt-share-price-and-allow-over-redempt-x — generated from skeleton `name_match_missing_call`
Ported from: code4arena audit 2025-11-sukukfi
Severity: MEDIUM
Pattern: function whose name matches the target regex reads a state var
matching the read regex, but does NOT contain an internal/high-level call
matching the required-call regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/fulfillredeem-may-corrupt-share-price-and-allow-over-redempt-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class FulfillredeemMayCorruptSharePriceAndAllowOverRedemptX(AbstractDetector):
    ARGUMENT = "fulfillredeem-may-corrupt-share-price-and-allow-over-redempt-x"
    HELP = "Audittens , also found by 0xG0P1 0xSecurious 0xSeer blockace dee24 Dest1ny_rs EPSec s4bot3ur , and slvDev src/ShareTokenUpgradeable.sol #L710 src/ShareTokenUpgradeable.sol #L378-L3"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "fulfillRedeem may corrupt share price and allow over-redemption of assets"
    WIKI_DESCRIPTION = "Audittens , also found by 0xG0P1 0xSecurious 0xSeer blockace dee24 Dest1ny_rs EPSec s4bot3ur , and slvDev src/ShareTokenUpgradeable.sol #L710 src/ShareTokenUpgradeable.sol #L378-L389 src/ERC7575VaultUpgradeable.sol #L1533-L1535 src/ERC7575VaultUpgradeable.sol #L1176-L1179 src/ERC7575VaultUpgradeable"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: Audittens , also found by 0xG0P1 0xSecurious 0xSeer blockace dee24 Dest1ny_rs EPSec s4bot3ur , and slvDev src/ShareTokenUpgradeable.sol #L710 src/ShareTokenUpgradeable.sol #L378-L389 src/ERC7575VaultU"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(unregisterVault|consolidateTransfers|slvDev|sharePrice|normalizedAssets).*", re.IGNORECASE)
    _READ_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _REQUIRED_CALL_REGEX = re.compile(r".*(accrue|update|sync|validate|check|refresh).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                # Check that the function reads at least one state var matching the regex
                reads_target = False
                for sv in f.state_variables_read:
                    if self._READ_VAR_REGEX.search(sv.name):
                        reads_target = True
                        break
                if not reads_target:
                    continue

                # Check for the required internal/high-level call (presence = safe)
                has_required_call = False
                for ic in f.internal_calls:
                    callee = ic.function if hasattr(ic, "function") else ic
                    callee_name = getattr(callee, "name", "") or ""
                    if self._REQUIRED_CALL_REGEX.search(callee_name):
                        has_required_call = True
                        break
                if not has_required_call:
                    for hc_tuple in f.high_level_calls:
                        hc = hc_tuple[1] if isinstance(hc_tuple, tuple) else hc_tuple
                        callee_name = (
                            getattr(hc.function, "name", "") if hasattr(hc, "function") else ""
                        ) or ""
                        if self._REQUIRED_CALL_REGEX.search(callee_name):
                            has_required_call = True
                            break

                if has_required_call:
                    continue

                info = [
                    f,
                    f" — fulfillredeem-may-corrupt-share-price-and-allow-over-redempt-x: reads `{{{{}}}}`-matching state but does not call a `.*(accrue|update|sync|validate|check|refresh).*` guard. ",
                    f"Ported from code4arena audit 2025-11-sukukfi. See reference/bug_patterns_observed.md.",
                ]
                res = self.generate_result(info)
                results.append(res)
        return results
