"""
invalid-basereserve-stalls-buy-on-bonding-curve — generated from skeleton `name_match_missing_call`
Ported from: zellic audit GTE CLOB and Launchpad- Zellic Audit Report
Severity: HIGH
Pattern: function whose name matches the target regex reads a state var
matching the read regex, but does NOT contain an internal/high-level call
matching the required-call regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/invalid-basereserve-stalls-buy-on-bonding-curve.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class InvalidBasereserveStallsBuyOnBondingCurve(AbstractDetector):
    ARGUMENT = "invalid-basereserve-stalls-buy-on-bonding-curve"
    HELP = "The SimpleBondingCurve contract provides exchange rates between quote token and base token prior to graduation events. Graduation is when the BONDING_SUPPLY has been reached and re"
    IMPACT = DetectorClassification.HIGH
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Invalid baseReserve stalls buy on bonding curve"
    WIKI_DESCRIPTION = "The SimpleBondingCurve contract provides exchange rates between quote token and base token prior to graduation events. Graduation is when the BONDING_SUPPLY has been reached and remaining balances in the Launchpad are sent to a UniswapV2 token pool. The _getQuoteAmount() function (used in both buy()"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: The SimpleBondingCurve contract provides exchange rates between quote token and base token prior to graduation events. Graduation is when the BONDING_SUPPLY has been reached and remaining balances in"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(creditAccount|_getQuoteAmount|baseAmount|quoteReserve|baseReserve).*", re.IGNORECASE)
    _READ_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _REQUIRED_CALL_REGEX = re.compile(r".*(accrue|update|sync|validate|check|refresh).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                # Check that the function reads at least one state var matching the regex
                reads_target = False
                for sv in f.state_variables_read:
                    if self._READ_VAR_REGEX.search(sv.name):
                        reads_target = True
                        break
                if not reads_target:
                    continue

                # Check for the required internal/high-level call (presence = safe)
                has_required_call = False
                for ic in f.internal_calls:
                    callee = ic.function if hasattr(ic, "function") else ic
                    callee_name = getattr(callee, "name", "") or ""
                    if self._REQUIRED_CALL_REGEX.search(callee_name):
                        has_required_call = True
                        break
                if not has_required_call:
                    for hc_tuple in f.high_level_calls:
                        hc = hc_tuple[1] if isinstance(hc_tuple, tuple) else hc_tuple
                        callee_name = (
                            getattr(hc.function, "name", "") if hasattr(hc, "function") else ""
                        ) or ""
                        if self._REQUIRED_CALL_REGEX.search(callee_name):
                            has_required_call = True
                            break

                if has_required_call:
                    continue

                info = [
                    f,
                    f" — invalid-basereserve-stalls-buy-on-bonding-curve: reads `{{{{}}}}`-matching state but does not call a `.*(accrue|update|sync|validate|check|refresh).*` guard. ",
                    f"Ported from zellic audit GTE CLOB and Launchpad- Zellic Audit Report. See reference/bug_patterns_observed.md.",
                ]
                res = self.generate_result(info)
                results.append(res)
        return results
