"""
lack-of-validation-of-outputtoken-address — generated from skeleton `name_match_missing_require`
Ported from: zellic audit Odos Cross-Chain Contracts - Zellic Audit Report
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/lack-of-validation-of-outputtoken-address.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class LackOfValidationOfOutputtokenAddress(AbstractDetector):
    ARGUMENT = "lack-of-validation-of-outputtoken-address"
    HELP = "In the executeOdosHook function of the AcrossHook contract, there is a lack of validation to ensure that the outputToken specified by the user in hookData is not the zero address."
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Lack of validation of outputToken address"
    WIKI_DESCRIPTION = "In the executeOdosHook function of the AcrossHook contract, there is a lack of validation to ensure that the outputToken specified by the user in hookData is not the zero address. Since the zero address is used in OdosRouterV3 to represent native tokens, users may assume that it is a valid and suppo"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: In the executeOdosHook function of the AcrossHook contract, there is a lack of validation to ensure that the outputToken specified by the user in hookData is not the zero address. Since the zero addre"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(handleV3AcrossMessage|executeOdosHook|outputToken|hookData).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — lack-of-validation-of-outputtoken-address: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from zellic audit Odos Cross-Chain Contracts - Zellic Audit Report.",
                ]
                results.append(self.generate_result(info))
        return results
