"""
protocol-should-update-interest-rate-after-changing-rate-mod-x — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2024-07-benddao
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/protocol-should-update-interest-rate-after-changing-rate-mod-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class ProtocolShouldUpdateInterestRateAfterChangingRateModX(AbstractDetector):
    ARGUMENT = "protocol-should-update-interest-rate-after-changing-rate-mod-x"
    HELP = "SpicyMeatball Impact After updating the interest model, the protocol does not update the interest rate, resulting in interest being calculated at the old model rates for some time."
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Protocol should update interest rate after changing rate model in the configurator module"
    WIKI_DESCRIPTION = "SpicyMeatball Impact After updating the interest model, the protocol does not update the interest rate, resulting in interest being calculated at the old model rates for some time. Proof of Concept The pool admin can change rate model in the Configurator.sol module: function executeSetAssetLendingRa"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: SpicyMeatball Impact After updating the interest model, the protocol does not update the interest rate, resulting in interest being calculated at the old model rates for some time. Proof of Concept Th"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(deposit|executeCrossLiquidateERC721|executeIsolateLiquidate|stake|executeSetAssetLendingRate|poolId|groupId).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — protocol-should-update-interest-rate-after-changing-rate-mod-x: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from code4arena audit 2024-07-benddao.",
                ]
                results.append(self.generate_result(info))
        return results
