"""
rebalancing-would-revert-on-morpho-in-some-cases-proof-of-co-x — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2024-12-lambowin
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/rebalancing-would-revert-on-morpho-in-some-cases-proof-of-co-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class RebalancingWouldRevertOnMorphoInSomeCasesProofOfCoX(AbstractDetector):
    ARGUMENT = "rebalancing-would-revert-on-morpho-in-some-cases-proof-of-co-x"
    HELP = "[QA-04] Rebalancing would revert on Morpho in some cases Proof of Concept Take a look at function rebalance ( uint256 directionMask uint256 amountIn uint256 amountOut ) external no"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Rebalancing would revert on Morpho in some cases Proof of Concept Take a look at"
    WIKI_DESCRIPTION = "[QA-04] Rebalancing would revert on Morpho in some cases Proof of Concept Take a look at function rebalance ( uint256 directionMask uint256 amountIn uint256 amountOut ) external nonReentrant { uint256 balanceBefore = IERC20 ( weth ). balanceOf ( address ( this )); bytes memory data = abi . encode ("
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: [QA-04] Rebalancing would revert on Morpho in some cases Proof of Concept Take a look at function rebalance ( uint256 directionMask uint256 amountIn uint256 amountOut ) external nonReentrant { uint256"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(rebalance|_getTokenInOut|directionMask|amountIn|amountOut).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — rebalancing-would-revert-on-morpho-in-some-cases-proof-of-co-x: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from code4arena audit 2024-12-lambowin.",
                ]
                results.append(self.generate_result(info))
        return results
