"""
refunds-to-eoas-on-unsuccessful-cross-chain-messages-fail-le-x — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2025-02-recall
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/refunds-to-eoas-on-unsuccessful-cross-chain-messages-fail-le-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class RefundsToEoasOnUnsuccessfulCrossChainMessagesFailLeX(AbstractDetector):
    ARGUMENT = "refunds-to-eoas-on-unsuccessful-cross-chain-messages-fail-le-x"
    HELP = "muellerberndt Finding description and impact In IPC, EOAs send funds between subnets using the fund and fundWithToken functions which produce IpcMsgKind.Transfer messages. When a c"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Refunds to EOAs on unsuccessful cross-chain messages fail, leaving users’ funds stuck in the gateway"
    WIKI_DESCRIPTION = "muellerberndt Finding description and impact In IPC, EOAs send funds between subnets using the fund and fundWithToken functions which produce IpcMsgKind.Transfer messages. When a cross-net message fails, an error receipt is propagated back to the originating subnet, and the message value is refunded"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: muellerberndt Finding description and impact In IPC, EOAs send funds between subnets using the fund and fundWithToken functions which produce IpcMsgKind.Transfer messages. When a cross-net message fai"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(leave|submitCheckpoint|Call|Receipt).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — refunds-to-eoas-on-unsuccessful-cross-chain-messages-fail-le-x: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from code4arena audit 2025-02-recall.",
                ]
                results.append(self.generate_result(info))
        return results
