"""
static-signatures-bound-to-caller-revert-under-erc-4337-caus-x — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2025-10-sequence
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/static-signatures-bound-to-caller-revert-under-erc-4337-caus-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class StaticSignaturesBoundToCallerRevertUnderErc4337CausX(AbstractDetector):
    ARGUMENT = "static-signatures-bound-to-caller-revert-under-erc-4337-caus-x"
    HELP = "Agontuk , also found by 0xnija and zcai Finding description Sequence wallets support ERC‑4337 by validating signatures inside validateUserOp() in ERC4337v07 . The function enforces"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "Static signatures bound to caller revert under ERC-4337, causing DoS"
    WIKI_DESCRIPTION = "Agontuk , also found by 0xnija and zcai Finding description Sequence wallets support ERC‑4337 by validating signatures inside validateUserOp() in ERC4337v07 . The function enforces that msg.sender is the entrypoint and then performs signature verification via an external self‑call: this.isValidSigna"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: Agontuk , also found by 0xnija and zcai Finding description Sequence wallets support ERC‑4337 by validating signatures inside validateUserOp() in ERC4337v07 . The function enforces that msg.sender is"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(recoverChained|readUnitX|validateUserOp|isValidSignature|userOpHash).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — static-signatures-bound-to-caller-revert-under-erc-4337-caus-x: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from code4arena audit 2025-10-sequence.",
                ]
                results.append(self.generate_result(info))
        return results
