"""
state-price-mismatch-in-liquidation — generated from skeleton `state_write_without_paired_write`
Ported from: code4arena audit 2025-12-panoptic-next-core
Severity: MEDIUM
Pattern: a function whose name matches the target regex writes a state
variable matching the primary regex but does NOT write a second state
variable matching the paired regex in the same function body.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class StatePriceMismatchInLiquidation(AbstractDetector):
    ARGUMENT = "state-price-mismatch-in-liquidation"
    HELP = "devdragon , also found by merlinboii In PanopticPool._liquidate , the protocol evaluates the liquidatee’s collateral and debt to determine the liquidation bonus and potential proto"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "State-price mismatch in liquidation"
    WIKI_DESCRIPTION = "devdragon , also found by merlinboii In PanopticPool._liquidate , the protocol evaluates the liquidatee’s collateral and debt to determine the liquidation bonus and potential protocol loss. However, there is a fundamental accounting mismatch in how these values are calculated: 1. Stale asset valuati"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: devdragon , also found by merlinboii In PanopticPool._liquidate , the protocol evaluates the liquidatee’s collateral and debt to determine the liquidation bonus and potential protocol loss. However, t"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(_getRequiredCollateralAtTickSinglePosition|tokenData0|tokenData1|riskEngine).*", re.IGNORECASE)
    _PRIMARY_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _PAIRED_VAR_REGEX = re.compile(r".*(flag|isLong|cleared|reset|status).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_primary = False
                writes_paired = False
                for sv in f.state_variables_written:
                    if self._PRIMARY_VAR_REGEX.search(sv.name):
                        writes_primary = True
                    if self._PAIRED_VAR_REGEX.search(sv.name):
                        writes_paired = True

                if writes_primary and not writes_paired:
                    info = [
                        f,
                        f" — state-price-mismatch-in-liquidation: writes `.*(balance|amount|total|supply|reserve).*`-matching var but not `.*(flag|isLong|cleared|reset|status).*`-matching paired state. ",
                        f"Ported from code4arena audit 2025-12-panoptic-next-core.",
                    ]
                    results.append(self.generate_result(info))
        return results
