"""
swapaction-getswaptoken-will-return-wrong-swap-token-for-bal-x — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2024-07-loopfi
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/swapaction-getswaptoken-will-return-wrong-swap-token-for-bal-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class SwapactionGetswaptokenWillReturnWrongSwapTokenForBalX(AbstractDetector):
    ARGUMENT = "swapaction-getswaptoken-will-return-wrong-swap-token-for-bal-x"
    HELP = "0xAlix2 As known, when doing a Balancer EXACT_OUT batch swap, assets should be passed in reverse order, this is thoroughly documented here . Swapping in USDC for an exact amount ou"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "SwapAction::getSwapToken will return wrong swap token for balancer EXACT_OUT"
    WIKI_DESCRIPTION = "0xAlix2 As known, when doing a Balancer EXACT_OUT batch swap, assets should be passed in reverse order, this is thoroughly documented here . Swapping in USDC for an exact amount out of BAL swapType = `EXACT_OUT` and `assets` = [BAL, WETH, DAI, USDC]: However, in SwapAction::getSwapToken , for Balanc"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: 0xAlix2 As known, when doing a Balancer EXACT_OUT batch swap, assets should be passed in reverse order, this is thoroughly documented here . Swapping in USDC for an exact amount out of BAL swapType ="
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(EXACT_OUT|assets|getSwapToken).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(assets|getSwapToken|token).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(assets|getSwapToken|token).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — swapaction-getswaptoken-will-return-wrong-swap-token-for-bal-x: writes `.*(assets|getSwapToken|token).*`-matching state without a `require` on `.*(assets|getSwapToken|token).*`. ",
                    f"Ported from code4arena audit 2024-07-loopfi.",
                ]
                results.append(self.generate_result(info))
        return results
