"""
the-check-and-update-rate-limit-function-reverts-when-rate-l-x — generated from skeleton `name_match_missing_require`
Ported from: zellic audit LayerZero Starknet Endpoint V2 - Zellic Audit Report
Severity: LOW
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/the-check-and-update-rate-limit-function-reverts-when-rate-l-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class TheCheckAndUpdateRateLimitFunctionRevertsWhenRateLX(AbstractDetector):
    ARGUMENT = "the-check-and-update-rate-limit-function-reverts-when-rate-l-x"
    HELP = "The comment of the _check_and_update_rate_limit function explains that the function would return true if the rate limit is exceeded and false otherwise. However, it does not return"
    IMPACT = DetectorClassification.LOW
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "The _check_and_update_rate_limit function reverts when rate limit is ex-"
    WIKI_DESCRIPTION = "The comment of the _check_and_update_rate_limit function explains that the function would return true if the rate limit is exceeded and false otherwise. However, it does not return any result, but reverts when the rate limit is exceeded: /// Checks and updates the rate limit for the given endpoint I"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: The comment of the _check_and_update_rate_limit function explains that the function would return true if the rate limit is exceeded and false otherwise. However, it does not return any result, but rev"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(eid|amount|direction).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(amount|direction|eid).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(amount|direction|eid).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — the-check-and-update-rate-limit-function-reverts-when-rate-l-x: writes `.*(amount|direction|eid).*`-matching state without a `require` on `.*(amount|direction|eid).*`. ",
                    f"Ported from zellic audit LayerZero Starknet Endpoint V2 - Zellic Audit Report.",
                ]
                results.append(self.generate_result(info))
        return results
