"""
there-is-a-calculation-error-in-auravault-redeem — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2024-07-loopfi
Severity: HIGH
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/there-is-a-calculation-error-in-auravault-redeem.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class ThereIsACalculationErrorInAuravaultRedeem(AbstractDetector):
    ARGUMENT = "there-is-a-calculation-error-in-auravault-redeem"
    HELP = "lian886 , also found by novamanbg The amount of funds that users can withdraw decreases, leading to a loss of funds for users. Proof of Concept function redeem ( uint256 shares add"
    IMPACT = DetectorClassification.HIGH
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "There is a calculation error in AuraVault::redeem()"
    WIKI_DESCRIPTION = "lian886 , also found by novamanbg The amount of funds that users can withdraw decreases, leading to a loss of funds for users. Proof of Concept function redeem ( uint256 shares address receiver address owner ) public virtual override ( IERC4626 ERC4626 ) returns ( uint256 ) { require ( shares <= max"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: lian886 , also found by novamanbg The amount of funds that users can withdraw decreases, leading to a loss of funds for users. Proof of Concept function redeem ( uint256 shares address receiver addres"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(redeem|_onDecreaseLever|deposit|claim|maxRedeem|rewardPool|previewRedeem).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(balance|amount|total|supply|reserve).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — there-is-a-calculation-error-in-auravault-redeem: writes `.*(balance|amount|total|supply|reserve).*`-matching state without a `require` on `.*(balance|amount|total|supply|reserve).*`. ",
                    f"Ported from code4arena audit 2024-07-loopfi.",
                ]
                results.append(self.generate_result(info))
        return results
