"""
when-a-user-single-side-deposit-into-a-pool-slippage-protect-x — generated from skeleton `name_match_missing_require`
Ported from: code4arena audit 2024-11-mantra-dex
Severity: MEDIUM
Pattern: function whose name matches the target regex writes a state var
matching the write regex, but does NOT contain a `require`/`assert` that
references the guard variable regex. Flag the function.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
Spec: detectors/_specs/when-a-user-single-side-deposit-into-a-pool-slippage-protect-x.yaml
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract, is_leaf_helper
from slither.core.cfg.node import NodeType
from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification


class WhenAUserSingleSideDepositIntoAPoolSlippageProtectX(AbstractDetector):
    ARGUMENT = "when-a-user-single-side-deposit-into-a-pool-slippage-protect-x"
    HELP = "oakcobalt , also found by Egis_Security When a user single-side deposit into a pool, a swap is performed first before liquidity provision. The vulnerability is belief_price is alwa"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "When a user single-side deposit into a pool, slippage protection is invalid"
    WIKI_DESCRIPTION = "oakcobalt , also found by Egis_Security When a user single-side deposit into a pool, a swap is performed first before liquidity provision. The vulnerability is belief_price is always set to NONE which causes slippage protection to be invalid in some cases. //contracts/pool-manager/src/liquidity/comm"
    WIKI_EXPLOIT_SCENARIO = "Per audit finding: oakcobalt , also found by Egis_Security When a user single-side deposit into a pool, a swap is performed first before liquidity provision. The vulnerability is belief_price is always set to NONE which"
    WIKI_RECOMMENDATION = "See source audit report for recommended fix."

    _FN_NAME_REGEX = re.compile(r".*(InvalidPoolAssetsLength|belief_price|max_spread).*", re.IGNORECASE)
    _WRITE_VAR_REGEX = re.compile(r".*(belief_price|max_spread).*", re.IGNORECASE)
    _GUARD_VAR_REGEX = re.compile(r".*(belief_price|max_spread).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                if not self._FN_NAME_REGEX.search(f.name):
                    continue
                if is_leaf_helper(f):
                    continue

                writes_target = False
                for sv in f.state_variables_written:
                    if self._WRITE_VAR_REGEX.search(sv.name):
                        writes_target = True
                        break
                if not writes_target:
                    continue

                has_guard = False
                for node in f.nodes:
                    if node.type not in (NodeType.IF, NodeType.EXPRESSION):
                        continue
                    if not node.contains_require_or_assert():
                        continue
                    expr_text = str(node.expression) if node.expression else ""
                    if self._GUARD_VAR_REGEX.search(expr_text):
                        has_guard = True
                        break

                if has_guard:
                    continue

                info = [
                    f,
                    f" — when-a-user-single-side-deposit-into-a-pool-slippage-protect-x: writes `.*(belief_price|max_spread).*`-matching state without a `require` on `.*(belief_price|max_spread).*`. ",
                    f"Ported from code4arena audit 2024-11-mantra-dex.",
                ]
                results.append(self.generate_result(info))
        return results
