"""
erc-721-burn-without-check — generated from skeleton `highlevelcall_missing_sibling`
Ported from: Hexens Glider query: erc-721-tokens-can-be-burned-by-anyone
Severity: MEDIUM
Pattern: a function makes a HighLevelCall to an external function matching
the trigger signature regex, but does NOT also make a sibling call
matching the required sibling signature regex in the same function body.

Generated by tools/gen-detector.py — DO NOT EDIT BY HAND.
"""

import re
import sys
from pathlib import Path as _Path

sys.path.insert(0, str(_Path(__file__).resolve().parent.parent))
from _template_utils import is_vendored_or_test_contract

from slither.detectors.abstract_detector import AbstractDetector, DetectorClassification
from slither.slithir.operations import HighLevelCall
from slither.core.declarations import Function


class Erc721BurnWithoutCheck(AbstractDetector):
    ARGUMENT = "erc-721-burn-without-check"
    HELP = "ERC-721 burn without check"
    IMPACT = DetectorClassification.MEDIUM
    CONFIDENCE = DetectorClassification.MEDIUM
    WIKI = "https://github.com/Vuk97/auditooor/blob/main/reference/bug_patterns_observed.md"
    WIKI_TITLE = "ERC-721 burn without check"
    WIKI_DESCRIPTION = "Main contracts exposing burn(uint256) that calls _burn(uint256), with no modifiers, and no msg.sender usage in the function body."
    WIKI_EXPLOIT_SCENARIO = "Per Glider query tags [ERC-721, access-control, burn]: Main contracts exposing burn(uint256) that calls _burn(uint256), with no modifiers, and no msg.sender usage in the function body."
    WIKI_RECOMMENDATION = "Apply the guard described by the Glider query; cross-reference the canonical Hexens doc."

    _TRIGGER_SIG_REGEX = re.compile(r".*(erc).*", re.IGNORECASE)
    _REQUIRED_SIBLING_REGEX = re.compile(r".*(validate|check|verify|assert).*", re.IGNORECASE)

    def _detect(self):
        results = []
        for c in self.contracts:
            if is_vendored_or_test_contract(c):
                continue
            for f in c.functions_and_modifiers_declared:
                triggers = []
                siblings = []
                for hc_tuple in f.high_level_calls:
                    hc = hc_tuple[1] if isinstance(hc_tuple, tuple) else hc_tuple
                    if not isinstance(hc, HighLevelCall):
                        continue
                    if not isinstance(hc.function, Function):
                        continue
                    sig = hc.function.solidity_signature or hc.function.name
                    if self._TRIGGER_SIG_REGEX.search(sig):
                        triggers.append(sig)
                    if self._REQUIRED_SIBLING_REGEX.search(sig):
                        siblings.append(sig)
                if triggers and not siblings:
                    info = [
                        f,
                        f" — erc-721-burn-without-check: calls `{{{{}}}}` without also calling a `.*(validate|check|verify|assert).*` sibling. ",
                        f"Ported from Hexens Glider query: erc-721-tokens-can-be-burned-by-anyone.",
                    ]
                    results.append(self.generate_result(info))
        return results
