#!/usr/bin/env bash
# apply-patterns.sh — mechanically apply all pattern sources against workspace source.
#
# Usage:
#   ./tools/apply-patterns.sh <workspace> [--target-type lending|vault|dex|bridge|bundler]
#
# Extracts grep patterns from 3 sources:
#   1. reference/bug_patterns_observed.md — Grep/Code smell fields (P1..P187+)
#   2. reference/solodit_grep_catalog.md — all grep patterns by vuln class
#   3. tools/apply-queries.sh patterns (Hexens Glider grep approximations)
#
# Outputs: <workspace>/PATTERN_HITS.md — structured hit report grouped by pattern source.
#
# Fixes SKILL_ISSUES #70, #71, #72.

set -uo pipefail

AUDITOOOR_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUG_PATTERNS="$AUDITOOOR_DIR/reference/bug_patterns_observed.md"
SOLODIT_GREP="$AUDITOOOR_DIR/reference/solodit_grep_catalog.md"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <workspace> [--target-type lending|vault|dex|bridge|bundler]"
    exit 1
fi

WS="$1"
TARGET_TYPE="${3:-all}"
shift
while [ $# -gt 0 ]; do
    case "$1" in
        --target-type) TARGET_TYPE="$2"; shift 2 ;;
        *) shift ;;
    esac
done

# Find source directory
SRC_DIR=""
SOURCE_LANG=""
RG_GLOB=""
for candidate in "$WS/src" "$WS/contracts" "$WS"; do
    if [ -d "$candidate" ]; then
        sol_found=$(find "$candidate" -name "*.sol" -print -quit 2>/dev/null)
        if [ -n "$sol_found" ]; then
            SRC_DIR="$candidate"
            SOURCE_LANG="Solidity"
            RG_GLOB="*.sol"
            break
        fi
    fi
done

if [ -z "$SRC_DIR" ]; then
    for candidate in "$WS/src/contracts" "$WS/contracts" "$WS/src" "$WS"; do
        if [ -d "$candidate" ]; then
            rust_found=$(find "$candidate" -name "*.rs" -not -path "*/target/*" -not -path "*/tests/*" -not -path "*/fuzz/*" -print -quit 2>/dev/null)
            if [ -n "$rust_found" ]; then
                SRC_DIR="$candidate"
                SOURCE_LANG="Rust"
                RG_GLOB="*.rs"
                break
            fi
        fi
    done
fi

if [ -z "$SRC_DIR" ]; then
    echo "[error] No Solidity or Rust source found in $WS"
    exit 1
fi

OUT="$WS/PATTERN_HITS.md"
TOTAL_HITS=0
TOTAL_PATTERNS=0
PATTERNS_WITH_HITS=0

cat > "$OUT" << 'HEADER'
# Pattern Hits

Auto-generated by `tools/apply-patterns.sh`. Each section groups hits from a
different pattern source. Investigate hits marked HIGH first.

---

HEADER

echo "**Source language:** $SOURCE_LANG" >> "$OUT"
echo "**Source root:** \`$SRC_DIR\`" >> "$OUT"
echo "" >> "$OUT"

echo "[apply-patterns] scanning $SRC_DIR ($SOURCE_LANG)"
echo "[apply-patterns] target type: $TARGET_TYPE"

# ---- Source 1: bug_patterns_observed.md ----
echo "" >> "$OUT"
echo "## Source 1: bug_patterns_observed.md" >> "$OUT"
echo "" >> "$OUT"

if [ -f "$BUG_PATTERNS" ]; then
    # Extract Grep fields — lines starting with | **Grep** |
    GREP_COUNT=0
    CURRENT_PATTERN=""
    while IFS= read -r line; do
        # Capture pattern header
        if echo "$line" | grep -q "^### P[0-9]"; then
            CURRENT_PATTERN="$line"
        fi
        # Capture grep commands
        if echo "$line" | grep -q '| \*\*Grep\*\* |'; then
            GREP_CMD=$(echo "$line" | sed 's/.*| \*\*Grep\*\* | //' | sed 's/ |$//' | head -c 500)
            # Extract the rg pattern from backticks or raw text
            RG_PATTERN=$(echo "$GREP_CMD" | sed -n "s/.*rg -n '\([^']*\)'.*/\1/p" | head -1)
            if [ -n "$RG_PATTERN" ]; then
                TOTAL_PATTERNS=$((TOTAL_PATTERNS + 1))
                HITS=$(rg -c "$RG_PATTERN" -g "$RG_GLOB" "$SRC_DIR" 2>/dev/null | awk -F: '{s+=$2} END {print s+0}')
                if [ "$HITS" -gt 0 ]; then
                    PATTERNS_WITH_HITS=$((PATTERNS_WITH_HITS + 1))
                    TOTAL_HITS=$((TOTAL_HITS + HITS))
                    echo "### $CURRENT_PATTERN" >> "$OUT"
                    echo "**Hits: $HITS**" >> "$OUT"
                    echo '```' >> "$OUT"
                    rg -n "$RG_PATTERN" -g "$RG_GLOB" "$SRC_DIR" 2>/dev/null | head -10 >> "$OUT"
                    if [ "$HITS" -gt 10 ]; then
                        echo "... ($((HITS - 10)) more)" >> "$OUT"
                    fi
                    echo '```' >> "$OUT"
                    echo "" >> "$OUT"
                    GREP_COUNT=$((GREP_COUNT + 1))
                fi
            fi
        fi
    done < "$BUG_PATTERNS"
    echo "  [bug_patterns] $GREP_COUNT patterns with hits" >&2
else
    echo "  [skip] bug_patterns_observed.md not found" >&2
    echo "*File not found*" >> "$OUT"
fi

# ---- Source 2: solodit_grep_catalog.md ----
echo "" >> "$OUT"
echo "## Source 2: solodit_grep_catalog.md" >> "$OUT"
echo "" >> "$OUT"

if [ -f "$SOLODIT_GREP" ]; then
    SOLODIT_COUNT=0
    CURRENT_CLASS=""
    while IFS= read -r line; do
        # Capture class header
        if echo "$line" | grep -q "^# "; then
            CURRENT_CLASS=$(echo "$line" | sed 's/^# //')
        fi
        # Capture rg patterns
        if echo "$line" | grep -q "^rg -n "; then
            RG_PATTERN=$(echo "$line" | sed "s/rg -n '//;s/'.*//")
            if [ -n "$RG_PATTERN" ]; then
                TOTAL_PATTERNS=$((TOTAL_PATTERNS + 1))
                HITS=$(rg -c "$RG_PATTERN" -g "$RG_GLOB" "$SRC_DIR" 2>/dev/null | awk -F: '{s+=$2} END {print s+0}')
                if [ "$HITS" -gt 0 ]; then
                    PATTERNS_WITH_HITS=$((PATTERNS_WITH_HITS + 1))
                    TOTAL_HITS=$((TOTAL_HITS + HITS))
                    echo "### $CURRENT_CLASS" >> "$OUT"
                    echo "**Pattern:** \`$RG_PATTERN\` — **$HITS hits**" >> "$OUT"
                    echo '```' >> "$OUT"
                    rg -n "$RG_PATTERN" -g "$RG_GLOB" "$SRC_DIR" 2>/dev/null | head -5 >> "$OUT"
                    if [ "$HITS" -gt 5 ]; then
                        echo "... ($((HITS - 5)) more)" >> "$OUT"
                    fi
                    echo '```' >> "$OUT"
                    echo "" >> "$OUT"
                    SOLODIT_COUNT=$((SOLODIT_COUNT + 1))
                fi
            fi
        fi
    done < "$SOLODIT_GREP"
    echo "  [solodit_grep] $SOLODIT_COUNT patterns with hits" >&2
else
    echo "  [skip] solodit_grep_catalog.md not found" >&2
    echo "*File not found*" >> "$OUT"
fi

# ---- Summary ----
cat >> "$OUT" << SUMMARY

---

## Summary

| Source | Patterns checked | Patterns with hits | Total hits |
|--------|------------------|--------------------|------------|
| bug_patterns_observed | — | — | — |
| solodit_grep_catalog | — | — | — |
| **TOTAL** | **$TOTAL_PATTERNS** | **$PATTERNS_WITH_HITS** | **$TOTAL_HITS** |

Generated $(date -u +%Y-%m-%dT%H:%M:%SZ) by \`tools/apply-patterns.sh\`
SUMMARY

echo ""
echo "[done] $TOTAL_PATTERNS patterns checked, $PATTERNS_WITH_HITS with hits, $TOTAL_HITS total hits"
echo "[done] output: $OUT"
