#!/usr/bin/env bash
# digest-aggregate.sh — cross-engagement digest persistence (Issue #126).
#
# Scans ~/audits/*/prior_audits/DIGEST_*.md across every past engagement and
# produces a cross-engagement summary of RECURRING bug families + TOP attacker
# angles. Runs idempotently; designed to be invoked at the end of every
# engagement (append new digests to the aggregate).
#
# Output: auditooor/reference/recurring_bug_families.md
#
# Usage:
#   ./tools/digest-aggregate.sh                 # scan + write aggregate
#   ./tools/digest-aggregate.sh --audit-root ~/audits  # override scan root

set -u
AUDIT_ROOT="$HOME/audits"
while [ $# -gt 0 ]; do
  case "$1" in
    --audit-root) AUDIT_ROOT="$2"; shift 2 ;;
    *) shift ;;
  esac
done

AUDITOOOR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$AUDITOOOR_DIR/reference/recurring_bug_families.md"

if [ ! -d "$AUDIT_ROOT" ]; then
  echo "[digest-aggregate] $AUDIT_ROOT not found — nothing to aggregate" >&2
  exit 1
fi

python3 - "$AUDIT_ROOT" "$OUT" <<'PY'
import re, sys, datetime, glob, os
from collections import Counter
from pathlib import Path

audit_root = sys.argv[1]
out_path = sys.argv[2]

digests = sorted(glob.glob(f"{audit_root}/*/prior_audits/DIGEST_*.md"))
if not digests:
    print(f"[digest-aggregate] no DIGEST_*.md found under {audit_root}", file=sys.stderr)
    sys.exit(0)

engagements = {}  # workspace -> list of digest paths
for d in digests:
    rel = Path(d).relative_to(audit_root)
    workspace = rel.parts[0]
    engagements.setdefault(workspace, []).append(d)

# Count bug-family keywords across all digests
FAMILY_KEYWORDS = {
    "reentrancy": r"(?i)reentran|callback.*before|CEI\s*viola",
    "batching-auth": r"(?i)batch.*auth|first.*element.*batch|batched.*bypass",
    "rounding-asymmetry": r"(?i)round.*direction|round.*down.*up|round.*asym|rounding.*favor",
    "oracle-staleness": r"(?i)oracle.*stale|stale.*price|no.*TTL|freshness|last.*update",
    "hook-bypass": r"(?i)hook.*bypass|skip.*hook|whenNotPaused|transfer.*hook",
    "cross-chain-auth": r"(?i)cross.?chain.*auth|message.*forge|chain.*id.*bind|replay.*across",
    "access-control-escalation": r"(?i)role.*escalat|admin.*bypass|privil.*escal|ward.*leak",
    "state-machine-race": r"(?i)cancel.*before|fulfill.*race|pending.*flag.*clear|state.*machine",
    "integer-casting": r"(?i)int\d+.*cast|sign.*bit|uint\d+\s*cast|downcast",
    "signature-replay": r"(?i)sig.*replay|EIP-?712|nonce.*missing|malleability",
    "refund-escrow-loss": r"(?i)refund.*escrow|stuck.*escrow|stranded.*fund",
    "approval-abuse": r"(?i)approve.*abuse|allowance.*drain|permit.*front",
    "decimals-mismatch": r"(?i)decimal.*mismatch|token.*decimals|decimal.*conv",
    "deploy-state-divergence": r"(?i)deploy.*script|role.*grant.*miss|mainnet.*deploy",
}

family_hits = Counter()
per_engagement = {}  # workspace -> Counter of family hits
all_top5 = []  # list of (workspace, audit_name, bullet)

for d in digests:
    text = Path(d).read_text(errors="ignore")
    rel = Path(d).relative_to(audit_root)
    workspace = rel.parts[0]
    audit_name = Path(d).stem.replace("DIGEST_", "")

    per_engagement.setdefault(workspace, Counter())

    for family, rx in FAMILY_KEYWORDS.items():
        matches = len(re.findall(rx, text))
        if matches:
            family_hits[family] += matches
            per_engagement[workspace][family] += matches

    # Parse TOP-5 attacker angles if present
    m = re.search(r"(?mi)^##?\s*(?:TOP-5|Useful attacker angles|Attacker angles)[^\n]*\n(.*?)(?:\n##\s|\Z)", text, re.DOTALL)
    if m:
        block = m.group(1)
        bullets = re.findall(r"^\s*[-*\d.]+\s+(.{20,300})$", block, re.MULTILINE)
        for b in bullets[:5]:
            all_top5.append((workspace, audit_name, b.strip()))

# Write aggregate
lines = []
lines.append("# Recurring bug families across engagements")
lines.append("")
lines.append(f"Auto-generated by `tools/digest-aggregate.sh` on {datetime.datetime.now(datetime.timezone.utc).isoformat()}Z.")
lines.append(f"Sources: {len(digests)} DIGESTs across {len(engagements)} engagements.")
lines.append("")
lines.append("**Purpose:** cross-engagement learning. When starting a new audit, skim this file to remember which bug families recur across the DeFi ecosystem.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Bug-family heatmap")
lines.append("")
lines.append("| Family | Total mentions | Seen in engagements |")
lines.append("|---|---:|---|")

# Sort by total hits
for family, total in family_hits.most_common():
    seen_in = [ws for ws, c in per_engagement.items() if c.get(family, 0) > 0]
    lines.append(f"| `{family}` | {total} | {', '.join(seen_in)} |")

lines.append("")
lines.append("## Per-engagement summary")
lines.append("")
for ws, counter in sorted(per_engagement.items()):
    lines.append(f"### `{ws}`")
    lines.append(f"- {len(engagements[ws])} digests loaded")
    top_families = counter.most_common(5)
    if top_families:
        lines.append(f"- Top bug families: " + ", ".join(f"`{f}` ({c})" for f, c in top_families))
    lines.append("")

lines.append("## Cross-engagement top attacker angles")
lines.append("")
lines.append(f"(first {min(30, len(all_top5))} of {len(all_top5)} extracted; deduplicated by substring prefix)")
lines.append("")
seen_prefixes = set()
count = 0
for ws, audit_name, bullet in all_top5:
    prefix = bullet[:60].lower()
    if prefix in seen_prefixes:
        continue
    seen_prefixes.add(prefix)
    lines.append(f"- **[{ws}/{audit_name}]** {bullet}")
    count += 1
    if count >= 30:
        break

lines.append("")
lines.append("---")
lines.append("")
lines.append("## How to use this file")
lines.append("")
lines.append("1. At the start of every new engagement, read the `Bug-family heatmap` table — the top 3 families are where the DeFi ecosystem keeps regressing.")
lines.append("2. For the target protocol's vertical (lending / vault / exchange / bridge), check which families appeared in engagements with similar verticals.")
lines.append("3. Feed the top-3 families into `generate-hypotheses.sh` as priming context.")
lines.append("4. After closing the engagement, re-run `digest-aggregate.sh` to update the corpus.")

Path(out_path).write_text("\n".join(lines))
print(f"[digest-aggregate] {len(digests)} digests from {len(engagements)} engagements → {out_path}")
print(f"[digest-aggregate] top-3 recurring: {', '.join(f for f,_ in family_hits.most_common(3))}")
PY
