#!/usr/bin/env bash
# full-audit.sh — R76 orchestrator: run EVERY auditooor analyzer against
# a workspace in the right order, so a fresh engagement can go from
# "source cloned" to "full attack-surface report" with one command.
#
# Chain:
#   1. scan.sh              — base pattern scan (904 detectors)
#   2. attack-path.py       — reachability to high-value sinks
#   3. acl-matrix.py        — access-control matrix + ungated-privileged
#   4. storage-layout.py    — proxy / diamond layout
#   5. integration-assumptions.py — implicit assumption hypotheses
#   6. missing-check-catalog.py    — "op X needs check Y" rules
#   7. invariant-proposer.py       — candidate Foundry invariants
#   8. invariant-hunt.sh (class=auto) — if user passes --hunt
#   9. economic-hypotheses-ir.py   — IR dataflow attack-surface
#  10. auto-triage.sh       — LLM-dispatch brief
#  11. auto-poc-synth.py    — PoC scaffolds from scan hits
#
# Output: per-tool reports in the workspace + a top-level FULL_AUDIT.md
# that summarizes every finding class with triage-friendly links.
#
# Usage:
#   bash tools/full-audit.sh <workspace> [--hunt] [--skip-scan]

set -uo pipefail
AUDITOOOR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WS="${1:-}"
HUNT=0
SKIP_SCAN=0
shift 1 2>/dev/null || true
while [ $# -gt 0 ]; do
    case "$1" in
        --hunt) HUNT=1; shift ;;
        --skip-scan) SKIP_SCAN=1; shift ;;
        -h|--help)
            sed -n '2,25p' "$0" | sed 's/^# //; s/^#//'; exit 0 ;;
        *) echo "[warn] ignoring: $1" >&2; shift ;;
    esac
done

[ -z "$WS" ] && { echo "usage: $0 <workspace> [--hunt] [--skip-scan]" >&2; exit 1; }
[ -d "$WS" ] || { echo "[err] workspace not found: $WS" >&2; exit 1; }

REPORT="$WS/FULL_AUDIT.md"
echo "# Full audit report — $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$REPORT"
echo "" >> "$REPORT"
echo "Generated by \`tools/full-audit.sh\`. Workspace: \`$WS\`." >> "$REPORT"
echo "" >> "$REPORT"

log_step() {
    echo ""
    echo "────────────────────────────────────────────────────────"
    echo "[$1] $2"
    echo "────────────────────────────────────────────────────────"
    echo "" >> "$REPORT"
    echo "## $1 — $2" >> "$REPORT"
    echo "" >> "$REPORT"
}

run_step() {
    local label="$1" cmd="$2" outfile="$3"
    log_step "$label" "$cmd"
    eval "$cmd" 2>&1 | tail -5 | tee -a "$REPORT"
    [ -f "$WS/$outfile" ] && echo "" >> "$REPORT" && echo "📄 See \`$outfile\`" >> "$REPORT"
}

# ── 1. Pattern scan (the 904-detector sweep) ──
if [ "$SKIP_SCAN" = 0 ]; then
    run_step "1/10" "bash $AUDITOOOR/tools/scan.sh $WS" "custom-detectors.log"
fi

# ── 2. Attack-path analysis ──
run_step "2/10" "python3 $AUDITOOOR/tools/attack-path.py $WS" "attack_paths.md"

# ── 3. ACL matrix ──
run_step "3/10" "python3 $AUDITOOOR/tools/acl-matrix.py $WS" "acl_matrix.md"

# ── 4. Storage layout ──
run_step "4/10" "python3 $AUDITOOOR/tools/storage-layout.py $WS" "storage_layout.md"

# ── 5. Integration assumptions ──
run_step "5/10" "python3 $AUDITOOOR/tools/integration-assumptions.py $WS" "integration_assumptions.md"

# ── 6. Missing-check catalog ──
run_step "6/10" "python3 $AUDITOOOR/tools/missing-check-catalog.py $WS" "missing_checks.md"

# ── 7. Invariant proposer ──
run_step "7/10" "python3 $AUDITOOOR/tools/invariant-proposer.py $WS" "invariant_hunt/auto_proposed"

# ── 8. Invariant-hunt (optional) ──
if [ "$HUNT" = 1 ]; then
    if ls "$WS/src/"*/foundry.toml >/dev/null 2>&1 || [ -f "$WS/foundry.toml" ]; then
        run_step "8/10" "bash $AUDITOOOR/tools/invariant-hunt.sh $WS auto" "invariant_hunt"
    else
        echo "[skip] 8/10 invariant-hunt — no foundry.toml found" | tee -a "$REPORT"
    fi
else
    echo "[skip] 8/10 invariant-hunt — pass --hunt to run" | tee -a "$REPORT"
fi

# ── 9. Economic hypotheses ──
# Find the biggest .sol file as a first target (usually the main entry contract)
MAIN_SOL=""
if [ -d "$WS/src" ]; then
    MAIN_SOL=$(find "$WS/src" -name "*.sol" -type f 2>/dev/null | head -20 | xargs ls -S 2>/dev/null | head -1)
fi
if [ -n "$MAIN_SOL" ] && [ -f "$MAIN_SOL" ]; then
    run_step "9/10" "python3 $AUDITOOOR/tools/economic-hypotheses-ir.py $MAIN_SOL" "economic_hypotheses_ir"
else
    echo "[skip] 9/10 economic-hypotheses — no main .sol found" | tee -a "$REPORT"
fi

# ── 10. Auto-PoC synth ──
if [ -f "$WS/custom-detectors.log" ]; then
    run_step "10/10" "python3 $AUDITOOOR/tools/auto-poc-synth.py $WS --top 10" "test/poc"
fi

# ── Summary footer ──
echo "" >> "$REPORT"
echo "## Quick-read links" >> "$REPORT"
echo "" >> "$REPORT"
for f in attack_paths.md acl_matrix.md storage_layout.md integration_assumptions.md missing_checks.md auto_triage_brief.md; do
    if [ -f "$WS/$f" ]; then
        echo "- [\`$f\`]($f)" >> "$REPORT"
    fi
done

echo ""
echo "════════════════════════════════════════════════════════"
echo "Full audit report:  $REPORT"
echo "════════════════════════════════════════════════════════"
