#!/usr/bin/env python3
"""fuzz-campaign.py — V5 PR 4 fuzz-campaign wrapper (stdlib-only).

Per docs/ROADMAP_10_OF_10_V5_CAMPAIGNS.md Section 4. Implements a bounded
campaign farm that ORCHESTRATES the existing fuzz/deep tooling rather than
adding a new engine. This is Codex's hard rule: "First inventory existing
fuzz/deep tools before adding new engines."

Existing tools the wrapper orchestrates (do NOT duplicate):

  - tools/fuzz-runner.sh         bounded medusa|echidna|auto runner with
                                 timeout, manifest, counterexample capture
                                 (PR 107 / capv3-iter1-T1).
  - forge test --invariant       Forge invariant/fuzz harnesses generated by
                                 tools/gen-invariants.sh and class templates
                                 under reference/invariant_class_templates/.
  - tools/symbolic-ce-to-forge.py halmos CE → Forge replay scaffold (capv3
                                 iter8-T3). Used in forge_test_generated.
  - tools/poc-scaffold.py         pattern-based PoC scaffold generator. Used
                                 when no symbolic CE is available and the
                                 wrapper falls back to a generic Forge
                                 reproducer for a shrunk crash sequence.
  - tools/audit-deep.sh           profile-driven deep audit aggregator.
                                 Surfaced in summary.md as a follow-up
                                 pointer; the wrapper does NOT invoke
                                 audit-deep itself (out of scope, would
                                 spin up halmos/medusa/echidna chains).

Lifecycle (Codex's exact spec):

    created -> seeding -> running -> crash_found|timeout|coverage_plateau ->
    shrinking -> forge_test_generated -> verified|rejected

Artifact layout (Codex's exact spec):

    fuzz_campaigns/<id>/
      config.json                campaign config (lane='fuzz', target,
                                 profile, duration, engine)
      coverage.json              coverage manifest (engine-reported or
                                 honest-zero placeholder)
      crashes/*.json             one JSON per unique crash, with
                                 {crash_id, status, raw_seq, dedup_hash,
                                 source_run, captured_at}
      shrunk/*.json              one JSON per shrunk crash, with
                                 {crash_id, original_len, shrunk_len,
                                 shrunk_seq, method}
      forge_tests/*.t.sol        generated Forge replay tests
      replay.log                 chronological state-transition log
      summary.md                 human-readable campaign summary

First-implementation scope (PR 4):
  - Forge invariant/fuzz only via fuzz-runner.sh's existing engine layer.
  - Shrink uses a deterministic suffix-pruning strategy on the captured
    failing-sequence trace; non-deterministic Forge fuzz seeds are
    surfaced in the shrunk artifact's `seed_determinism` field.
  - Symbolic / Halmos / Medusa orchestration deferred to a follow-up PR.
    Stated explicitly in the PR body and in summary.md when the chosen
    engine is "auto" but only Forge is available.

Terminology constraint (Codex): this is NOT "infinite fuzzers". It is a
bounded campaign farm. Budget guards (--duration cap), crash dedupe (SHA
of normalized sequence), and resume behaviour (campaign-state init is
idempotent) are first-class.

CLI surface::

    python3 tools/fuzz-campaign.py \\
        --workspace ~/audits/<project> \\
        --target <Contract> \\
        --profile invariant \\
        --duration 3600 \\
        --out ~/audits/<project>/fuzz_campaigns/<id>

Honest-finding contract:
  - Every terminal state writes summary.md. timeout / coverage_plateau /
    rejected MUST NOT claim "verified". The "verified" state is only
    reachable when the generated Forge test reproduces on the
    vulnerable version AND changes behavior (or fails) on the
    recommended-fix version. That gate is operator-driven (pre/post-fix
    smoke); the wrapper records the evidence but does not auto-promote.

Stdlib-only: argparse, hashlib, json, pathlib, re, shutil, subprocess,
sys, time, datetime, typing.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Iterable

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LIFECYCLE_STATES = (
    "created",
    "seeding",
    "running",
    "crash_found",
    "timeout",
    "coverage_plateau",
    "shrinking",
    "forge_test_generated",
    "verified",
    "rejected",
)

# States that are TERMINAL (no further transitions inside this run).
TERMINAL_STATES = frozenset({"verified", "rejected", "timeout", "coverage_plateau"})

# Which transitions are legal. Codex's lifecycle is mostly linear with two
# branches at the running fork. Keep the table small and explicit so foot-gun
# #15-style silent regressions get caught at runtime.
_TRANSITIONS: dict[str, frozenset[str]] = {
    "created": frozenset({"seeding"}),
    "seeding": frozenset({"running"}),
    "running": frozenset({"crash_found", "timeout", "coverage_plateau"}),
    "crash_found": frozenset({"shrinking"}),
    "shrinking": frozenset({"forge_test_generated"}),
    "forge_test_generated": frozenset({"verified", "rejected"}),
    "timeout": frozenset(),  # terminal honest-non-finding
    "coverage_plateau": frozenset(),  # terminal honest-non-finding
    "verified": frozenset(),
    "rejected": frozenset(),
}

PROFILES = ("invariant", "fuzz")

# Hard cap on --duration to prevent unbounded runs (foot-gun: "infinite
# fuzzers" creep). Mirrors fuzz-runner.sh's 3600s cap.
DURATION_CAP_SECONDS = 3600

# Maximum sequence-line length retained in shrunk artifacts (avoid bloating
# crashes/*.json with megabyte traces).
SHRUNK_MAX_LINES = 256

REPO_ROOT = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# JSON / time helpers
# ---------------------------------------------------------------------------

def _utcnow_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _elapsed_seconds(started_at: str, ended_at: str) -> int:
    try:
        start = _dt.datetime.fromisoformat(started_at.replace("Z", "+00:00"))
        end = _dt.datetime.fromisoformat(ended_at.replace("Z", "+00:00"))
    except (TypeError, ValueError):
        return 0
    return max(0, int((end - start).total_seconds()))


def _finalize_runtime(state: dict[str, Any]) -> None:
    state["ended_at"] = _utcnow_iso()
    state["duration"] = _elapsed_seconds(
        str(state.get("started_at", "")),
        str(state.get("ended_at", "")),
    )


def _atomic_write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, sort_keys=True))
    tmp.replace(path)


def _append_replay(path: Path, event: str, **fields: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    line = {"ts": _utcnow_iso(), "event": event, **fields}
    with path.open("a") as f:
        f.write(json.dumps(line, sort_keys=True) + "\n")


# ---------------------------------------------------------------------------
# Crash deduplication
# ---------------------------------------------------------------------------

# Failing-sequence normalization: strip volatile fields (timestamps,
# addresses, hex blob lengths) before hashing so two reruns of the same
# Forge fuzz with different seeds dedup to one crash.
_VOLATILE_PATTERNS = (
    (re.compile(r"0x[0-9a-fA-F]{40}"), "<addr>"),
    (re.compile(r"0x[0-9a-fA-F]{16,}"), "<hex>"),
    (re.compile(r"\bts=\d+"), "ts=<n>"),
    (re.compile(r"\btimestamp=\d+"), "timestamp=<n>"),
    (re.compile(r"\bgas:\s*\d+"), "gas: <n>"),
    (re.compile(r"\bseed:\s*\d+"), "seed: <n>"),
    (re.compile(r"\brun:\s*\d+"), "run: <n>"),
    # Forge invariant counters — different across reruns of the SAME crash.
    (re.compile(r"\bruns:\s*\d+"), "runs: <n>"),
    (re.compile(r"\bcalls:\s*\d+"), "calls: <n>"),
    (re.compile(r"\breverts:\s*\d+"), "reverts: <n>"),
    # Generic large numbers AFTER the specific patterns above so we don't
    # eat single-digit args like deposit(100). Threshold = 10 digits to
    # avoid touching small literals in the call sequence.
    (re.compile(r"\b\d{10,}\b"), "<num>"),
)


def normalize_sequence(text: str) -> str:
    """Normalize a failing-sequence trace for dedup hashing.

    Public for unit-test use. Strips volatile addresses/hex/numbers that
    differ across reruns of the same crash but preserves the call shape.
    """
    out = text
    for rx, repl in _VOLATILE_PATTERNS:
        out = rx.sub(repl, out)
    # Collapse repeated whitespace; preserve newlines for sequence shape.
    out = re.sub(r"[ \t]+", " ", out)
    return out.strip()


def crash_dedup_hash(failing_sequence: str) -> str:
    """First 12 chars of SHA256 over normalized sequence."""
    norm = normalize_sequence(failing_sequence)
    return hashlib.sha256(norm.encode("utf-8")).hexdigest()[:12]


# ---------------------------------------------------------------------------
# Lifecycle / state helpers
# ---------------------------------------------------------------------------

def can_transition(from_state: str, to_state: str) -> bool:
    """Return True iff the state machine permits from→to.

    Public for unit tests. Foot-gun guard: a wrapper bug that tries to
    write 'verified' directly from 'timeout' is a silent honesty bypass —
    we reject it loudly.
    """
    if from_state not in _TRANSITIONS:
        return False
    return to_state in _TRANSITIONS[from_state]


def transition(state: dict[str, Any], to_state: str, replay_log: Path,
               **details: Any) -> None:
    """Mutate state['lifecycle'] with validation + replay log entry."""
    cur = state.get("lifecycle", "created")
    if not can_transition(cur, to_state):
        raise ValueError(
            f"illegal transition {cur!r} -> {to_state!r} "
            f"(allowed: {sorted(_TRANSITIONS.get(cur, ()))})"
        )
    state["lifecycle"] = to_state
    state["updated_at"] = _utcnow_iso()
    _append_replay(replay_log, f"transition:{to_state}",
                   from_state=cur, **details)


# ---------------------------------------------------------------------------
# Fuzz runner orchestration
# ---------------------------------------------------------------------------

def _which(binary: str) -> str | None:
    return shutil.which(binary)


def _engine_available(engine: str) -> bool:
    if engine == "forge":
        return _which("forge") is not None
    if engine in ("medusa", "echidna"):
        return _which(engine) is not None
    return False


def discover_engine(workspace: Path, requested: str) -> str:
    """Pick an engine. Defaults to 'forge' (PR 4 first-impl scope).

    Returns the chosen engine name. Raises RuntimeError if the requested
    engine is not on PATH. Does NOT silently fall through — that would
    let a user think medusa is running when only forge is.
    """
    if requested == "auto":
        if _engine_available("forge"):
            return "forge"
        # PR 4 scope: do not orchestrate medusa/echidna ourselves. Surface a
        # clear error rather than pretending the wrapper supports them today.
        raise RuntimeError(
            "no fuzz engine on PATH. PR 4 wrapper supports forge only. "
            "medusa/echidna orchestration is deferred to a follow-up PR; "
            "for those engines invoke tools/fuzz-runner.sh directly."
        )
    if requested == "forge":
        if not _engine_available("forge"):
            raise RuntimeError("forge not on PATH")
        return "forge"
    if requested in ("medusa", "echidna"):
        # Defer cleanly — give the caller an actionable message. PR 4
        # explicitly defers medusa/echidna orchestration to a follow-up
        # PR; wrapper supports forge only today.
        raise RuntimeError(
            f"engine {requested!r} deferred to a follow-up PR. PR 4 "
            f"wrapper supports forge only. Use tools/fuzz-runner.sh "
            f"directly for medusa/echidna; symbolic/Halmos orchestration "
            f"is also deferred."
        )
    raise RuntimeError(f"unknown engine: {requested!r}")


def run_forge_campaign(workspace: Path, target: str, profile: str,
                       duration: int, out_dir: Path,
                       _runner_override: list[str] | None = None) -> dict[str, Any]:
    """Invoke `forge test --invariant` (or --fuzz) under a wall-clock cap.

    Returns a result dict with keys: status, exit_code, stdout_path,
    stderr_path, duration_s, command, engine_version. The status alphabet
    is the wrapper's vocabulary, mapped from forge exit codes:
      - "crash_found"   → forge exit != 0 AND crash markers present
      - "timeout"       → wall-clock exceeded
      - "coverage_plateau" → forge passed AND --duration >= 60 (heuristic;
                          v1 conservative — operator can override)
      - "no_finding"    → forge passed, short run, no crash and no plateau

    The `_runner_override` argv is for tests only — it lets the test inject
    a fake `forge` command without PATH-shadowing.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    stdout_path = out_dir / "forge.stdout.log"
    stderr_path = out_dir / "forge.stderr.log"

    # Build forge argv. The runner_override path lets tests inject a fake
    # forge that emits crash markers / pass / hang on demand.
    if _runner_override is not None:
        argv = list(_runner_override)
    else:
        # Use --match-contract to scope to the target. --fuzz-runs and
        # --invariant-runs are bounded so a misconfigured project cannot
        # blow past --duration on a single seed expansion.
        if profile == "invariant":
            argv = [
                "forge", "test",
                "--match-contract", target,
                "--invariant-runs", "256",
                "--invariant-depth", "32",
            ]
        else:  # fuzz
            argv = [
                "forge", "test",
                "--match-contract", target,
                "--fuzz-runs", "256",
            ]

    # Get engine version best-effort (only when not overridden — tests
    # don't care).
    engine_version = ""
    if _runner_override is None:
        try:
            v = subprocess.check_output(
                ["forge", "--version"], stderr=subprocess.DEVNULL, timeout=5
            )
            engine_version = v.decode("utf-8", "replace").strip().splitlines()[0]
        except (FileNotFoundError, subprocess.TimeoutExpired,
                subprocess.CalledProcessError):
            pass

    started = time.monotonic()
    try:
        proc = subprocess.run(
            argv,
            cwd=str(workspace),
            stdout=stdout_path.open("w"),
            stderr=stderr_path.open("w"),
            timeout=duration,
        )
        exit_code = proc.returncode
        timed_out = False
    except subprocess.TimeoutExpired:
        exit_code = 124
        timed_out = True
    elapsed = time.monotonic() - started

    stdout_text = stdout_path.read_text(errors="replace") if stdout_path.exists() else ""

    # Status classification
    crash_markers = bool(
        re.search(r"\b(FAIL|invariant.*failed|counterexample|panic|revert)\b",
                  stdout_text, re.IGNORECASE)
    )
    if timed_out:
        status = "timeout"
    elif crash_markers and exit_code != 0:
        status = "crash_found"
    elif exit_code == 0 and duration >= 60:
        # Conservative coverage-plateau heuristic: a clean pass under a
        # non-trivial budget. We do NOT call this "verified" — that would be
        # the dishonest classification Minimax warned about.
        status = "coverage_plateau"
    else:
        status = "no_finding"

    return {
        "status": status,
        "exit_code": exit_code,
        "stdout_path": str(stdout_path),
        "stderr_path": str(stderr_path),
        "duration_s": round(elapsed, 2),
        "command": " ".join(argv),
        "engine_version": engine_version,
    }


# ---------------------------------------------------------------------------
# Crash extraction + shrink
# ---------------------------------------------------------------------------

_CRASH_BLOCK_RE = re.compile(
    r"""
    (?:
        ^.*FAIL.*$                           # forge "[FAIL. Reason: ...]" lines
        |^.*invariant.*(?:failed|broken).*$  # invariant break
        |^\s*Counterexample:.*$              # inline counterexample
        |^\s*\[Sequence\].*$                 # forge invariant sequence header
    )
    """,
    re.IGNORECASE | re.MULTILINE | re.VERBOSE,
)


def extract_failing_sequence(stdout_text: str) -> str:
    """Pull the failing call sequence out of forge stdout.

    Forge invariant output prints the sequence between the [Sequence]
    header and the next blank line or the next "Test Result:" line. We
    capture the whole crash block + 40 trailing lines (sequence rarely
    longer than that for bounded depth=32).
    """
    if not stdout_text:
        return ""
    lines = stdout_text.splitlines()
    keep: list[str] = []
    in_block = False
    tail = 0
    for ln in lines:
        if not in_block and _CRASH_BLOCK_RE.search(ln):
            in_block = True
            keep.append(ln)
            continue
        if in_block:
            # Stop at blank-line gap after a sequence has started, OR a
            # "Test Result:" / "Suite result:" forge boundary.
            if re.match(r"^\s*(Test Result:|Suite result:|Ran \d+ test)", ln):
                break
            keep.append(ln)
            tail += 1
            if tail > 40:
                break
    return "\n".join(keep[:SHRUNK_MAX_LINES])


def shrink_sequence(failing_sequence: str) -> dict[str, Any]:
    """Deterministic shrink: prune trailing lines that are not part of
    the canonical [Sequence] block, drop blanks, dedup repeated ops.

    Returns a dict {original_len, shrunk_len, shrunk_seq, method,
    seed_determinism}. seed_determinism is "deterministic" when the input
    contains a "[Sequence]" header (Forge invariant) — otherwise
    "non-deterministic" (e.g. fuzz seeds, ad-hoc panic) and the operator
    is warned in summary.md.
    """
    raw = failing_sequence or ""
    original_len = len(raw.splitlines())
    seed_det = "deterministic" if "[Sequence]" in raw else "non-deterministic"

    # Step 1: keep only sequence-relevant lines.
    keep: list[str] = []
    seen_seq_header = False
    for ln in raw.splitlines():
        # Always keep crash header so the sequence is interpretable.
        if _CRASH_BLOCK_RE.search(ln):
            keep.append(ln.rstrip())
            if "[Sequence]" in ln:
                seen_seq_header = True
            continue
        if seen_seq_header and ln.strip():
            keep.append(ln.rstrip())

    # Step 2: dedup adjacent identical calls (common in invariant traces).
    deduped: list[str] = []
    for ln in keep:
        if not deduped or deduped[-1] != ln:
            deduped.append(ln)

    shrunk = "\n".join(deduped[:SHRUNK_MAX_LINES])
    return {
        "original_len": original_len,
        "shrunk_len": len(deduped),
        "shrunk_seq": shrunk,
        "method": "suffix-prune+dedup",
        "seed_determinism": seed_det,
    }


# ---------------------------------------------------------------------------
# Forge test generation from shrunk crash
# ---------------------------------------------------------------------------

_FORGE_TEMPLATE = """// SPDX-License-Identifier: MIT
// AUTO-GENERATED by tools/fuzz-campaign.py — DO NOT EDIT BY HAND.
// crash_id: {crash_id}
// dedup_hash: {dedup_hash}
// captured_at: {captured_at}
// seed_determinism: {seed_determinism}
//
// This is a *replay scaffold* derived from a Forge invariant/fuzz crash.
// Operator must:
//   1. Wire setUp() against the actual contract under test.
//   2. Replace the placeholder calls below with the shrunk sequence.
//   3. Run `forge test --match-path forge_tests/{file_name}` on:
//        - the vulnerable commit  -> expect FAIL
//        - the recommended-fix    -> expect PASS (or different failure)
//      Only after BOTH are observed may the campaign transition to
//      `verified`. The wrapper records evidence; the operator promotes.
pragma solidity ^0.8.0;

import "forge-std/Test.sol";

contract Replay_{contract_id} is Test {{
    // TODO: import the contract under test
    // import "{target_path}";

    function setUp() public {{
        // TODO: deploy {target} with realistic constructor args.
    }}

    function test_replay_{crash_id_short}() public {{
        // ----- begin shrunk failing sequence (verbatim from campaign) -----
        /*
{sequence_block}
        */
        // ----- end shrunk failing sequence --------------------------------

        // TODO: translate the sequence above into concrete contract calls.
        // The wrapper does NOT auto-translate Forge sequence syntax into
        // Solidity calls — that requires interface knowledge the wrapper
        // does not have. See tools/poc-scaffold.py for pattern-aware
        // scaffolds, or tools/symbolic-ce-to-forge.py for halmos CE-driven
        // replays.
        assertTrue(false, "operator: fill in the replay then remove this assert");
    }}
}}
"""


def generate_forge_test(crash_id: str, dedup_hash: str,
                        target: str, shrunk_seq: str,
                        seed_determinism: str,
                        captured_at: str,
                        out_path: Path) -> Path:
    """Render a Forge replay-scaffold .t.sol file.

    The scaffold ALWAYS asserts false until an operator wires it. This is
    intentional: a green test from an unfilled scaffold would be the
    "shrink hides root cause" failure mode Minimax warned about.
    """
    contract_id = re.sub(r"[^A-Za-z0-9_]", "_", target) or "Target"
    file_name = out_path.name
    # crash_id is 'crash-<dedup>'; the function-name segment must be
    # ASCII identifier (no hyphens, dots, etc) for Solidity to compile.
    crash_id_short = re.sub(r"[^A-Za-z0-9_]", "_", crash_id[:18])
    seq_block = "\n".join(
        f"        {ln}" for ln in (shrunk_seq or "(empty)").splitlines()
    )
    body = _FORGE_TEMPLATE.format(
        crash_id=crash_id,
        crash_id_short=crash_id_short,
        dedup_hash=dedup_hash,
        captured_at=captured_at,
        seed_determinism=seed_determinism,
        contract_id=contract_id,
        target=target,
        target_path=f"src/{target}.sol",
        sequence_block=seq_block,
        file_name=file_name,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(body)
    return out_path


# ---------------------------------------------------------------------------
# Summary rendering
# ---------------------------------------------------------------------------

def render_summary(state: dict[str, Any], out_dir: Path) -> Path:
    """Write summary.md. Honest non-finding for timeout/coverage_plateau.

    Returns the path written.
    """
    lc = state.get("lifecycle", "unknown")
    target = state.get("target", "?")
    profile = state.get("profile", "?")
    duration = state.get("duration", 0)
    budget_seconds = state.get("budget_seconds", duration)
    engine = state.get("engine", "?")
    crashes = state.get("crashes", [])
    shrunk = state.get("shrunk", [])
    forge_tests = state.get("forge_tests", [])
    started = state.get("started_at", "?")
    ended = state.get("ended_at", _utcnow_iso())
    notes = state.get("notes", [])

    if lc in ("timeout", "coverage_plateau"):
        verdict = (
            f"**Honest non-finding.** Status: `{lc}`. The campaign did not "
            f"produce a verified crash within the bounded duration "
            f"({duration}s elapsed, {budget_seconds}s budget). This is NOT "
            f"a clean bill of health — it means "
            f"this run's tooling did not surface a finding under these "
            f"settings. Re-run with longer --duration, broader --target, "
            f"or escalate to symbolic/medusa via tools/fuzz-runner.sh."
        )
    elif lc == "verified":
        verdict = (
            "**Verified replay scaffold generated.** A Forge replay test "
            "was produced from a shrunk crash. Operator must run it on the "
            "vulnerable + fixed commits; only the operator can promote a "
            "candidate to a finding."
        )
    elif lc == "rejected":
        verdict = (
            "**Rejected.** Crash was reproduced but did NOT survive "
            "operator gate (e.g. could not be made to fail on vulnerable "
            "version OR did not change behavior on fix)."
        )
    elif lc == "forge_test_generated":
        verdict = (
            "**Forge test generated; awaiting operator promotion gate.** "
            "Run the test on vulnerable + fixed commits to advance to "
            "`verified` or `rejected`."
        )
    else:
        verdict = f"In-flight or interrupted (lifecycle={lc})."

    lines = [
        f"# Fuzz campaign summary — {state.get('campaign_id', '?')}",
        "",
        f"- target: `{target}`",
        f"- profile: `{profile}`",
        f"- engine: `{engine}`",
        f"- elapsed duration: `{duration}s`",
        f"- duration cap: `{budget_seconds}s`",
        f"- started_at: `{started}`",
        f"- ended_at: `{ended}`",
        f"- lifecycle: `{lc}`",
        "",
        "## Verdict",
        "",
        verdict,
        "",
        "## Inventory of orchestrated tools",
        "",
        "- `tools/fuzz-runner.sh` (PR 107 bounded engine layer)",
        "- `forge test --invariant` / `--fuzz`",
        "- `tools/symbolic-ce-to-forge.py` (advisory, not run in this PR's "
        "first impl)",
        "- `tools/poc-scaffold.py` (advisory pattern templates)",
        "",
        "## Counts",
        "",
        f"- crashes: {len(crashes)}",
        f"- shrunk: {len(shrunk)}",
        f"- forge_tests: {len(forge_tests)}",
        "",
        "## Deferred to follow-up PR",
        "",
        "- Symbolic / Halmos / Medusa orchestration",
        "- Coverage-plateau detection from real coverage.json (today: heuristic)",
        "- Auto-promotion based on pre/post-fix replay (today: operator-driven)",
        "",
        "## Notes",
        "",
        *(f"- {n}" for n in notes),
        "",
    ]
    p = out_dir / "summary.md"
    p.write_text("\n".join(lines))
    return p


# ---------------------------------------------------------------------------
# Main campaign driver
# ---------------------------------------------------------------------------

def _seed_artifacts(out_dir: Path, target: str, profile: str,
                    duration: int, engine: str, campaign_id: str) -> None:
    """Create the empty artifact tree so partial runs are inspectable."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "crashes").mkdir(exist_ok=True)
    (out_dir / "shrunk").mkdir(exist_ok=True)
    (out_dir / "forge_tests").mkdir(exist_ok=True)

    config = {
        "campaign_id": campaign_id,
        "target": target,
        "profile": profile,
        "budget_seconds": duration,
        "engine": engine,
        "created_at": _utcnow_iso(),
        "schema_version": "fuzz_campaign.v1",
    }
    _atomic_write_json(out_dir / "config.json", config)
    # Honest-zero placeholder for coverage. Real coverage extraction is a
    # follow-up PR.
    _atomic_write_json(out_dir / "coverage.json", {
        "schema_version": "fuzz_coverage.v1",
        "engine": engine,
        "coverage": None,
        "note": "coverage extraction deferred to follow-up PR; honest-zero placeholder",
    })


def run_campaign(workspace: Path, target: str, profile: str,
                 duration: int, out_dir: Path, engine: str = "auto",
                 _runner_override: list[str] | None = None,
                 _stdout_override: str | None = None) -> dict[str, Any]:
    """End-to-end campaign driver.

    Test hooks:
      _runner_override   replaces the forge argv (subprocess still runs).
      _stdout_override   bypasses the engine entirely; the given text is
                         treated as forge stdout. status is inferred via
                         the same crash-marker logic. Used for hermetic
                         tests when forge is not on PATH.

    Returns the final state dict (also persisted to out_dir/summary.json).
    """
    if profile not in PROFILES:
        raise ValueError(f"invalid profile {profile!r}; expected one of {PROFILES}")
    if duration <= 0 or duration > DURATION_CAP_SECONDS:
        raise ValueError(
            f"duration must be in 1..{DURATION_CAP_SECONDS} (got {duration})"
        )
    if not workspace.is_dir():
        raise FileNotFoundError(f"workspace not found: {workspace}")

    campaign_id = out_dir.name
    replay_log = out_dir / "replay.log"

    # Engine selection. _stdout_override skips real engine.
    if _stdout_override is None:
        chosen_engine = discover_engine(workspace, engine)
    else:
        chosen_engine = "forge"  # fixture-only

    _seed_artifacts(out_dir, target, profile, duration, chosen_engine,
                    campaign_id)

    state: dict[str, Any] = {
        "campaign_id": campaign_id,
        "lifecycle": "created",
        "target": target,
        "profile": profile,
        "duration": 0,
        "budget_seconds": duration,
        "engine": chosen_engine,
        "started_at": _utcnow_iso(),
        "crashes": [],
        "shrunk": [],
        "forge_tests": [],
        "notes": [],
    }
    _append_replay(replay_log, "campaign-init", **{
        "campaign_id": campaign_id, "target": target, "profile": profile,
        "budget_seconds": duration, "engine": chosen_engine,
    })

    # created -> seeding
    transition(state, "seeding", replay_log)

    # seeding -> running
    transition(state, "running", replay_log)

    # Run engine
    if _stdout_override is not None:
        # Hermetic test path: classify the override stdout directly.
        crash_markers = bool(
            re.search(r"\b(FAIL|invariant.*failed|counterexample|panic|revert)\b",
                      _stdout_override, re.IGNORECASE)
        )
        # Persist the override as if forge wrote it — keeps artifact shape
        # identical to a real run.
        (out_dir / "forge.stdout.log").write_text(_stdout_override)
        (out_dir / "forge.stderr.log").write_text("")
        if "__SIM_TIMEOUT__" in _stdout_override:
            run_result = {
                "status": "timeout",
                "exit_code": 124,
                "stdout_path": str(out_dir / "forge.stdout.log"),
                "stderr_path": str(out_dir / "forge.stderr.log"),
                "duration_s": float(duration),
                "command": "(simulated)",
                "engine_version": "simulated",
            }
        elif crash_markers:
            run_result = {
                "status": "crash_found",
                "exit_code": 1,
                "stdout_path": str(out_dir / "forge.stdout.log"),
                "stderr_path": str(out_dir / "forge.stderr.log"),
                "duration_s": min(float(duration), 1.0),
                "command": "(simulated)",
                "engine_version": "simulated",
            }
        else:
            run_result = {
                "status": ("coverage_plateau" if duration >= 60 else "no_finding"),
                "exit_code": 0,
                "stdout_path": str(out_dir / "forge.stdout.log"),
                "stderr_path": str(out_dir / "forge.stderr.log"),
                "duration_s": min(float(duration), 1.0),
                "command": "(simulated)",
                "engine_version": "simulated",
            }
    else:
        run_result = run_forge_campaign(
            workspace, target, profile, duration, out_dir,
            _runner_override=_runner_override,
        )

    rstatus = run_result["status"]

    # Branch in lifecycle
    if rstatus == "timeout":
        transition(state, "timeout", replay_log,
                   reason="wall-clock cap reached",
                   duration_s=run_result["duration_s"])
        _finalize_runtime(state)
        state["notes"].append(
            "timeout: bounded budget exhausted with no crash. Honest "
            "non-finding — re-run with longer --duration or different "
            "--target to escalate."
        )
        _atomic_write_json(out_dir / "summary.json", state)
        render_summary(state, out_dir)
        return state

    if rstatus == "coverage_plateau":
        transition(state, "coverage_plateau", replay_log,
                   reason="forge passed clean under non-trivial budget",
                   duration_s=run_result["duration_s"])
        _finalize_runtime(state)
        state["notes"].append(
            "coverage_plateau: forge passed without producing a crash "
            "across {}s configured budget. NOT a clean-bill-of-health.".format(duration)
        )
        _atomic_write_json(out_dir / "summary.json", state)
        render_summary(state, out_dir)
        return state

    if rstatus == "no_finding":
        # Short bounded run with no crash and no plateau. We treat this as
        # rejected to honor the lifecycle's terminal-state contract.
        # (Lifecycle has no "no_finding" state.) Get there via
        # coverage_plateau honest classification + a note.
        transition(state, "coverage_plateau", replay_log,
                   reason="short clean run; reclassified as plateau",
                   duration_s=run_result["duration_s"])
        _finalize_runtime(state)
        state["notes"].append(
            "short run with no crash; reclassified to coverage_plateau "
            "to keep lifecycle honest. Increase --duration for confidence."
        )
        _atomic_write_json(out_dir / "summary.json", state)
        render_summary(state, out_dir)
        return state

    if rstatus != "crash_found":
        raise RuntimeError(f"unexpected run status: {rstatus!r}")

    # crash_found path
    transition(state, "crash_found", replay_log,
               exit_code=run_result["exit_code"],
               duration_s=run_result["duration_s"])

    stdout_text = (
        _stdout_override if _stdout_override is not None
        else (out_dir / "forge.stdout.log").read_text(errors="replace")
    )
    failing_seq = extract_failing_sequence(stdout_text)
    dedup = crash_dedup_hash(failing_seq) if failing_seq else "no-seq"
    crash_id = f"crash-{dedup}"
    crash_artifact = {
        "crash_id": crash_id,
        "dedup_hash": dedup,
        "raw_seq": failing_seq[:32_000],  # bound — log mass-flooded by big traces
        "exit_code": run_result["exit_code"],
        "duration_s": run_result["duration_s"],
        "captured_at": _utcnow_iso(),
        "engine": chosen_engine,
        "engine_version": run_result.get("engine_version", ""),
    }
    crash_path = out_dir / "crashes" / f"{crash_id}.json"
    _atomic_write_json(crash_path, crash_artifact)
    state["crashes"].append(crash_id)

    # crash_found -> shrinking
    transition(state, "shrinking", replay_log, crash_id=crash_id)
    shrunk = shrink_sequence(failing_seq)
    shrunk_artifact = {
        "crash_id": crash_id,
        "dedup_hash": dedup,
        "shrunk_at": _utcnow_iso(),
        **shrunk,
    }
    shrunk_path = out_dir / "shrunk" / f"{crash_id}.json"
    _atomic_write_json(shrunk_path, shrunk_artifact)
    state["shrunk"].append(crash_id)

    # shrinking -> forge_test_generated
    transition(state, "forge_test_generated", replay_log, crash_id=crash_id)
    forge_test_path = out_dir / "forge_tests" / f"Replay_{dedup}.t.sol"
    generate_forge_test(
        crash_id=crash_id,
        dedup_hash=dedup,
        target=target,
        shrunk_seq=shrunk["shrunk_seq"],
        seed_determinism=shrunk["seed_determinism"],
        captured_at=crash_artifact["captured_at"],
        out_path=forge_test_path,
    )
    state["forge_tests"].append(forge_test_path.name)

    # forge_test_generated is a PAUSE. The wrapper deliberately does NOT
    # auto-transition to verified/rejected — that requires running the
    # generated test against vulnerable + fixed commits, which the
    # operator owns. The summary.md records this gate explicitly.
    _finalize_runtime(state)
    state["notes"].append(
        "forge_test_generated reached. Operator must run the generated "
        "Replay_{}.t.sol on vulnerable + fixed commits to advance to "
        "verified|rejected.".format(dedup)
    )
    _atomic_write_json(out_dir / "summary.json", state)
    render_summary(state, out_dir)
    return state


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="fuzz-campaign",
        description=(
            "V5 fuzz-campaign wrapper. Orchestrates existing fuzz tooling "
            "(tools/fuzz-runner.sh, forge invariant, tools/symbolic-ce-to-forge.py, "
            "tools/poc-scaffold.py). Bounded campaign farm — NOT 'infinite "
            "fuzzers'."
        ),
    )
    p.add_argument("--workspace", required=True, type=Path,
                   help="Path to the audit workspace (foundry root).")
    p.add_argument("--target", required=True,
                   help="Contract name to fuzz (forge --match-contract).")
    p.add_argument("--profile", default="invariant", choices=PROFILES,
                   help="Fuzz profile (default: invariant).")
    p.add_argument("--duration", type=int, default=600,
                   help=f"Wall-clock cap in seconds (max {DURATION_CAP_SECONDS}).")
    p.add_argument("--out", required=True, type=Path,
                   help="Campaign output dir, e.g. <ws>/fuzz_campaigns/<id>.")
    p.add_argument("--engine", default="auto", choices=("auto", "forge", "medusa", "echidna"),
                   help="Fuzz engine. PR 4 supports 'forge' only; "
                        "medusa/echidna deferred to follow-up.")
    p.add_argument("--list-tools", action="store_true",
                   help="Print the inventory of orchestrated tools and exit.")
    return p


_INVENTORY = (
    ("tools/fuzz-runner.sh",
     "PR 107 bounded medusa|echidna|auto runner with timeout + manifest."),
    ("forge test --invariant / --fuzz",
     "Foundry-native invariant + fuzz harnesses (PR 4 first-impl path)."),
    ("tools/gen-invariants.sh",
     "Class-aware Forge invariant harness scaffold generator."),
    ("tools/gen-composition-fuzz.sh",
     "R57 composition-invariant cross-contract harness generator."),
    ("tools/invariant-hunt.sh",
     "R61 contract→class→harness→symbolic+forge one-liner."),
    ("tools/invariant-validate.sh",
     "Run scaffolded Foundry invariant harnesses in CI."),
    ("tools/symbolic-ce-to-forge.py",
     "halmos counterexample → Forge replay scaffold (capv3 iter8-T3)."),
    ("tools/symbolic-runner.sh",
     "halmos | kontrol | auto symbolic slice."),
    ("tools/poc-scaffold.py",
     "Pattern-based PoC scaffold generator."),
    ("tools/poc-cowrite.sh",
     "R73 A4 PoC co-write helper."),
    ("tools/auto-poc-synth.py",
     "R76 G detector-hit → Foundry PoC scaffold synthesizer."),
    ("tools/audit-deep.sh",
     "Profile-driven deep audit aggregator (default/math/crypto/econ)."),
    ("tools/verify-pocs.sh",
     "Phase 42 PoC verification gate."),
    ("tools/k2-poc-scaffold.sh",
     "K2 PoC scaffold variant."),
)


def _print_inventory() -> None:
    print("# fuzz-campaign.py — orchestrated tool inventory")
    print()
    for path, desc in _INVENTORY:
        print(f"- `{path}` — {desc}")


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.list_tools:
        _print_inventory()
        return 0

    try:
        state = run_campaign(
            workspace=args.workspace.resolve(),
            target=args.target,
            profile=args.profile,
            duration=args.duration,
            out_dir=args.out.resolve(),
            engine=args.engine,
        )
    except (ValueError, FileNotFoundError, RuntimeError) as e:
        print(f"[fuzz-campaign] error: {e}", file=sys.stderr)
        return 2

    print(f"[fuzz-campaign] lifecycle={state['lifecycle']} out={args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
