#!/usr/bin/env bash
# install-memory-watcher-launchd.sh — T-17.
#
# Install the memory-event-watcher.py daemon via launchd (macOS) or
# systemd-user/cron (Linux).  Wraps install-pipeline-supervision.sh with
# the canonical label com.auditooor.memory-watcher.
#
# The watcher script is copied to /private/tmp/auditooor-memory-watcher/ to
# keep it out of TCC-protected ~/Documents paths on macOS.
#
# Usage:
#   bash tools/install-memory-watcher-launchd.sh [--vault-dir <dir>] [--config <yaml>]
#   bash tools/install-memory-watcher-launchd.sh --uninstall
#   bash tools/install-memory-watcher-launchd.sh --status
#
# Requires: python3 in PATH.  watchdog is recommended but optional
# (falls back to polling every 30 s when absent).
#
# Enable / disable without uninstalling:
#   launchctl unload ~/Library/LaunchAgents/com.auditooor.memory-watcher.plist
#   launchctl load   ~/Library/LaunchAgents/com.auditooor.memory-watcher.plist

set -uo pipefail

LABEL="com.auditooor.memory-watcher"
WORK_DIR="/private/tmp/auditooor-memory-watcher"
SCRIPT="$WORK_DIR/run-watcher.sh"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SUPERVISOR="$REPO_ROOT/tools/install-pipeline-supervision.sh"

# Defaults — can be overridden by flags
VAULT_DIR="$REPO_ROOT/obsidian-vault"
CONFIG_ARG=""
MODE="install"    # install | uninstall | status

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --vault-dir)  VAULT_DIR="$2"; shift 2 ;;
    --config)     CONFIG_ARG="--config $2"; shift 2 ;;
    --uninstall)  MODE="uninstall"; shift ;;
    --status)     MODE="status"; shift ;;
    -h|--help)
      grep '^#' "$0" | head -30 | sed 's/^# \?//'
      exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

# ---- STATUS ----
if [[ "$MODE" == "status" ]]; then
  echo "=== Memory-event-watcher status ==="
  PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
  if [[ -f "$PLIST" ]]; then
    echo "[OK] plist present: $PLIST"
  else
    echo "[--] plist absent (not installed)"
  fi
  echo ""
  echo "launchctl list:"
  launchctl list 2>/dev/null | grep "$LABEL" || echo "  (not loaded)"
  echo ""
  STDOUT_LOG="$WORK_DIR/run-watcher.launchd.log"
  STDERR_LOG="$WORK_DIR/run-watcher.launchd.err"
  if [[ -f "$STDOUT_LOG" ]]; then
    echo "Last 10 lines of stdout log:"
    tail -10 "$STDOUT_LOG"
  fi
  if [[ -f "$STDERR_LOG" ]]; then
    echo "Last 10 lines of stderr log:"
    tail -10 "$STDERR_LOG"
  fi
  exit 0
fi

# ---- UNINSTALL ----
if [[ "$MODE" == "uninstall" ]]; then
  PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
  if [[ -f "$PLIST" ]]; then
    launchctl unload "$PLIST" 2>/dev/null || true
    rm -f "$PLIST"
    echo "[uninstall] plist removed: $PLIST"
  else
    echo "[uninstall] nothing to remove (plist not found)"
  fi
  exit 0
fi

# ---- INSTALL ----
# Validate prereqs
if ! command -v python3 >/dev/null 2>&1; then
  echo "[install] ERROR: python3 not found in PATH" >&2
  exit 1
fi

if [[ ! -f "$SUPERVISOR" ]]; then
  echo "[install] ERROR: install-pipeline-supervision.sh not found at $SUPERVISOR" >&2
  exit 1
fi

WATCHER_SRC="$REPO_ROOT/tools/memory-event-watcher.py"
if [[ ! -f "$WATCHER_SRC" ]]; then
  echo "[install] ERROR: memory-event-watcher.py not found at $WATCHER_SRC" >&2
  exit 1
fi

# Inform about watchdog
if ! python3 -c "import watchdog" 2>/dev/null; then
  echo "[install] WARN: watchdog not installed — watcher will use polling fallback (30s)."
  echo "[install] For fsevents: pip install watchdog"
fi

# Set up work dir with copies
mkdir -p "$WORK_DIR"
cp -f "$WATCHER_SRC" "$WORK_DIR/memory-event-watcher.py"

# Write runner script (what launchd actually executes — keeps log paths tidy)
cat > "$SCRIPT" <<SHELL
#!/usr/bin/env bash
# Auto-generated by install-memory-watcher-launchd.sh — do not edit manually.
# Re-run: bash $REPO_ROOT/tools/install-memory-watcher-launchd.sh

set -uo pipefail
exec python3 "$WORK_DIR/memory-event-watcher.py" \\
  --vault-dir "$VAULT_DIR" \\
  $CONFIG_ARG
SHELL
chmod +x "$SCRIPT"

echo "[install] Runner script: $SCRIPT"
echo "[install] Vault dir:     $VAULT_DIR"
echo "[install] Label:         $LABEL"

# Delegate to the shared supervisor script (handles launchd / systemd / cron)
bash "$SUPERVISOR" \
  --label "$LABEL" \
  --script "$SCRIPT" \
  --interval 3600

# Note: the memory watcher is a *daemon* (runs continuously), not a periodic
# job.  The --interval here is the restart delay if the daemon exits
# unexpectedly.  launchd's KeepAlive=true would be more accurate for a daemon,
# but install-pipeline-supervision.sh uses StartInterval for restart semantics.
# For production use, set KeepAlive manually in the plist:
#   <key>KeepAlive</key><true/>
# and remove <key>StartInterval</key>.

echo ""
echo "=== Install complete ==="
echo "  Enable:  launchctl load   ~/Library/LaunchAgents/${LABEL}.plist"
echo "  Disable: launchctl unload ~/Library/LaunchAgents/${LABEL}.plist"
echo "  Status:  bash tools/install-memory-watcher-launchd.sh --status"
echo "  Logs:    tail $WORK_DIR/run-watcher.launchd.log"
