#!/usr/bin/env bash
# invariant-monitor.sh — live invariant monitoring stub (U9, R43 roadmap).
#
# Full roadmap goal: for every deployed contract in scope, track N key
# invariants continuously (via The Graph / custom indexer) and auto-triage
# breaks as live findings.
#
# This stub ships the foundation: a YAML registry of invariants per workspace
# and a `cast`-backed runner. Indexer / webhook / subgraph wiring is left
# for a future iteration.
#
# Each invariant is a record:
#   name:          short stable slug (e.g. OFF.A-prevention)
#   contract:      deployed address (0x…) the check targets
#   expression:    a `cast call` command-line (no leading `cast`) whose
#                  stdout is compared against `expected`
#   expected:      literal string the cast output must equal (or != if
#                  expected starts with "!=")
#   severity:      label applied when the invariant breaks (Critical / High / …)
#   note:          free-form rationale
#
# Usage:
#   ./tools/invariant-monitor.sh <ws> check
#   ./tools/invariant-monitor.sh <ws> define <contract> <name> <cast-expr> <expected> <severity> [note]
#   ./tools/invariant-monitor.sh <ws> run [--rpc-url URL]
#
# Exit codes:
#   0 — all invariants hold (or no invariants defined)
#   1 — at least one invariant broken — see monitoring/broken_invariants_<ts>.log
#   2 — usage / config error

set -u

WS="${1:-}"
MODE="${2:-}"
shift 2 2>/dev/null || true

if [ -z "$WS" ] || [ -z "$MODE" ]; then
  echo "usage: $0 <workspace> {check|define|run} [...]" >&2
  exit 2
fi

if [ ! -d "$WS" ]; then
  echo "[invariant-monitor] workspace not found: $WS" >&2
  exit 2
fi

MON_DIR="$WS/monitoring"
INV_FILE="$MON_DIR/invariants.yaml"

seed_header() {
  mkdir -p "$MON_DIR"
  if [ ! -f "$INV_FILE" ]; then
    cat > "$INV_FILE" <<EOF
# invariants.yaml — live invariant registry for workspace $(basename "$WS")
# Generated by tools/invariant-monitor.sh
# Each entry is executed by \`cast call\` against --rpc-url at \`run\` time.
# A break is logged to monitoring/broken_invariants_<ts>.log with the declared severity.
invariants: []
EOF
  fi
}

case "$MODE" in
  check)
    if [ ! -f "$INV_FILE" ]; then
      echo "[invariant-monitor] no invariants defined yet ($INV_FILE missing)"
      exit 0
    fi
    echo "[invariant-monitor] registry: $INV_FILE"
    echo
    # Parse simple YAML list — expects one entry per "- name:" block.
    awk '
      /^[[:space:]]*-[[:space:]]*name:/ { idx++; printf "\n[%d] %s\n", idx, $0; next }
      /^[[:space:]]*(contract|expression|expected|severity|note):/ { print "    " $0 }
    ' "$INV_FILE"
    COUNT=$(grep -cE '^[[:space:]]*-[[:space:]]*name:' "$INV_FILE" 2>/dev/null || echo 0)
    echo
    echo "[invariant-monitor] total invariants: $COUNT"
    exit 0
    ;;

  define)
    # R45 bugfix (Bug 3): parse optional --allow-zero before positionals
    ALLOW_ZERO=0
    DEFINE_ARGS=()
    while [ $# -gt 0 ]; do
      case "$1" in
        --allow-zero) ALLOW_ZERO=1; shift ;;
        *) DEFINE_ARGS+=("$1"); shift ;;
      esac
    done
    set -- "${DEFINE_ARGS[@]}"

    CONTRACT="${1:-}"
    NAME="${2:-}"
    EXPR="${3:-}"
    EXPECTED="${4:-}"
    SEVERITY="${5:-Medium}"
    NOTE="${6:-}"
    if [ -z "$CONTRACT" ] || [ -z "$NAME" ] || [ -z "$EXPR" ] || [ -z "$EXPECTED" ]; then
      echo "usage: $0 <ws> define <contract> <name> <cast-expr> <expected> [severity] [note] [--allow-zero]" >&2
      exit 2
    fi

    # R45 bugfix (Bug 3): reject non-hex / wrong-length addresses.
    # Previously accepted 0x0…0 and random strings, leading to silent cast
    # failures at run time.
    if ! [[ "$CONTRACT" =~ ^0x[a-fA-F0-9]{40}$ ]]; then
      echo "[invariant-monitor] invalid contract address: '$CONTRACT' (must match ^0x[a-fA-F0-9]{40}$)" >&2
      exit 2
    fi
    # Reject address(0) unless operator explicitly opts in.
    if [ "$ALLOW_ZERO" != "1" ] && [[ "$CONTRACT" =~ ^0x0{40}$ ]]; then
      echo "[invariant-monitor] refusing to register invariant on address(0). Pass --allow-zero to override." >&2
      exit 2
    fi
    seed_header
    {
      echo ""
      echo "  - name: $NAME"
      echo "    contract: $CONTRACT"
      echo "    expression: \"$EXPR\""
      echo "    expected: \"$EXPECTED\""
      echo "    severity: $SEVERITY"
      [ -n "$NOTE" ] && echo "    note: \"$NOTE\""
    } >> "$INV_FILE"
    # If this is the first entry, replace the "invariants: []" stub.
    if grep -q '^invariants: \[\]' "$INV_FILE"; then
      # rewrite: strip the `[]` off so downstream parsers see a real list
      sed -i.bak 's/^invariants: \[\]/invariants:/' "$INV_FILE" && rm -f "$INV_FILE.bak"
    fi
    echo "[invariant-monitor] defined $NAME on $CONTRACT (severity=$SEVERITY)"
    exit 0
    ;;

  run)
    RPC_URL="${RPC_URL:-}"
    while [ $# -gt 0 ]; do
      case "$1" in
        --rpc-url) RPC_URL="$2"; shift 2 ;;
        *) shift ;;
      esac
    done
    if [ ! -f "$INV_FILE" ]; then
      echo "[invariant-monitor] no invariants defined — nothing to run"
      exit 0
    fi
    if ! command -v cast >/dev/null 2>&1; then
      echo "[invariant-monitor] cast not found on PATH — install foundry (https://getfoundry.sh)"
      echo "[invariant-monitor] SKIPPING run (foundation stub — no-op)"
      exit 0
    fi
    if [ -z "$RPC_URL" ]; then
      echo "[invariant-monitor] no RPC URL (pass --rpc-url or set RPC_URL env)"
      echo "[invariant-monitor] SKIPPING run (foundation stub — no-op)"
      exit 0
    fi

    TS=$(date -u +%Y%m%dT%H%M%SZ)
    BROKEN_LOG="$MON_DIR/broken_invariants_${TS}.log"
    TOTAL=0
    BROKEN=0

    # Extract entries. Expected format: blocks of 4-6 indented lines per "- name:".
    # Tiny hand-rolled parser keyed to what `define` emits.
    python3 - "$INV_FILE" "$RPC_URL" "$BROKEN_LOG" <<'PY' || EXIT_RC=$?
import sys, re, subprocess, os

inv_file, rpc_url, broken_log = sys.argv[1], sys.argv[2], sys.argv[3]

entries = []
cur = None
with open(inv_file) as f:
    for line in f:
        m = re.match(r"\s*-\s*name:\s*(\S.*)", line)
        if m:
            if cur: entries.append(cur)
            cur = {"name": m.group(1).strip().strip('"')}
            continue
        if cur is None: continue
        for key in ("contract", "expression", "expected", "severity", "note"):
            m = re.match(rf"\s*{key}:\s*(.*)", line)
            if m:
                val = m.group(1).strip()
                if val.startswith('"') and val.endswith('"'):
                    val = val[1:-1]
                cur[key] = val
                break
if cur: entries.append(cur)

print(f"[invariant-monitor] running {len(entries)} invariant(s) against {rpc_url}")
broken = []
for e in entries:
    name = e.get("name", "?")
    expr = e.get("expression", "")
    expected = e.get("expected", "")
    sev = e.get("severity", "Medium")
    contract = e.get("contract", "")
    # Build: cast call <contract> <expr…>
    # `expression` is the argv after `cast call <contract>` — e.g. 'hasAnyRole(address,uint256)(bool) 0x… 1'
    cmd = ["cast", "call", contract] + expr.split() + ["--rpc-url", rpc_url]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        stdout = (out.stdout or "").strip()
        stderr = (out.stderr or "").strip()
        if out.returncode != 0:
            print(f"  [ERR ] {name}: cast failed rc={out.returncode}: {stderr[:200]}")
            broken.append((name, sev, contract, f"cast rc={out.returncode}: {stderr[:200]}"))
            continue
        negate = expected.startswith("!=")
        want = expected[2:].strip() if negate else expected
        ok = (stdout != want) if negate else (stdout == want)
        if ok:
            print(f"  [PASS] {name} -> {stdout}")
        else:
            op = "!=" if negate else "=="
            msg = f"got {stdout!r}, expected {op} {want!r}"
            print(f"  [FAIL] {name} [{sev}]: {msg}")
            broken.append((name, sev, contract, msg))
    except Exception as ex:
        print(f"  [ERR ] {name}: {ex}")
        broken.append((name, sev, contract, f"exception: {ex}"))

if broken:
    with open(broken_log, "w") as f:
        f.write(f"# Broken invariants ({len(broken)})\n\n")
        for name, sev, contract, msg in broken:
            f.write(f"- [{sev}] {name} @ {contract}\n  {msg}\n\n")
    print(f"[invariant-monitor] {len(broken)} broken — wrote {broken_log}")
    sys.exit(1)

print("[invariant-monitor] all invariants hold")
sys.exit(0)
PY
    exit "${EXIT_RC:-0}"
    ;;

  *)
    echo "usage: $0 <workspace> {check|define|run} [...]" >&2
    exit 2
    ;;
esac
