#!/usr/bin/env python3
"""ledger-summary.py — compact rollup of docs/archive/R94_LOOP_LEDGER.md

The R94 loop ledger has ~125 cycle entries and grows with every mining round.
Scrolling 125k of markdown to answer "what topics have we mined?" is
painful. This script parses the cycle headers and emits a per-topic / per-
cycle rollup.

Output goes to `docs/LEDGER_SUMMARY.md` (overwritten on each run).

Part of Phase 3 of the consolidation megaplan (PR #84).
"""
from __future__ import annotations

import re
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LEDGER = REPO / "docs" / "R94_LOOP_LEDGER.md"
OUT = REPO / "docs" / "LEDGER_SUMMARY.md"

CYCLE_RE = re.compile(r"^##\s+Cycle\s+(\d+)\s+—\s+([\d\-]+).*?$", re.M)
TOPIC_RE = re.compile(r"corpus\s+([^()\n]+?)(?:\s+(?:HIGHs|corpus|findings|exploit|2026|\())", re.I)
PARITY_RE = re.compile(r"\*\*Parity:\*\*\s+[^→]+→\s+\*\*([\d.]+)%\*\*")
RUST_RE = re.compile(r"\*\*Rust detectors:\*\*\s+[\d]+\s+→\s+\*\*([\d]+)\*\*|\*\*Rust:\*\*\s+[\d]+\s+→\s+\*\*([\d]+)\*\*")
SOL_RE = re.compile(r"\*\*Solidity active patterns:\*\*\s+[\d]+\s+→\s+\*\*([\d]+)\*\*|\*\*Sol:\*\*\s+[\d]+\s+→\s+\*\*([\d]+)\*\*")
FIXTURES_RE = re.compile(r"\*\*Fixtures:\*\*\s+[\d/]+\s+→\s+\*\*([\d/]+)\*\*")


def topic_of(section: str) -> str:
    """Heuristic topic extraction from a cycle section body."""
    # Look for the MINE row description
    for line in section.splitlines()[:50]:
        m = re.search(r"Solodit\s+([a-zA-Z\-/\s]+?)\s+(?:HIGHs|corpus|findings)", line)
        if m:
            return m.group(1).strip().rstrip(',').rstrip(".").lower()
        m = re.search(r"MINE\s+\|\s+([^|]+?)\s+(?:HIGHs|findings|corpus)", line)
        if m:
            return m.group(1).strip().lower()
        m = re.search(r"Kelp\s+rsETH", line)
        if m:
            return "kelp rseth (layerzero oft)"
        m = re.search(r"CEILING-RAISE\s+\|\s+\+\d+\s+([\w\-/\s]+?)(?:classes|class)", line)
        if m:
            return m.group(1).strip().rstrip(',').lower()
    return "(no topic extracted)"


def main() -> int:
    if not LEDGER.exists():
        print(f"[err] {LEDGER} not found")
        return 1

    text = LEDGER.read_text()
    # Split into cycle sections
    sections = []
    matches = list(CYCLE_RE.finditer(text))
    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        sections.append((int(m.group(1)), m.group(2), text[start:end]))

    if not sections:
        print("[err] no cycles parsed — check ledger format")
        return 1

    # Per-topic rollup
    topic_cycles: dict[str, list[int]] = defaultdict(list)
    per_cycle = []
    for cyc, date, body in sections:
        topic = topic_of(body)
        topic_cycles[topic].append(cyc)
        pm = PARITY_RE.search(body)
        parity = pm.group(1) if pm else "?"
        rm = RUST_RE.search(body)
        rust = next((g for g in rm.groups() if g), "?") if rm else "?"
        sm = SOL_RE.search(body)
        sol = next((g for g in sm.groups() if g), "?") if sm else "?"
        fm = FIXTURES_RE.search(body)
        fixtures = fm.group(1) if fm else "?"
        per_cycle.append((cyc, date, topic, parity, rust, sol, fixtures))

    # Current state from latest cycle
    last = per_cycle[-1]
    latest_cycle, latest_date, latest_topic, latest_parity, latest_rust, latest_sol, latest_fixtures = last

    # Commit SHA snapshot
    try:
        sha = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=REPO,
            stderr=subprocess.DEVNULL,
        ).decode().strip()
    except subprocess.CalledProcessError:
        sha = "(unknown)"

    # Write output
    out = []
    out.append("# R94 Loop Ledger — Summary")
    out.append("")
    out.append(f"Auto-generated by `tools/ledger-summary.py`. "
               f"Source: `docs/archive/R94_LOOP_LEDGER.md` ({LEDGER.stat().st_size // 1024} KB, "
               f"{len(sections)} cycles).")
    out.append("")
    out.append("## Current state")
    out.append("")
    out.append(f"- **Latest cycle:** {latest_cycle} ({latest_date})")
    out.append(f"- **Parity:** {latest_parity}%")
    out.append(f"- **Rust detectors:** {latest_rust}")
    out.append(f"- **Solidity active patterns:** {latest_sol}")
    out.append(f"- **Fixtures:** {latest_fixtures}")
    out.append(f"- **Commit:** `{sha}`")
    out.append("")

    out.append("## Topic → cycles covered")
    out.append("")
    out.append("| Topic | Cycle count | Cycles |")
    out.append("|---|---:|---|")
    for topic, cycs in sorted(topic_cycles.items(), key=lambda x: (-len(x[1]), x[0])):
        compact = ", ".join(str(c) for c in sorted(cycs))
        if len(compact) > 60:
            compact = f"{min(cycs)}...{max(cycs)} ({len(cycs)} cycles)"
        safe_topic = topic.replace("|", "\\|")[:80]
        out.append(f"| {safe_topic} | {len(cycs)} | {compact} |")
    out.append("")

    out.append("## Latest 20 cycles")
    out.append("")
    out.append("| Cycle | Date | Topic | Parity | Rust | Sol | Fixtures |")
    out.append("|---:|---|---|---|---:|---:|---|")
    for row in per_cycle[-20:]:
        cyc, date, topic, parity, rust, sol, fixtures = row
        safe_topic = topic.replace("|", "\\|")[:50]
        out.append(f"| {cyc} | {date} | {safe_topic} | {parity}% | {rust} | {sol} | {fixtures} |")
    out.append("")

    OUT.write_text("\n".join(out) + "\n")
    print(f"[ok] wrote {OUT.relative_to(REPO)}")
    print(f"     cycles: {len(sections)}")
    print(f"     topics: {len(topic_cycles)}")
    print(f"     latest: cycle {latest_cycle} @ {latest_parity}% parity "
          f"({latest_rust} rust / {latest_sol} sol)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
