#!/usr/bin/env bash
# monitor-cron.sh — schedule invariant-monitor on cron (U9, R46).
#
# Generates a workspace-local cron wrapper and prints a crontab line for the
# operator to install manually. We deliberately don't touch the user's crontab
# — printing the line keeps the install step auditable.
#
# Usage:
#   ./tools/monitor-cron.sh setup <ws> <interval-minutes> <rpc-url> [--alert-email <email>]
#
# Produces:
#   <ws>/monitoring/cron_wrapper.sh  — runs invariant-monitor --batch;
#                                       on FAIL, appends to alerts.log and,
#                                       if --alert-email given and `mail` is
#                                       installed, emails the operator.
#   stdout: a crontab line the operator can paste into `crontab -e`.

set -u

MODE="${1:-}"
if [ "$MODE" != "setup" ]; then
  echo "usage: $0 setup <ws> <interval-minutes> <rpc-url> [--alert-email <email>]" >&2
  exit 2
fi
shift

WS="${1:-}"
INTERVAL="${2:-}"
RPC_URL="${3:-}"
shift 3 2>/dev/null || true

ALERT_EMAIL=""
while [ $# -gt 0 ]; do
  case "$1" in
    --alert-email) ALERT_EMAIL="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [ -z "$WS" ] || [ -z "$INTERVAL" ] || [ -z "$RPC_URL" ]; then
  echo "usage: $0 setup <ws> <interval-minutes> <rpc-url> [--alert-email <email>]" >&2
  exit 2
fi

if [ ! -d "$WS" ]; then
  echo "[monitor-cron] workspace not found: $WS" >&2
  exit 2
fi

# Validate interval is a positive integer.
if ! [[ "$INTERVAL" =~ ^[0-9]+$ ]] || [ "$INTERVAL" -le 0 ]; then
  echo "[monitor-cron] interval must be a positive integer (minutes)" >&2
  exit 2
fi

# Resolve absolute paths so the cron wrapper is invariant to cwd.
ABS_WS=$(cd "$WS" && pwd)
# Assume this script lives next to invariant-monitor.sh in tools/.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
INV_MON="$SCRIPT_DIR/invariant-monitor.sh"

if [ ! -x "$INV_MON" ]; then
  echo "[monitor-cron] invariant-monitor.sh not found or not executable at $INV_MON" >&2
  exit 2
fi

MON_DIR="$ABS_WS/monitoring"
WRAPPER="$MON_DIR/cron_wrapper.sh"
ALERTS_LOG="$MON_DIR/alerts.log"
RUN_LOG="$MON_DIR/cron_last_run.log"
mkdir -p "$MON_DIR"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# cron_wrapper.sh — generated by tools/monitor-cron.sh for workspace $(basename "$ABS_WS")
# Runs invariant-monitor --batch and routes failures to alerts.log / optional email.
set -u

WS="$ABS_WS"
RPC_URL="$RPC_URL"
INV_MON="$INV_MON"
ALERTS_LOG="$ALERTS_LOG"
RUN_LOG="$RUN_LOG"
ALERT_EMAIL="$ALERT_EMAIL"

TS=\$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Capture full run output for the alert payload.
OUTPUT=\$("\$INV_MON" "\$WS" run --batch --rpc-url "\$RPC_URL" 2>&1)
RC=\$?

# Always overwrite the last-run log (bounded cost, easy to tail).
{
  echo "# invariant-monitor cron run \$TS (rc=\$RC)"
  echo "\$OUTPUT"
} > "\$RUN_LOG"

if [ "\$RC" -ne 0 ]; then
  {
    echo "=== ALERT \$TS (rc=\$RC) ==="
    echo "\$OUTPUT"
    echo
  } >> "\$ALERTS_LOG"

  if [ -n "\$ALERT_EMAIL" ] && command -v mail >/dev/null 2>&1; then
    SUBJECT="[invariant-monitor] FAIL rc=\$RC on \$(basename "\$WS") at \$TS"
    printf '%s\n' "\$OUTPUT" | mail -s "\$SUBJECT" "\$ALERT_EMAIL" || true
  fi
fi

exit \$RC
EOF

chmod +x "$WRAPPER"

# Build a crontab line that runs every $INTERVAL minutes.
# */N works cleanly only for N that evenly divide 60; otherwise cron would
# reset alignment every hour. Fall back to an hourly cadence hint when N>60.
if [ "$INTERVAL" -le 59 ] && [ $((60 % INTERVAL)) -eq 0 ]; then
  CRON_SPEC="*/$INTERVAL * * * *"
elif [ "$INTERVAL" -eq 60 ]; then
  CRON_SPEC="0 * * * *"
elif [ $((INTERVAL % 60)) -eq 0 ]; then
  HOURS=$((INTERVAL / 60))
  if [ "$HOURS" -le 23 ] && [ $((24 % HOURS)) -eq 0 ]; then
    CRON_SPEC="0 */$HOURS * * *"
  else
    CRON_SPEC="0 * * * *  # interval=$INTERVAL min does not divide evenly; adjust manually"
  fi
else
  CRON_SPEC="*/$INTERVAL * * * *  # interval=$INTERVAL does not divide 60; cron will reset alignment hourly"
fi

CRON_LINE="$CRON_SPEC $WRAPPER >> $MON_DIR/cron.stdout.log 2>&1"

echo "[monitor-cron] wrapper: $WRAPPER"
echo "[monitor-cron] alerts:  $ALERTS_LOG"
echo "[monitor-cron] last-run: $RUN_LOG"
if [ -n "$ALERT_EMAIL" ]; then
  echo "[monitor-cron] alert-email: $ALERT_EMAIL (requires \`mail\` on PATH)"
fi
echo
echo "Install the crontab line (run \`crontab -e\` and paste):"
echo
echo "  $CRON_LINE"
echo

exit 0
