#!/usr/bin/env bash
# orient-from-audits.sh — extract "operational considerations" / "known issues" / "by design" notes from prior audit texts
#
# Usage:
#   ./tools/orient-from-audits.sh <workspace-dir>
#
# Run once on iter 1. Generates workspace/PRIOR_CONCERNS.md from the audit .txt files
# pre-extracted to /tmp/ (via extract-pdfs.sh). Every line that looks like an operational
# consideration, known issue, non-exploit acknowledgement, or by-design note is captured
# so the skill can surface them during orient without re-reading full audit PDFs.
#
# Fixes Issue 13 from SKILL_ISSUES.md — external-intel integration on iter 1, not iter 14.

set -uo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <workspace-dir>"
    exit 1
fi

WS="$1"
if [ ! -d "$WS" ]; then
    echo "Error: workspace $WS not found"
    exit 1
fi

OUT="$WS/PRIOR_CONCERNS.md"

mkdir -p "$WS/prior_audits"

# Collect all audit text files. Primary: $WS/prior_audits/*.{txt,md} (durable,
# from in-repo audits/*.pdf via fetch-targets.sh, or curated DIGEST_*.md).
# Fallback: /tmp (ad-hoc).
collect_sources() {
    SOURCES=()
    if [ -d "$WS/prior_audits" ]; then
        for f in "$WS/prior_audits"/*.txt "$WS/prior_audits"/*.md; do
            [ -f "$f" ] && SOURCES+=("$f")
        done
    fi
    for pat in "/tmp/cantina_*.txt" "/tmp/quantstamp_*.txt" "/tmp/audit_*.txt" "/tmp/openzeppelin_*.txt" "/tmp/chainsecurity_*.txt" "/tmp/oz_*.txt"; do
        for f in $pat; do
            [ -f "$f" ] && SOURCES+=("$f")
        done
    done
}

collect_sources

# If still empty, try auto-extracting in-repo audit PDFs (lib/**/audit*/*.pdf).
# Gracefully skip if pdftotext is missing.
if [ ${#SOURCES[@]} -eq 0 ]; then
    if command -v pdftotext >/dev/null 2>&1; then
        # Portable to bash 3.2 (macOS): use a temp file instead of mapfile.
        PDF_LIST="$(mktemp)"
        find "$WS" -maxdepth 6 \( -path '*/lib/*' -o -path '*/audits/*' -o -path '*/audit/*' \) -iname '*.pdf' 2>/dev/null | head -10 > "$PDF_LIST"
        PDF_COUNT=$(wc -l < "$PDF_LIST" | tr -d ' ')
        if [ "$PDF_COUNT" -gt 0 ]; then
            echo "[orient] prior_audits/ empty — auto-extracting $PDF_COUNT in-repo audit PDF(s) via pdftotext..."
            while IFS= read -r pdf; do
                [ -z "$pdf" ] && continue
                base=$(basename "$pdf" .pdf | tr ' /' '__')
                out="$WS/prior_audits/${base}.txt"
                pdftotext -layout "$pdf" "$out" 2>/dev/null && echo "  + $out"
            done < "$PDF_LIST"
            collect_sources
        fi
        rm -f "$PDF_LIST"
    else
        echo "[orient] pdftotext not installed; skipping PDF auto-extract."
    fi
fi

# If STILL no sources, write a minimal PRIOR_CONCERNS.md and exit rc=0
# so downstream gates (agent-dispatch-enforced.sh, pre-iter-check.sh) don't cascade.
if [ ${#SOURCES[@]} -eq 0 ]; then
    cat > "$OUT" <<EOF
# Prior Audit Concerns — auto-generated (MINIMAL)

Generated by \`tools/orient-from-audits.sh\` at $(date -u +%Y-%m-%dT%H:%M:%SZ).

**No prior_audits/ content found** (no \`.txt\`, no \`.md\`, no extractable in-repo
audit PDFs). Proceed with first-principles review. Re-run this script after
populating \`$WS/prior_audits/\` with audit reports (\`.txt\`/\`.md\`) or after
adding in-repo audit PDFs that \`pdftotext\` can extract.

---

**How to use this file during orient:** there are no acknowledged prior concerns
to avoid re-litigating. Treat every plausible bug class as in-scope.
EOF
    echo "[orient] No audit sources available. Wrote minimal $OUT (rc=0)."
    exit 0
fi

# Patterns worth surfacing — phrases that usually indicate "this was considered and accepted"
# (hence is often the exact class a bounty submission needs to NOT re-litigate)
PATTERNS='(operational [Cc]onsider|[Bb]y [Dd]esign|[Rr]isk [Aa]ccepted|[Kk]nown [Ii]ssue|[Nn]ot a [Bb]ug|[Ww]ill not [Ff]ix|[Aa]cknowledged|[Ss]tale [Ss]tate|[Aa]ssumption|trusted to|non-exploitable|not exploitable|cannot be exploited|intended behavior|[Dd]esign [Dd]ecision|[Dd]esign [Rr]evision)'

{
    echo "# Prior Audit Concerns — auto-generated"
    echo ""
    echo "Generated by \`tools/orient-from-audits.sh\` at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo ""
    echo "Every line below is from a prior audit report and expresses an ACKNOWLEDGED concern,"
    echo "by-design decision, or operational caveat. These represent the exact classes a bounty"
    echo "submission should NOT re-litigate without a novel angle. Read this file during orient."
    echo ""
    echo "---"
    echo ""

    for src in "${SOURCES[@]}"; do
        name=$(basename "$src")
        echo "## \`$name\`"
        echo ""
        # Grep lines matching the patterns + 2 lines of context before/after
        # Dedupe consecutive duplicates with awk.
        grep -nE "$PATTERNS" "$src" 2>/dev/null \
            | awk '!seen[$0]++' \
            | head -80 \
            | sed 's/^/- L/'
        echo ""
    done

    echo "---"
    echo ""
    echo "**How to use this file during orient:** for every finding candidate you consider,"
    echo "grep this file for the relevant contract/function name. If a prior audit already"
    echo "acknowledged the concern as by-design, your submission needs a novel angle — re-"
    echo "litigating the exact acknowledged concern will be closed as dupe."
} > "$OUT"

echo "Generated $OUT from ${#SOURCES[@]} source files:"
for s in "${SOURCES[@]}"; do echo "  - $s"; done
wc -l "$OUT" | awk '{print "Total lines:", $1}'
