#!/usr/bin/env bash
# provision-deep-engines.sh - Hermetic deep-engine provisioning for the
# auditooor toolchain.
#
# Installs PINNED versions of the three dynamic-analysis engines into
# tools/deep-engine-bin/ so the runners (halmos-runner.sh / medusa-fuzz.sh /
# echidna-campaign.sh) can find and execute them. Until this script runs,
# the runners keep skipping gracefully (tool-unavailable artifact, exit 0).
#
#   halmos  - symbolic execution      (pip install into a private venv)
#   medusa  - call-sequence fuzzing   (GitHub release binary)
#   echidna - property fuzzing        (GitHub release binary)
#
# Usage:
#   tools/provision-deep-engines.sh [--engine halmos|medusa|echidna|all]
#                                   [--check]
#
#   --check : print resolution status for every engine and exit. Never
#             touches the network. Used by the provisioning-check test.
#
# Network is required only for an actual install. --check is offline-safe.
# The script is idempotent: an engine already present at the pinned
# version is left untouched.
#
# Exit codes:
#   0  all requested engines provisioned (or --check ran)
#   1  a usage / argument error
#   2  one or more installs failed (network, platform, checksum)

set -uo pipefail

# ---- pinned versions -------------------------------------------------------
# Bump deliberately; the runners record the resolved --version in their
# artifact JSON so a drift is always visible downstream.
HALMOS_VERSION="0.3.3"     # pip; verified against forge 1.5.1 (W5-D1)
MEDUSA_VERSION="1.5.1"     # crytic/medusa release tag (no leading 'v')
ECHIDNA_VERSION="2.3.2"    # crytic/echidna release tag (no leading 'v')

# ---- layout ----------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$SCRIPT_DIR"
BIN_DIR="${AUDITOOOR_DEEP_BIN_DIR:-$TOOLS_DIR/deep-engine-bin}"
VENV_DIR="$BIN_DIR/.halmos-venv"
WORK_DIR=""

cleanup() { [ -n "$WORK_DIR" ] && rm -rf "$WORK_DIR"; }
trap cleanup EXIT

log()  { echo "[provision-deep-engines] $*" >&2; }
fail() { log "ERROR: $*"; exit 2; }
# warn() is the offline-safe sibling of fail(): it reports and returns
# non-zero WITHOUT exiting, so an absent toolchain / dead network in the
# Rust/Go blocks degrades gracefully instead of aborting the whole run.
warn() { log "WARN: $*"; return 1; }

# ---- platform detection ----------------------------------------------------
detect_platform() {
    local os arch
    os="$(uname -s)"
    arch="$(uname -m)"
    case "$os" in
        Linux)  PLATFORM_OS="linux" ;;
        Darwin) PLATFORM_OS="macos" ;;
        *)      PLATFORM_OS="unknown" ;;
    esac
    case "$arch" in
        x86_64|amd64)  PLATFORM_ARCH="x64" ;;
        arm64|aarch64) PLATFORM_ARCH="arm64" ;;
        *)             PLATFORM_ARCH="unknown" ;;
    esac
}

# ---- check mode (offline) --------------------------------------------------
do_check() {
    # shellcheck source=lib/deep-engine-resolve.sh
    . "$TOOLS_DIR/lib/deep-engine-resolve.sh"
    local engine bin rc=0
    echo "deep-engine provisioning status (bin dir: $BIN_DIR)"
    for engine in halmos medusa echidna; do
        if resolve_deep_engine "$engine"; then
            local ver
            ver="$("$DEEP_ENGINE_BIN" --version 2>/dev/null | awk 'NF {print; exit}')"
            echo "  $engine: AVAILABLE  source=$DEEP_ENGINE_SOURCE  bin=$DEEP_ENGINE_BIN  version=${ver:-unknown}"
        else
            echo "  $engine: MISSING    (run: tools/provision-deep-engines.sh --engine $engine)"
            rc=1
        fi
    done
    return $rc
}

# ---- halmos: pip into a private venv --------------------------------------
provision_halmos() {
    if [ -x "$BIN_DIR/halmos" ]; then
        log "halmos already provisioned at $BIN_DIR/halmos - skipping"
        return 0
    fi
    command -v python3 >/dev/null 2>&1 || fail "python3 not found; cannot provision halmos"
    log "creating halmos venv at $VENV_DIR"
    python3 -m venv "$VENV_DIR" || fail "python3 -m venv failed"
    log "pip install halmos==$HALMOS_VERSION (this may take a few minutes)"
    "$VENV_DIR/bin/pip" install --quiet --upgrade pip >/dev/null 2>&1 || true
    if ! "$VENV_DIR/bin/pip" install --quiet "halmos==$HALMOS_VERSION"; then
        fail "pip install halmos==$HALMOS_VERSION failed (network? version yanked?)"
    fi
    [ -x "$VENV_DIR/bin/halmos" ] || fail "halmos entrypoint missing after pip install"
    # Stable wrapper so the resolver finds tools/deep-engine-bin/halmos.
    cat > "$BIN_DIR/halmos" <<EOF
#!/usr/bin/env bash
# Auto-generated by tools/provision-deep-engines.sh - pinned halmos $HALMOS_VERSION
exec "$VENV_DIR/bin/halmos" "\$@"
EOF
    chmod +x "$BIN_DIR/halmos"
    log "halmos provisioned: $("$BIN_DIR/halmos" --version 2>/dev/null | awk 'NF {print; exit}')"
}

# ---- github release binary fetch (medusa / echidna) -----------------------
fetch_release_binary() {
    local engine="$1" repo="$2" version="$3" asset="$4"
    if [ -x "$BIN_DIR/$engine" ]; then
        log "$engine already provisioned at $BIN_DIR/$engine - skipping"
        return 0
    fi
    command -v curl >/dev/null 2>&1 || fail "curl not found; cannot provision $engine"
    WORK_DIR="$(mktemp -d)"
    local url="https://github.com/$repo/releases/download/$version/$asset"
    log "downloading $engine $version from $url"
    if ! curl -fsSL --retry 2 -o "$WORK_DIR/$asset" "$url"; then
        fail "download failed for $engine ($url) - check network / version pin / platform asset name"
    fi
    case "$asset" in
        *.tar.gz|*.tgz) tar -xzf "$WORK_DIR/$asset" -C "$WORK_DIR" ;;
        *.zip)          unzip -q "$WORK_DIR/$asset" -d "$WORK_DIR" ;;
        *)              cp "$WORK_DIR/$asset" "$WORK_DIR/$engine" ;;
    esac
    local extracted
    extracted="$(find "$WORK_DIR" -type f -name "$engine" -perm -u+x 2>/dev/null | head -1)"
    [ -z "$extracted" ] && extracted="$(find "$WORK_DIR" -type f -name "$engine" 2>/dev/null | head -1)"
    [ -z "$extracted" ] && fail "$engine binary not found inside release asset $asset"
    cp "$extracted" "$BIN_DIR/$engine"
    chmod +x "$BIN_DIR/$engine"
    rm -rf "$WORK_DIR"; WORK_DIR=""
    log "$engine provisioned: $("$BIN_DIR/$engine" --version 2>/dev/null | awk 'NF {print; exit}')"
}

provision_medusa() {
    detect_platform
    [ "$PLATFORM_OS" = "unknown" ] && fail "unsupported OS for medusa"
    # crytic/medusa asset naming: medusa-<os>-<arch>.tar.gz
    local arch="$PLATFORM_ARCH"
    [ "$arch" = "x64" ] && arch="x64"
    local asset="medusa-${PLATFORM_OS}-${arch}.tar.gz"
    fetch_release_binary medusa "crytic/medusa" "$MEDUSA_VERSION" "$asset"
}

provision_echidna() {
    detect_platform
    [ "$PLATFORM_OS" = "unknown" ] && fail "unsupported OS for echidna"
    # crytic/echidna asset naming: echidna-<ver>-<arch>-<os>.tar.gz
    local osname="$PLATFORM_OS"
    [ "$osname" = "macos" ] && osname="macOS"
    [ "$osname" = "linux" ] && osname="Linux"
    local asset="echidna-${ECHIDNA_VERSION}-${PLATFORM_ARCH}-${osname}.tar.gz"
    fetch_release_binary echidna "crytic/echidna" "v${ECHIDNA_VERSION}" "$asset"
}

# ---- rust deep engines (bolero / kani / miri) -----------------------------
# Provisioned into the caller's existing cargo/rustup toolchains (NOT into
# BIN_DIR) because cargo-installed binaries live in ~/.cargo/bin and miri is
# a rustup component. Each step is idempotent (skip when already present) and
# offline-safe (any cargo/rustup/network failure -> WARN + continue, never
# fail()). Gated on `command -v cargo`; the whole block is a no-op when the
# Rust toolchain is absent.
provision_rust() {
    if ! command -v cargo >/dev/null 2>&1; then
        warn "cargo not found on PATH; skipping Rust deep engines (bolero/kani/miri)" || true
        return 0
    fi

    # cargo-bolero: coverage-guided fuzz harness driver.
    if command -v cargo-bolero >/dev/null 2>&1; then
        log "cargo-bolero already installed - skipping"
    else
        log "cargo install --locked cargo-bolero (may take several minutes)"
        if ! cargo install --locked cargo-bolero; then
            warn "cargo install cargo-bolero failed (network? build deps?) - continuing" || true
        fi
    fi

    # kani-verifier: model checker. Needs the post-install `cargo kani setup`
    # to fetch its backend; detect a working install via `cargo kani --version`.
    if cargo kani --version >/dev/null 2>&1; then
        log "cargo-kani already installed - skipping"
    else
        log "cargo install --locked kani-verifier (may take several minutes)"
        if ! cargo install --locked kani-verifier; then
            warn "cargo install kani-verifier failed (network? build deps?) - continuing" || true
        elif ! cargo kani setup; then
            warn "cargo kani setup failed (network?) - kani binary present but backend missing" || true
        fi
    fi

    # miri: rustup component (interpreter for UB detection). Requires rustup;
    # if rustup is absent (e.g. distro-packaged cargo) skip honestly.
    if ! command -v rustup >/dev/null 2>&1; then
        warn "rustup not found; skipping miri component (rust toolchain not rustup-managed)" || true
    elif rustup component list --installed 2>/dev/null | grep -q '^miri'; then
        log "miri component already installed - skipping"
    else
        log "rustup component add miri"
        if ! rustup component add miri; then
            warn "rustup component add miri failed (network? channel lacks miri?) - continuing" || true
        fi
    fi
    return 0
}

# ---- go deep engines (staticcheck / govulncheck) --------------------------
# `go install` drops binaries into $GOBIN (or $(go env GOPATH)/bin). Idempotent
# via `command -v`; offline-safe (any go-install failure -> WARN + continue).
# Gated on `command -v go`; no-op when the Go toolchain is absent.
provision_go() {
    if ! command -v go >/dev/null 2>&1; then
        warn "go not found on PATH; skipping Go deep engines (staticcheck/govulncheck)" || true
        return 0
    fi

    if command -v staticcheck >/dev/null 2>&1; then
        log "staticcheck already installed - skipping"
    else
        log "go install honnef.co/go/tools/cmd/staticcheck@latest"
        if ! go install honnef.co/go/tools/cmd/staticcheck@latest; then
            warn "go install staticcheck failed (network? GOPROXY?) - continuing" || true
        fi
    fi

    if command -v govulncheck >/dev/null 2>&1; then
        log "govulncheck already installed - skipping"
    else
        log "go install golang.org/x/vuln/cmd/govulncheck@latest"
        if ! go install golang.org/x/vuln/cmd/govulncheck@latest; then
            warn "go install govulncheck failed (network? GOPROXY?) - continuing" || true
        fi
    fi
    return 0
}

# ---- arg parse -------------------------------------------------------------
ENGINE_TARGET="all"
LANG_HINT=""
CHECK_ONLY=0
while [ $# -gt 0 ]; do
    case "$1" in
        --engine) ENGINE_TARGET="${2:-}"; shift 2 ;;
        --lang)   LANG_HINT="${2:-}"; shift 2 ;;
        --check)  CHECK_ONLY=1; shift ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \{0,1\}//' | head -40
            exit 0 ;;
        *) log "unknown argument: $1"; exit 1 ;;
    esac
done

mkdir -p "$BIN_DIR"

if [ "$CHECK_ONLY" = "1" ]; then
    do_check
    exit $?
fi

# Map an optional workspace-language hint to the engine families to run under
# `--engine all`. Empty hint = provision every family whose toolchain exists
# (each provision_* self-gates on command -v). EVM is always attempted under
# `all` to preserve the pre-existing behavior.
lang_wants() {
    # $1 = family (evm|rust|go). Returns 0 if the current LANG_HINT selects it.
    [ -z "$LANG_HINT" ] && return 0
    case "$LANG_HINT" in
        evm|solidity|vyper)              [ "$1" = "evm" ] ;;
        rust|cargo)                      [ "$1" = "rust" ] ;;
        go|golang)                       [ "$1" = "go" ] ;;
        *) return 0 ;;  # unknown hint -> do not filter, attempt all families
    esac
}

case "$ENGINE_TARGET" in
    halmos)  provision_halmos ;;
    medusa)  provision_medusa ;;
    echidna) provision_echidna ;;
    rust)    provision_rust ;;
    go)      provision_go ;;
    all)
        if lang_wants evm; then
            provision_halmos
            provision_medusa
            provision_echidna
        fi
        lang_wants rust && provision_rust
        lang_wants go   && provision_go ;;
    *) log "invalid --engine value: $ENGINE_TARGET (want halmos|medusa|echidna|rust|go|all)"; exit 1 ;;
esac

log "provisioning complete; runners will now resolve from $BIN_DIR"
do_check || true
exit 0
