#!/usr/bin/env python3
"""Emit a conservative scanner wiring truth ledger from local repo evidence.

This tool does not run scanners, compile targets, or fetch network data.  It
records what is locally visible about scanner/pattern wiring so downstream
memory can distinguish real wired coverage from DSL-only, generated,
quarantined, documentation, and Rust source-shape-only rows.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable


SCHEMA_VERSION = "auditooor.scanner_wiring_truth_inventory.v1"
DEFAULT_LIMIT = 12_000

WIRING_STATUSES = {
    "wired_verified",
    "dsl_only_or_unverified",
    "generated_no_fixture",
    "quarantined_fake",
    "in_dsl_fake_suspect",
    "backend_executor_missing_or_tbd",
    "rust_source_shape_only",
    "documentation_only",
    "backend_executor_gap_fail_closed",
    "unknown",
}

EXECUTOR_SIGNALS = {
    "solidity": [
        "detectors/run_custom.py",
        "tools/run-detector.py",
        "tools/slither-compile-cache.py",
    ],
    "rust": [
        "tools/rust-scan.sh",
        "tools/rust-detect.py",
        "tools/base-rust-swival-shape-scan.py",
        "tools/rust-source-graph.py",
    ],
    "circom": [
        "tools/zkbugs-detectorization-map.py",
    ],
    "move": [
        "tools/move-detector-runner.py",
        "detectors/move_wave1/test_fixtures/test_detectors.sh",
    ],
    "go": [
        "tools/go-detector-runner.py",
        "tools/lang-detect.py",
        "detectors/go_wave1/test_fixtures/test_detectors.sh",
    ],
    "python": [
        "tools/python-detector-runner.py",
        "tools/lang-detect.py",
        "detectors/python_wave1/test_fixtures/test_detectors.sh",
    ],
}

BACKEND_EXECUTOR_RUN_COMMANDS = {
    "go": "python3 tools/lang-detect.py --lang go <workspace> --log <workspace>/audit/go-detect.log",
    "python": "python3 tools/lang-detect.py --lang python <workspace> --log <workspace>/audit/python-detect.log",
}

BACKEND_FAIL_CLOSED_GAPS = {
    "move": {
        "source_paths": [
            "tools/lang-detect.py",
            "docs/CROSS_LANGUAGE_DETECTORS.md",
            "docs/POLYGLOT_WAVE2_2026-05-04.md",
            "detectors/move_wave2/inflation_attack_zero_stake.py",
            "detectors/move_wave2/test_fixtures/inflation_attack_zero_stake_vulnerable.move",
            "detectors/move_wave2/test_fixtures/inflation_attack_zero_stake_clean.move",
        ],
        "blockers": [
            "move_shared_backend_executor_absent",
            "lang_detect_loads_move_wave1_only",
            "move_wave2_detectors_are_standalone_text_scanners",
            "move_wave2_regression_harness_missing",
        ],
        "suggested_next_action": (
            "fail closed: do not claim Move backend support until a shared Move executor loads "
            "the committed Move detector wave and a positive/clean regression harness passes"
        ),
    },
}

DOC_NAME_RE = re.compile(r"(scanner|detector|wiring|coverage|rust|executor)", re.I)
GENERATED_RE = re.compile(r"\b(generated|autogenerated|skeleton|template|draft)\b", re.I)
DOC_ONLY_RE = re.compile(r"\b(documentation[-_ ]only|docs[-_ ]only|reference[-_ ]only)\b", re.I)
SOURCE_SHAPE_RE = re.compile(r"\b(source[-_ ]shape|shape[-_ ]only|heuristic|tree[-_ ]sitter|regex|ast-only)\b", re.I)
EXPLICIT_FAKE_STATUS_RE = re.compile(
    r"^(fake|suspect|quarantine|quarantined|quarantined_fake|in_dsl_fake_suspect|mock[-_ ]only|hallucinated)$",
    re.I,
)
EXPLICIT_FAKE_COMMENT_RE = re.compile(r"(?m)^\s*#\s*(fake|suspect|quarantine|mock-only|hallucinated)\b", re.I)


@dataclass(frozen=True)
class LedgerRow:
    scanner_id: str
    pattern_id: str
    backend: str
    source_paths: list[str]
    evidence_kind: str
    wiring_status: str
    proof_status: str
    blockers: list[str]
    suggested_next_action: str
    memory_priority: int


@dataclass
class SupplementalFixtureEvidence:
    paths: list[Path]
    markers: set[str]


def _slug(value: str, fallback: str = "row") -> str:
    out = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return out or fallback


def _norm_id(value: str) -> str:
    return _slug(value).replace("-", "_")


def _rel(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except (OSError, ValueError):
        return str(path)


def _read_text(path: Path, *, max_bytes: int = 256_000) -> str:
    try:
        with path.open("rb") as handle:
            data = handle.read(max_bytes)
    except OSError:
        return ""
    return data.decode("utf-8", errors="replace")


def _read_json(path: Path) -> Any:
    text = _read_text(path)
    if not text.strip():
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def _metadata_sidecar_path(path: Path) -> bool:
    return path.name == "smoke.json" or path.name.endswith("_smoke.json") or path.name == "manifest.json" or path.name.endswith("_manifest.json")


def _first_scalar(text: str, *keys: str) -> str:
    for key in keys:
        match = re.search(rf"(?m)^\s*{re.escape(key)}\s*:\s*(.+?)\s*$", text)
        if not match:
            continue
        value = match.group(1).strip()
        value = re.sub(r"\s+#.*$", "", value).strip()
        value = value.strip("\"'")
        if value and value not in {"|", ">"}:
            return value
    return ""


def _detector_argument(text: str, fallback_stem: str) -> str:
    match = re.search(r"(?m)^\s*ARGUMENT\s*=\s*[\"']([^\"']+)[\"']", text)
    if match:
        return match.group(1).strip()
    return fallback_stem.replace("_", "-")


def _canonical_dsl_text_for_detector(root: Path, argument: str) -> str:
    if not argument:
        return ""
    path = root / "reference" / "patterns.dsl" / f"{argument}.yaml"
    if not path.is_file():
        return ""
    return _read_text(path)


def _dsl_backend(text: str) -> str:
    value = _first_scalar(text, "backend", "language", "engine").lower()
    if not value:
        return ""
    parts = [part for part in re.split(r"[^a-z0-9_]+", value) if part]
    return parts[0] if parts else value


def _backend_from_path(path: Path, text: str = "") -> str:
    parts = [part.lower() for part in path.parts]
    path_tokens = {
        token
        for part in parts
        for token in re.split(r"[^a-z0-9]+", part)
        if token
    }
    explicit_backend = _first_scalar(text, "backend", "language", "engine").lower()
    for backend in ("rust", "circom", "move", "go", "python", "solidity"):
        if backend in path_tokens or explicit_backend == backend:
            return backend
    rel = "/".join(parts)
    if "slither" in text[:4096].lower() or path.suffix == ".sol" or re.search(r"/wave\d+/", rel):
        return "solidity"
    return "unknown"


def _detector_paths(root: Path) -> list[Path]:
    detectors_root = root / "detectors"
    if not detectors_root.is_dir():
        return []
    out: list[Path] = []
    for path in detectors_root.rglob("*.py"):
        rel = path.relative_to(detectors_root)
        if "__pycache__" in rel.parts:
            continue
        if path.name.startswith("test_") or path.name == "__init__.py":
            continue
        if path.name.startswith("_") and "quarantine" not in "/".join(rel.parts).lower():
            continue
        if path.name in {"run_custom.py"}:
            continue
        out.append(path)
    return sorted(out)


def _fixture_roots(root: Path) -> list[Path]:
    roots = [
        root / "detectors" / "_fixtures",
        root / "detectors" / "fixtures",
        root / "detectors" / "test_fixtures",
        root / "patterns" / "fixtures",
        root / "test_fixtures",
    ]
    detectors_root = root / "detectors"
    if detectors_root.is_dir():
        roots.extend(
            path
            for path in sorted(detectors_root.glob("*/test_fixtures"))
            if path.is_dir()
        )
        roots.extend(
            path
            for path in sorted(detectors_root.glob("*/fixtures"))
            if path.is_dir()
        )
        roots.extend(
            path
            for path in sorted(detectors_root.glob("*_broken"))
            if path.is_dir()
        )
    return roots


def _fixture_index(root: Path) -> dict[str, list[Path]]:
    index: dict[str, list[Path]] = {}
    for fixture_root in _fixture_roots(root):
        if not fixture_root.is_dir():
            continue
        for path in sorted(fixture_root.rglob("*")):
            if not path.is_file():
                continue
            parts = path.relative_to(fixture_root).parts
            names = {path.stem, path.name}
            if parts:
                names.add(parts[0])
            for name in names:
                index.setdefault(_norm_id(name), []).append(path)
    return index


def _fixture_manifest_refs(paths: Iterable[Path], root: Path) -> tuple[list[Path], set[str]]:
    refs: list[Path] = []
    seen: set[Path] = set()
    markers: set[str] = set()
    for path in paths:
        if path.suffix.lower() != ".json":
            continue
        payload = _read_json(path)
        if not isinstance(payload, dict):
            continue
        if _metadata_sidecar_path(path):
            if _graveyard_or_broken_path(path):
                continue
            status = str(payload.get("status") or "").strip()
            if (path.name == "smoke.json" or path.name.endswith("_smoke.json")) and status and not _passing_smoke_status(payload):
                continue
        values: list[tuple[str, str]] = []
        for key in (
            "smoke_record",
            "smoke_record_path",
            "positive_fixture",
            "positive_fixture_path",
            "vulnerable_fixture",
            "vulnerable_fixture_path",
            "clean_fixture",
            "clean_fixture_path",
            "negative_fixture",
            "negative_fixture_path",
        ):
            value = payload.get(key)
            if isinstance(value, str) and value.strip():
                values.append((key, value.strip()))
        fixtures = payload.get("fixtures")
        if isinstance(fixtures, dict):
            for key in ("positive", "vulnerable", "clean", "negative"):
                value = fixtures.get(key)
                if isinstance(value, str) and value.strip():
                    values.append((key, value.strip()))
        for key, raw in values:
            candidate = Path(raw)
            resolved_paths: list[Path] = []
            if candidate.is_absolute():
                try:
                    resolved = candidate.resolve()
                    resolved.relative_to(root.resolve())
                except (OSError, ValueError):
                    continue
                resolved_paths.append(resolved)
            else:
                resolved_paths.extend([(root / candidate).resolve(), (path.parent / candidate).resolve()])
            for resolved in resolved_paths:
                if not resolved.exists() or resolved in seen:
                    continue
                seen.add(resolved)
                refs.append(resolved)
                if "smoke_record" in key:
                    smoke_refs, smoke_markers = _fixture_manifest_refs([resolved], root)
                    for smoke_ref in smoke_refs:
                        if smoke_ref in seen:
                            continue
                        seen.add(smoke_ref)
                        refs.append(smoke_ref)
                    markers.update(smoke_markers)
                if "positive" in key or "vulnerable" in key:
                    markers.add("positive")
                if "clean" in key or "negative" in key:
                    markers.add("clean")
    return refs, markers


def _resolve_repo_relative_path(raw: str, root: Path, *, base: Path | None = None) -> Path | None:
    candidate = Path(raw.strip())
    if not raw.strip():
        return None
    resolved_paths: list[Path] = []
    if candidate.is_absolute():
        resolved_paths.append(candidate.resolve())
    else:
        resolved_paths.append((root / candidate).resolve())
        if base is not None:
            resolved_paths.append((base / candidate).resolve())
    for resolved in resolved_paths:
        try:
            resolved.relative_to(root.resolve())
        except (OSError, ValueError):
            continue
        if resolved.exists():
            return resolved
    return None


def _closure_smoke_fixture_index(root: Path) -> dict[str, SupplementalFixtureEvidence]:
    reports_root = root / "reports"
    if not reports_root.is_dir():
        return {}
    index: dict[str, SupplementalFixtureEvidence] = {}
    for report_path in sorted(reports_root.glob("scanner_quarantine_closure_*.json")):
        payload = _read_json(report_path)
        if not isinstance(payload, dict):
            continue
        closed_rows = payload.get("closed")
        if not isinstance(closed_rows, list):
            continue
        for row in closed_rows:
            if not isinstance(row, dict):
                continue
            scanner_keys: set[str] = set()
            for candidate in (
                row.get("row_id"),
                row.get("detector_slug"),
                payload.get("selected_row"),
            ):
                if isinstance(candidate, str) and candidate.strip():
                    scanner_keys.add(_norm_id(candidate))
            detector_path = row.get("detector")
            if isinstance(detector_path, str) and detector_path.strip():
                scanner_keys.add(_norm_id(Path(detector_path).stem))

            smoke_path: Path | None = None
            smoke_record = row.get("smoke_record")
            if isinstance(smoke_record, str):
                smoke_path = _resolve_repo_relative_path(smoke_record, root, base=report_path.parent)

            evidence_paths: list[Path] = []
            markers: set[str] = set()
            if smoke_path is not None:
                evidence_paths.append(smoke_path)
                smoke_payload = _read_json(smoke_path)
                if isinstance(smoke_payload, dict):
                    for candidate in (
                        smoke_payload.get("detector_slug"),
                        smoke_payload.get("fixture_id"),
                        smoke_payload.get("pattern"),
                    ):
                        if isinstance(candidate, str) and candidate.strip():
                            scanner_keys.add(_norm_id(candidate))
                    detector_path_in_smoke = smoke_payload.get("detector_path")
                    if isinstance(detector_path_in_smoke, str) and detector_path_in_smoke.strip():
                        scanner_keys.add(_norm_id(Path(detector_path_in_smoke).stem))

            fixture_pair = row.get("fixture_pair")
            if isinstance(fixture_pair, dict):
                for key, marker in (
                    ("positive", "positive"),
                    ("vulnerable", "positive"),
                    ("clean", "clean"),
                    ("negative", "clean"),
                ):
                    value = fixture_pair.get(key)
                    if not isinstance(value, str):
                        continue
                    resolved = _resolve_repo_relative_path(value, root, base=report_path.parent)
                    if resolved is None:
                        continue
                    evidence_paths.append(resolved)
                    markers.add(marker)

            if not scanner_keys or not evidence_paths:
                continue

            unique_paths = sorted(set(evidence_paths))
            for scanner_key in sorted(scanner_keys):
                current = index.get(scanner_key)
                if current is None:
                    index[scanner_key] = SupplementalFixtureEvidence(paths=list(unique_paths), markers=set(markers))
                    continue
                current.paths = sorted(set([*current.paths, *unique_paths]))
                current.markers.update(markers)
    return index


def _passing_smoke_status(payload: dict[str, Any]) -> bool:
    status = str(payload.get("status") or "").strip().lower()
    if not status:
        return False
    return status in {
        "smoke_pass",
        "passed",
        "pass",
        "passed_smoke",
        "passed_vulnerable_clean_smoke",
    }


def _graveyard_or_broken_path(path: Path) -> bool:
    parts = {part.lower() for part in path.parts}
    return "wave_graveyard" in parts or any(part.endswith("_broken") for part in parts)


def _merge_supplemental_evidence(
    index: dict[str, SupplementalFixtureEvidence],
    scanner_key: str,
    paths: Iterable[Path],
    markers: Iterable[str],
) -> None:
    unique_paths = sorted(set(paths))
    if not scanner_key or not unique_paths:
        return
    current = index.get(scanner_key)
    if current is None:
        index[scanner_key] = SupplementalFixtureEvidence(paths=list(unique_paths), markers=set(markers))
        return
    current.paths = sorted(set([*current.paths, *unique_paths]))
    current.markers.update(markers)


def _smoke_sidecar_fixture_index(root: Path) -> dict[str, SupplementalFixtureEvidence]:
    """Index smoke sidecars by their own detector/pattern metadata.

    The normal fixture index keys by directory and filename. That misses
    nonstandard fixture roots where the only binding between a detector and
    its positive/clean pair lives inside smoke.json. Indexing the sidecar
    metadata keeps scanner truth tied to explicit smoke evidence rather than
    stale directory-name heuristics.
    """
    index: dict[str, SupplementalFixtureEvidence] = {}
    seen: set[Path] = set()
    for fixture_root in _fixture_roots(root):
        if not fixture_root.is_dir():
            continue
        for smoke_path in sorted(fixture_root.rglob("*.json")):
            if smoke_path in seen:
                continue
            if not _metadata_sidecar_path(smoke_path):
                continue
            seen.add(smoke_path)
            payload = _read_json(smoke_path)
            if not isinstance(payload, dict):
                continue
            if (smoke_path.name == "smoke.json" or smoke_path.name.endswith("_smoke.json")) and not _passing_smoke_status(payload):
                continue
            if _graveyard_or_broken_path(smoke_path):
                continue

            scanner_keys: set[str] = set()
            for candidate in (
                payload.get("detector_slug"),
                payload.get("fixture_id"),
                payload.get("pattern"),
                payload.get("pattern_id"),
            ):
                if isinstance(candidate, str) and candidate.strip():
                    scanner_keys.add(_norm_id(candidate))

            detector_path = payload.get("detector_path")
            if isinstance(detector_path, str) and detector_path.strip():
                scanner_keys.add(_norm_id(Path(detector_path).stem))

            if not scanner_keys:
                continue

            manifest_refs, manifest_markers = _fixture_manifest_refs([smoke_path], root)
            evidence_paths = [smoke_path, *manifest_refs]
            for scanner_key in sorted(scanner_keys):
                _merge_supplemental_evidence(index, scanner_key, evidence_paths, manifest_markers)
    return index


def _supplemental_fixture_index(root: Path) -> dict[str, SupplementalFixtureEvidence]:
    index = _smoke_sidecar_fixture_index(root)
    for scanner_key, evidence in _closure_smoke_fixture_index(root).items():
        _merge_supplemental_evidence(index, scanner_key, evidence.paths, evidence.markers)
    return index


def _fixture_evidence(
    scanner_id: str,
    fixture_idx: dict[str, list[Path]],
    root: Path,
    closure_smoke_idx: dict[str, SupplementalFixtureEvidence],
) -> tuple[bool, list[str], list[str]]:
    key = _norm_id(scanner_id)
    candidates = list(fixture_idx.get(key, []))
    supplemental_markers: set[str] = set()
    supplemental = closure_smoke_idx.get(key)
    if supplemental is not None:
        candidates.extend(supplemental.paths)
        supplemental_markers.update(supplemental.markers)
    # Some fixture filenames include the detector slug plus a suffix. Always
    # include those suffix matches; an extraction manifest directory can occupy
    # the exact key without being the actual clean/vulnerable fixture pair.
    for indexed_key, paths in fixture_idx.items():
        if indexed_key.startswith(key + "_") or indexed_key.startswith(key + "-"):
            candidates.extend(paths)
    manifest_refs, manifest_markers = _fixture_manifest_refs(candidates, root)
    manifest_markers.update(supplemental_markers)
    evidence_paths = [*candidates, *manifest_refs]
    rels = sorted({_rel(path, root) for path in evidence_paths})
    names = " ".join(_rel(path, root).lower() for path in evidence_paths)
    has_vulnerable = (
        "positive" in manifest_markers
        or any(marker in names for marker in ("vuln", "vulnerable", "positive", "bad", "poc"))
    )
    has_clean = (
        "clean" in manifest_markers
        or any(marker in names for marker in ("clean", "negative", "good", "fixed"))
    )
    return has_vulnerable and has_clean, rels, [
        blocker
        for blocker, missing in (
            ("positive_or_vulnerable_fixture_missing", not has_vulnerable),
            ("clean_or_negative_fixture_missing", not has_clean),
        )
        if missing
    ]


def _dsl_paths(root: Path) -> list[Path]:
    reference = root / "reference"
    if not reference.is_dir():
        return []
    return sorted(path for path in reference.rglob("*.yaml") if "patterns.dsl" in str(path))


def _explicit_fake_or_quarantine_marker(path: Path, text: str, status: str) -> bool:
    status_norm = status.strip().replace("-", "_").replace(" ", "_")
    if status_norm and EXPLICIT_FAKE_STATUS_RE.search(status_norm):
        return True
    rel_parts = {part.lower() for part in path.parts}
    if any("quarantine" in part for part in rel_parts):
        return True
    return bool(EXPLICIT_FAKE_COMMENT_RE.search(text))


def _dsl_row(path: Path, root: Path, detector_rows_by_id: dict[str, LedgerRow]) -> LedgerRow:
    text = _read_text(path)
    pattern_id = _first_scalar(text, "pattern", "id", "pattern_id", "name") or path.stem
    status = _first_scalar(text, "status", "wiring_status", "proof_status").lower()
    norm = _norm_id(pattern_id)
    detector_row = detector_rows_by_id.get(norm)
    backend = _first_scalar(text, "backend", "language", "engine") or (detector_row.backend if detector_row else "")
    backend = backend or _backend_from_path(path, text)
    rel = _rel(path, root)
    source_paths = [rel]
    blockers: list[str] = []
    proof_status = "no_detector_or_fixture_evidence"
    wiring_status = "dsl_only_or_unverified"
    evidence_kind = "dsl_yaml"
    priority = 70
    action = "wire detector predicate plus vulnerable/clean fixtures, or mark documentation-only"

    if DOC_ONLY_RE.search(status) or DOC_ONLY_RE.search(text):
        wiring_status = "documentation_only"
        proof_status = "documentation_reference_only"
        blockers = ["documentation_only_no_executable_detector"]
        priority = 30
        action = "keep as documentation unless a concrete detector and fixture pair are added"
    elif _explicit_fake_or_quarantine_marker(path, text, status):
        wiring_status = "in_dsl_fake_suspect"
        proof_status = "fake_or_suspect_dsl_evidence"
        blockers = ["dsl_fake_or_suspect_marker_present", "detector_wiring_not_trusted"]
        priority = 95
        action = "quarantine or delete suspect DSL row before treating it as memory"
    elif detector_row and detector_row.proof_status == "detector_and_fixture_pair_present":
        wiring_status = "wired_verified"
        proof_status = "detector_and_fixture_pair_present"
        blockers = []
        priority = 20
        evidence_kind = "dsl_yaml_with_detector_fixture_pair"
        source_paths = sorted({rel, *detector_row.source_paths})
        action = "keep as wired fixture-backed coverage; cite smoke output before claiming runtime proof"
    elif detector_row:
        proof_status = "detector_name_match_only"
        blockers = ["fixture_pair_not_verified_from_dsl_row"]
        priority = 60
        source_paths = sorted({rel, *detector_row.source_paths})
        action = "verify matching detector has positive/clean fixtures and smoke output"
    else:
        blockers = ["detector_file_missing", "fixture_pair_missing", "executor_route_unverified"]

    return LedgerRow(
        scanner_id="",
        pattern_id=pattern_id,
        backend=backend or "unknown",
        source_paths=source_paths,
        evidence_kind=evidence_kind,
        wiring_status=wiring_status,
        proof_status=proof_status,
        blockers=sorted(blockers),
        suggested_next_action=action,
        memory_priority=priority,
    )


def _detector_row(
    path: Path,
    root: Path,
    fixture_idx: dict[str, list[Path]],
    closure_smoke_idx: dict[str, SupplementalFixtureEvidence],
) -> LedgerRow:
    text = _read_text(path)
    scanner_id = path.stem
    argument = _detector_argument(text, scanner_id)
    canonical_dsl_text = _canonical_dsl_text_for_detector(root, argument)
    canonical_backend = _dsl_backend(canonical_dsl_text)
    path_backend = _backend_from_path(path, text)
    backend = canonical_backend or path_backend
    rel = _rel(path, root)
    fixture_verified, fixture_paths, fixture_blockers = _fixture_evidence(
        scanner_id, fixture_idx, root, closure_smoke_idx
    )
    canonical_dsl_path = root / "reference" / "patterns.dsl" / f"{argument}.yaml"
    canonical_refs = [_rel(canonical_dsl_path, root)] if canonical_dsl_text else []
    source_paths = sorted([rel, *canonical_refs, *fixture_paths])
    path_text = str(path).lower()
    blockers: list[str] = []
    proof_status = "detector_file_present"
    wiring_status = "unknown"
    priority = 50
    action = "inspect detector wiring and add fixture/smoke evidence"

    if "quarantine" in path_text or _graveyard_or_broken_path(path):
        wiring_status = "quarantined_fake"
        proof_status = "quarantined_or_fake_detector_artifact"
        path_blocker = "quarantine_path_present"
        if _graveyard_or_broken_path(path):
            path_blocker = "graveyard_or_broken_path_present"
        blockers = [path_blocker, "detector_must_not_count_as_wired"]
        priority = 100
        action = "keep out of wired coverage memory unless explicitly restored with fixtures"
    elif fixture_verified:
        wiring_status = "wired_verified"
        proof_status = "detector_and_fixture_pair_present"
        blockers = []
        priority = 20
        action = "optionally add or link smoke output; keep as wired fixture-backed coverage"
    elif backend == "rust":
        wiring_status = "rust_source_shape_only"
        proof_status = "rust_detector_without_fixture_pair"
        blockers = sorted({"rust_runtime_semantics_unverified", *fixture_blockers})
        priority = 90
        action = "add Rust runtime/cfg/trait proof plus positive/clean fixture evidence"
    elif GENERATED_RE.search(text) or GENERATED_RE.search(str(path)):
        wiring_status = "generated_no_fixture"
        proof_status = "generated_detector_without_fixture_pair"
        blockers = sorted({"generated_or_draft_detector", *fixture_blockers})
        priority = 80
        action = "materialize vulnerable/clean fixtures before counting as wired"
    else:
        wiring_status = "generated_no_fixture"
        proof_status = "detector_without_fixture_pair"
        blockers = sorted(fixture_blockers or ["fixture_pair_missing"])
        priority = 75
        action = "add vulnerable/clean fixtures and smoke output before counting as wired"

    if SOURCE_SHAPE_RE.search(text) and wiring_status not in {"wired_verified", "quarantined_fake"}:
        proof_status = "source_shape_only"
        if "source_shape_only" not in blockers:
            blockers = sorted([*blockers, "source_shape_only"])
        if backend == "rust":
            wiring_status = "rust_source_shape_only"
            priority = max(priority, 90)

    if (
        canonical_backend
        and path_backend
        and canonical_backend != path_backend
        and wiring_status not in {"wired_verified", "quarantined_fake"}
    ):
        proof_status = "source_shape_only"
        blockers = sorted(
            {
                *blockers,
                "canonical_backend_mismatch_with_detector_path",
                "source_shape_only",
            }
        )
        if canonical_backend == "rust":
            wiring_status = "rust_source_shape_only"
        priority = max(priority, 90)
        action = (
            f"rehome to a {canonical_backend} runner or keep as corpus/hacker-logic context; "
            f"do not count the {path_backend} detector as wired coverage"
        )

    return LedgerRow(
        scanner_id=scanner_id,
        pattern_id="",
        backend=backend,
        source_paths=source_paths,
        evidence_kind="detector_python",
        wiring_status=wiring_status,
        proof_status=proof_status,
        blockers=blockers,
        suggested_next_action=action,
        memory_priority=priority,
    )


def _detector_row_preference(row: LedgerRow) -> tuple[int, int, str]:
    if row.wiring_status == "wired_verified" and row.proof_status == "detector_and_fixture_pair_present":
        return (0, -len(row.source_paths), row.source_paths[0] if row.source_paths else "")
    if row.wiring_status == "quarantined_fake":
        return (4, -len(row.source_paths), row.source_paths[0] if row.source_paths else "")
    if row.wiring_status == "rust_source_shape_only":
        return (3, -len(row.source_paths), row.source_paths[0] if row.source_paths else "")
    if row.wiring_status == "generated_no_fixture":
        return (2, -len(row.source_paths), row.source_paths[0] if row.source_paths else "")
    return (1, -len(row.source_paths), row.source_paths[0] if row.source_paths else "")


def _detector_rows_by_id(rows: Iterable[LedgerRow]) -> dict[str, LedgerRow]:
    out: dict[str, LedgerRow] = {}
    for row in rows:
        if not row.scanner_id:
            continue
        key = _norm_id(row.scanner_id)
        current = out.get(key)
        if current is None or _detector_row_preference(row) < _detector_row_preference(current):
            out[key] = row
    return out


def _quarantine_rows(root: Path, seen_paths: set[str]) -> list[LedgerRow]:
    rows: list[LedgerRow] = []
    for base in (root / "detectors", root / "reference"):
        if not base.is_dir():
            continue
        for path in sorted(item for item in base.rglob("*") if item.is_file()):
            if "__pycache__" in path.parts or path.suffix == ".pyc":
                continue
            rel = _rel(path, root)
            lower = rel.lower()
            if rel in seen_paths:
                continue
            if "quarantine" not in lower:
                continue
            rows.append(
                LedgerRow(
                    scanner_id=path.stem if path.suffix == ".py" else "",
                    pattern_id=path.stem if path.suffix in {".yaml", ".yml"} else f"artifact-{_slug(path.stem)}",
                    backend=_backend_from_path(path, _read_text(path)),
                    source_paths=[rel],
                    evidence_kind="quarantine_artifact",
                    wiring_status="quarantined_fake",
                    proof_status="quarantined_or_fake_artifact",
                    blockers=["quarantine_or_fake_path_present", "must_not_count_as_wired_coverage"],
                    suggested_next_action="exclude from wired scanner memory unless restored with proof",
                    memory_priority=100,
                )
            )
    return rows


def _backend_rows(root: Path, detector_rows: Iterable[LedgerRow]) -> list[LedgerRow]:
    backends = sorted({row.backend for row in detector_rows if row.backend not in {"", "unknown"}})
    rows: list[LedgerRow] = []
    for backend in backends:
        signals = EXECUTOR_SIGNALS.get(backend, [])
        present = [signal for signal in signals if (root / signal).exists()]
        if present:
            run_command = BACKEND_EXECUTOR_RUN_COMMANDS.get(backend)
            action = "join executor signal with detector fixture rows before claiming coverage"
            if run_command:
                action = (
                    f"executor route is locally visible via `{run_command}`; "
                    "join that route with concrete detector fixture rows before claiming coverage"
                )
            rows.append(
                LedgerRow(
                    scanner_id=f"{backend}-backend-executor",
                    pattern_id="",
                    backend=backend,
                    source_paths=present,
                    evidence_kind="backend_executor_signal",
                    wiring_status="unknown",
                    proof_status="executor_signal_present_not_detector_proof",
                    blockers=["executor_presence_does_not_prove_individual_scanner_wiring"],
                    suggested_next_action=action,
                    memory_priority=25,
                )
            )
        elif backend in BACKEND_FAIL_CLOSED_GAPS:
            gap = BACKEND_FAIL_CLOSED_GAPS[backend]
            source_paths = [path for path in gap["source_paths"] if (root / path).exists()]
            rows.append(
                LedgerRow(
                    scanner_id=f"{backend}-backend-executor",
                    pattern_id="",
                    backend=backend,
                    source_paths=source_paths,
                    evidence_kind="backend_executor_signal",
                    wiring_status="backend_executor_gap_fail_closed",
                    proof_status="no_shared_backend_executor_fail_closed",
                    blockers=sorted(gap["blockers"]),
                    suggested_next_action=gap["suggested_next_action"],
                    memory_priority=45,
                )
            )
        else:
            rows.append(
                LedgerRow(
                    scanner_id=f"{backend}-backend-executor",
                    pattern_id="",
                    backend=backend,
                    source_paths=[],
                    evidence_kind="backend_executor_signal",
                    wiring_status="backend_executor_missing_or_tbd",
                    proof_status="no_known_executor_signal_found",
                    blockers=[f"{backend}_executor_missing_or_unknown"],
                    suggested_next_action=f"add or document the {backend} backend executor route before claiming scanner coverage",
                    memory_priority=85,
                )
            )
    return rows


def _documentation_rows(root: Path, seen_paths: set[str]) -> list[LedgerRow]:
    rows: list[LedgerRow] = []
    for base_name in ("docs", "reports"):
        base = root / base_name
        if not base.is_dir():
            continue
        for path in sorted(item for item in base.rglob("*") if item.is_file() and item.suffix.lower() in {".md", ".json"}):
            rel = _rel(path, root)
            if rel in seen_paths or not DOC_NAME_RE.search(path.name):
                continue
            rows.append(
                LedgerRow(
                    scanner_id="",
                    pattern_id=path.stem,
                    backend=_backend_from_path(path, path.name),
                    source_paths=[rel],
                    evidence_kind=f"{base_name[:-1]}_artifact",
                    wiring_status="documentation_only",
                    proof_status="report_or_doc_only",
                    blockers=["documentation_is_not_detector_wiring_proof"],
                    suggested_next_action="link to concrete detector, executor, fixture, and smoke rows if this doc claims coverage",
                    memory_priority=35,
                )
            )
    return rows


def _validate_row(row: LedgerRow) -> None:
    if row.wiring_status not in WIRING_STATUSES:
        raise ValueError(f"unknown wiring status: {row.wiring_status}")
    if not row.scanner_id and not row.pattern_id:
        raise ValueError("row needs scanner_id or pattern_id")


def build_inventory(repo_root: Path, *, limit: int | None = DEFAULT_LIMIT) -> dict[str, Any]:
    root = repo_root.resolve()
    fixture_idx = _fixture_index(root)
    closure_smoke_idx = _supplemental_fixture_index(root)
    detector_paths = _detector_paths(root)

    detector_rows = [_detector_row(path, root, fixture_idx, closure_smoke_idx) for path in detector_paths]
    detector_rows_by_id = _detector_rows_by_id(detector_rows)
    dsl_rows = [_dsl_row(path, root, detector_rows_by_id) for path in _dsl_paths(root)]
    seen_paths = {path for row in [*detector_rows, *dsl_rows] for path in row.source_paths}
    rows = [
        *detector_rows,
        *dsl_rows,
        *_quarantine_rows(root, seen_paths),
        *_backend_rows(root, detector_rows),
        *_documentation_rows(root, seen_paths),
    ]
    for row in rows:
        _validate_row(row)

    rows = sorted(
        rows,
        key=lambda row: (
            -row.memory_priority,
            row.wiring_status,
            row.backend,
            row.scanner_id,
            row.pattern_id,
            row.source_paths,
        ),
    )
    total_count = len(rows)
    effective_limit = DEFAULT_LIMIT if limit is None else max(0, limit)
    limited_rows = rows[:effective_limit]
    status_counts = Counter(row.wiring_status for row in limited_rows)
    evidence_counts = Counter(row.evidence_kind for row in limited_rows)
    backend_counts = Counter(row.backend for row in limited_rows)

    return {
        "schema": SCHEMA_VERSION,
        "repo_root": str(root),
        "limit": effective_limit,
        "total_row_count": total_count,
        "item_count": len(limited_rows),
        "truncated": len(limited_rows) < total_count,
        "status_counts": dict(sorted(status_counts.items())),
        "evidence_kind_counts": dict(sorted(evidence_counts.items())),
        "backend_counts": dict(sorted(backend_counts.items())),
        "rows": [asdict(row) for row in limited_rows],
    }


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "repo_root",
        nargs="?",
        default=".",
        help="repo root to scan (default: current directory)",
    )
    parser.add_argument("--json-out", type=Path, help="optional path to write deterministic JSON")
    parser.add_argument("--limit", type=int, default=DEFAULT_LIMIT, help=f"max rows to emit (default: {DEFAULT_LIMIT})")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    payload = build_inventory(Path(args.repo_root), limit=args.limit)
    encoded = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.json_out:
        _write_json(args.json_out, payload)
    else:
        sys.stdout.write(encoded)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
