#!/usr/bin/env python3
"""skipped-test-marker-scan.py - discovery scanner for developer-confessed skipped tests.

A skipped / disabled / ignored test names a behavior the team EXPLICITLY turned
off - because it is broken, flaky, or unverified. That is a developer confession
in exactly the same class as a FIXME / "// TODO: handle reorg" / a self-ack
comment: a high-signal seed for the per-function hunt. A ``t.Skip("flaky")`` /
``#[ignore]`` / ``it.skip(...)`` / ``vm.skip(true)`` is the team telling us where
their own confidence is weakest.

This scanner MINES the project's OWN test corpus (NOT auditooor-authored harness
scaffolding) for those markers, attributes each to the in-scope symbol the
skipped test exercises, and emits seeds for the hunt:

  <ws>/.auditooor/skipped_test_markers.jsonl         - one row per surviving marker
  <ws>/.auditooor/skipped_test_markers_result.json   - the verdict-bearing marker

It mirrors scanner-ran-integrity.py exactly: a ``SCHEMA`` const, an
``analyze(ws)->dict``, verdict tokens (``pass-skipped-test-scan-clean`` /
``found-skipped-tests``), and a ``--check`` / ``--json`` CLI. Stdlib-only,
offline, read-only (except the two artifacts under ``<ws>/.auditooor/``).

IMPORTANT - DISCOVERY != FAILURE: finding skipped tests is the POINT. ``--check``
exits 1 ONLY when the scan genuinely cannot run (scope/manifest unreadable); it
NEVER exits non-zero merely because markers were found. The downstream
disposition GATE (skipped-test-disposition-gate.py) is what enforces that each
discovered seed was hunted or rebutted.

Usage:
  python3 tools/skipped-test-marker-scan.py --workspace <ws> [--check] [--json] [--no-write]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Shared scope filter - never flag OOS / vendored / generated code.
try:  # normal package import
    from tools.lib.scope_exclusion import (  # type: ignore
        is_vendored as _is_vendored,
        is_generated as _is_generated,
        is_tool_artifact as _is_tool_artifact,
    )
except Exception:  # pragma: no cover - direct-script fallback
    _HERE = Path(__file__).resolve().parent
    if str(_HERE) not in sys.path:
        sys.path.insert(0, str(_HERE))
    from lib.scope_exclusion import (  # type: ignore
        is_vendored as _is_vendored,
        is_generated as _is_generated,
        is_tool_artifact as _is_tool_artifact,
    )

SCHEMA = "auditooor.skipped_test_marker.v1"
RESULT_SCHEMA = "auditooor.skipped_test_marker_result.v1"

ARTIFACT_REL = ".auditooor/skipped_test_markers.jsonl"
RESULT_REL = ".auditooor/skipped_test_markers_result.json"

# Dirs never walked (vendored / build / generated / git infra).
_PRUNE_DIRS = {
    "node_modules", "target", "out", ".git", "vendor", "lib", "broadcast",
    "cache", "dist", "build", "artifacts",
}

# Scaffold path segments => auditooor-authored, NOT a developer confession.
_SCAFFOLD_PATH_SEGMENTS = (
    "poc-tests", "engine-harness", ".auditooor", "crytic-export", "echidna-corpus",
)
# Authorship markers in the file head => auditooor-generated stub.
_SCAFFOLD_HEAD_MARKERS = (
    "advisory scaffold", "AUTOGENERATED", "DO NOT EDIT", "auditooor",
    "chimera-scaffold", "recon-log-bridge", "generated by tools/",
)

# ---------------------------------------------------------------------------
# Per-language marker regexes. Each yields (marker_label, capture-of-reason?).
# ---------------------------------------------------------------------------
_GO_SKIP = re.compile(r"\bt\.Skip(?:Now)?\s*\(")
_GO_TESTUTIL_SKIP = re.compile(r"\btestutil\.Skip\b")
_GO_FUNC = re.compile(r"^func\s+(Test\w+|Fuzz\w+|Benchmark\w+)\b")

_RUST_IGNORE = re.compile(r"#\s*\[\s*ignore")
_RUST_RETURN_IGNORED = re.compile(r"\breturn;?\s*//\s*ignored")
_RUST_FN = re.compile(r"\bfn\s+(\w+)")

# JS/TS: it.skip / test.skip / describe.skip / context.skip / xit / xdescribe.
# .only is explicitly NOT a skip.
_JS_DOT_SKIP = re.compile(r"\b(it|test|describe|context)\.skip\s*\(")
_JS_XIT = re.compile(r"\bxit\s*\(")
_JS_XDESCRIBE = re.compile(r"\bxdescribe\s*\(")
# title string literal as the first arg to a test/describe call.
_JS_TITLE = re.compile(r"""\(\s*(['"`])(.*?)\1""")

_SOL_VM_SKIP = re.compile(r"\bvm\.skip\s*\(\s*true\s*\)")
_SOL_FUNC = re.compile(r"function\s+(test\w*|invariant\w*)\b")

# Inline string-literal reason (Go t.Skip("..."), JS title, Rust #[ignore = "..."]).
_STR_ARG = re.compile(r"""(['"`])(.*?)\1""")
_RUST_IGNORE_REASON = re.compile(r"""#\s*\[\s*ignore\s*=\s*(['"])(.*?)\1""")


def _rel(ws: Path, p: Path) -> str:
    try:
        return p.relative_to(ws).as_posix()
    except ValueError:
        return p.as_posix()


def _read_text(p: Path) -> str | None:
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


# ---------------------------------------------------------------------------
# Scope resolution (canonical contract, reuse existing tooling).
# ---------------------------------------------------------------------------
def _load_scope_json(ws: Path):
    p = ws / "scope.json"
    if not p.is_file():
        return None
    try:
        obj = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(obj, dict):
        return None
    ins = [str(x) for x in (obj.get("in_scope") or []) if isinstance(x, str)]
    oos = [str(x) for x in (obj.get("out_of_scope") or []) if isinstance(x, str)]
    if not ins:
        return None
    return {"in_scope": ins, "out_of_scope": oos}


def _load_manifest_roots(ws: Path):
    """Fallback: derive in-scope roots from inscope_units.jsonl rows + lang hints."""
    p = ws / ".auditooor" / "inscope_units.jsonl"
    if not p.is_file():
        return None
    roots: set[str] = set()
    lang_by_dir: dict[str, str] = {}
    try:
        with p.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except (ValueError, TypeError):
                    continue
                if not isinstance(row, dict):
                    continue
                f = row.get("file") or row.get("path")
                if not isinstance(f, str) or not f.strip():
                    continue
                f = f.strip().replace("\\", "/").lstrip("./")
                roots.add(f)
                parent = str(Path(f).parent.as_posix())
                if parent and parent != ".":
                    roots.add(parent)
                    lng = row.get("lang")
                    if isinstance(lng, str) and lng:
                        lang_by_dir.setdefault(parent, lng)
    except OSError:
        return None
    if not roots:
        return None
    return {"roots": sorted(roots), "lang_by_dir": lang_by_dir}


def _oos_prefix_match(rel: str, oos_prefixes: list[str], in_prefixes: list[str]) -> bool:
    """True iff ``rel`` is excluded by an OOS prefix (longest-prefix wins)."""
    rel_n = rel.replace("\\", "/").lstrip("./")
    best_in = max((p for p in in_prefixes if rel_n == p or rel_n.startswith(p + "/")),
                  key=len, default=None)
    best_oos = max((p for p in oos_prefixes if rel_n == p or rel_n.startswith(p + "/")),
                   key=len, default=None)
    if best_oos is None:
        return False
    if best_in is None:
        return True
    return len(best_oos) > len(best_in)


# ---------------------------------------------------------------------------
# Language dispatch.
# ---------------------------------------------------------------------------
_LANG_BY_SUFFIX = {
    ".go": "go",
    ".rs": "rust",
    ".js": "js", ".ts": "js", ".jsx": "js", ".tsx": "js",
    ".sol": "solidity",
}


def _lang_of(path: Path) -> str | None:
    return _LANG_BY_SUFFIX.get(path.suffix.lower())


def _is_scaffold(rel: str, head: str) -> bool:
    norm = "/" + rel.replace("\\", "/").lstrip("/")
    for seg in _SCAFFOLD_PATH_SEGMENTS:
        if "/" + seg + "/" in norm or norm.endswith("/" + seg):
            return True
    head_low = head[:4096]
    for m in _SCAFFOLD_HEAD_MARKERS:
        if m in head_low:
            return True
    return False


def _backward_func(lines: list[str], idx: int, rx: re.Pattern, group: int = 1) -> str | None:
    for j in range(idx, -1, -1):
        m = rx.search(lines[j])
        if m:
            return m.group(group)
    return None


def _str_reason(line: str) -> str:
    m = _STR_ARG.search(line)
    return m.group(2) if m else ""


def _scan_go(lines: list[str]):
    for i, line in enumerate(lines):
        hit = None
        if _GO_SKIP.search(line):
            hit = "t.Skip"
        elif _GO_TESTUTIL_SKIP.search(line):
            hit = "testutil.Skip"
        if hit is None:
            continue
        name = _backward_func(lines, i, _GO_FUNC)
        yield {"line": i + 1, "marker": hit, "test_name": name,
               "skip_reason": _str_reason(line)}


def _scan_rust(lines: list[str]):
    for i, line in enumerate(lines):
        hit = None
        reason = ""
        if _RUST_IGNORE.search(line):
            hit = "#[ignore]"
            rm = _RUST_IGNORE_REASON.search(line)
            if rm:
                reason = rm.group(2)
        elif _RUST_RETURN_IGNORED.search(line):
            hit = "return-ignored"
        if hit is None:
            continue
        # enclosing fn: scan FORWARD a little (attribute precedes fn) then back.
        name = None
        for j in range(i + 1, min(i + 8, len(lines))):
            m = _RUST_FN.search(lines[j])
            if m:
                name = m.group(1)
                break
        if name is None:
            name = _backward_func(lines, i, _RUST_FN)
        yield {"line": i + 1, "marker": hit, "test_name": name, "skip_reason": reason}


def _scan_js(lines: list[str]):
    for i, line in enumerate(lines):
        hit = None
        if _JS_DOT_SKIP.search(line):
            # capture the verb.skip form precisely
            mm = _JS_DOT_SKIP.search(line)
            verb = mm.group(1)
            hit = f"{verb}.skip"
        elif _JS_XIT.search(line):
            hit = "xit"
        elif _JS_XDESCRIBE.search(line):
            hit = "xdescribe"
        if hit is None:
            continue
        tm = _JS_TITLE.search(line)
        title = tm.group(2) if tm else None
        yield {"line": i + 1, "marker": hit, "test_name": title, "skip_reason": ""}


def _scan_solidity(lines: list[str]):
    for i, line in enumerate(lines):
        if not _SOL_VM_SKIP.search(line):
            continue
        name = _backward_func(lines, i, _SOL_FUNC)
        yield {"line": i + 1, "marker": "vm.skip", "test_name": name, "skip_reason": ""}


_SCANNERS = {
    "go": _scan_go,
    "rust": _scan_rust,
    "js": _scan_js,
    "solidity": _scan_solidity,
}


# ---------------------------------------------------------------------------
# In-scope symbol attribution (the value-add over a raw grep).
# ---------------------------------------------------------------------------
def _sibling_impl(rel: str, lang: str) -> str | None:
    """Strip the test suffix to find the sibling implementation file rel path."""
    p = Path(rel)
    name = p.name
    impl = None
    if lang == "go" and name.endswith("_test.go"):
        impl = name[:-len("_test.go")] + ".go"
    elif lang == "js":
        for suf in (".test.ts", ".test.js", ".test.tsx", ".test.jsx",
                    ".spec.ts", ".spec.js"):
            if name.endswith(suf):
                impl = name[:-len(suf)] + suf[suf.rfind("."):]
                break
    elif lang == "solidity" and name.endswith(".t.sol"):
        impl = name[:-len(".t.sol")] + ".sol"
    elif lang == "rust" and name == "tests.rs":
        impl = "lib.rs"
    if impl is None:
        return None
    return (p.parent / impl).as_posix()


def _symbol_tokens(test_name: str | None) -> list[str]:
    if not test_name:
        return []
    n = test_name
    for pfx in ("Test", "Fuzz", "Benchmark", "test_", "test", "invariant_", "invariant"):
        if n.startswith(pfx):
            n = n[len(pfx):]
            break
    return [t for t in re.split(r"[^A-Za-z0-9]+", n) if t]


def _attribute(row: dict, rel: str, lang: str, ws: Path,
               manifest_files: set[str], manifest_norm: set[str]):
    exercises_file = None
    impl = _sibling_impl(rel, lang)
    if impl and (impl in manifest_files or (ws / impl).is_file()):
        exercises_file = impl
    exercises_symbol = None
    exercises_inscope_unit = None
    attribution = "unresolved"
    tokens = _symbol_tokens(row.get("test_name"))
    if tokens and manifest_norm:
        # match a manifest row whose file or function contains the tokens.
        for fl, fn in manifest_norm:
            hay = (fl + " " + (fn or "")).lower()
            if all(t.lower() in hay for t in tokens):
                exercises_symbol = tokens[0]
                exercises_inscope_unit = fl
                attribution = "resolved"
                break
    if exercises_symbol is None and exercises_file is not None:
        # sibling impl resolved even if symbol grep failed -> partial resolve.
        exercises_symbol = tokens[0] if tokens else None
        attribution = "resolved" if exercises_file else "unresolved"
    return {
        "exercises_file": exercises_file,
        "exercises_symbol": exercises_symbol,
        "exercises_inscope_unit": exercises_inscope_unit,
        "attribution": attribution,
    }


def _load_manifest_pairs(ws: Path):
    """Return (set of file rels, list of (file_line, function) for attribution)."""
    p = ws / ".auditooor" / "inscope_units.jsonl"
    files: set[str] = set()
    pairs: list[tuple[str, str]] = []
    if not p.is_file():
        return files, pairs
    try:
        with p.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except (ValueError, TypeError):
                    continue
                if not isinstance(row, dict):
                    continue
                f = row.get("file") or row.get("path")
                if isinstance(f, str) and f.strip():
                    fr = f.strip().replace("\\", "/").lstrip("./")
                    files.add(fr)
                fl = row.get("file_line") or row.get("file") or ""
                fn = row.get("function") or row.get("fn") or ""
                if isinstance(fl, str) and fl:
                    pairs.append((fl.replace("\\", "/").lstrip("./"),
                                  str(fn) if fn else ""))
    except OSError:
        pass
    return files, pairs


# ---------------------------------------------------------------------------
# Walk + analyze.
# ---------------------------------------------------------------------------
def _walk_candidates(root: Path):
    if root.is_file():
        yield root
        return
    if not root.is_dir():
        return
    for p in root.rglob("*"):
        if p.is_dir():
            continue
        parts = set(p.parts)
        if parts & _PRUNE_DIRS:
            continue
        if _lang_of(p) is not None:
            yield p


def analyze(ws: Path, *, write: bool = True) -> dict:
    ws = Path(ws)
    scope = _load_scope_json(ws)
    in_prefixes: list[str] = []
    oos_prefixes: list[str] = []
    roots: list[Path] = []
    in_scope_roots: list[str] = []
    manifest_lang: dict[str, str] = {}

    if scope is not None:
        in_prefixes = [s.replace("\\", "/").lstrip("./") for s in scope["in_scope"]]
        oos_prefixes = [s.replace("\\", "/").lstrip("./") for s in scope["out_of_scope"]]
        for rel in in_prefixes:
            r = ws / rel
            if r.exists():
                roots.append(r)
                in_scope_roots.append(rel)
    else:
        mani = _load_manifest_roots(ws)
        if mani is None:
            return {
                "schema": RESULT_SCHEMA,
                "workspace": str(ws),
                "verdict": "scan-error",
                "n_markers": 0,
                "n_excluded_scaffold": 0,
                "rows": [],
                "by_lang": {},
                "in_scope_roots": [],
                "reason": "no scope: neither scope.json nor .auditooor/inscope_units.jsonl is readable",
            }
        manifest_lang = mani["lang_by_dir"]
        # walk parent dirs (roots), de-dup nested ones
        rel_roots = sorted(set(mani["roots"]))
        # keep only the shallowest unique dirs to avoid re-walking nested files
        dirs = sorted({r for r in rel_roots if (ws / r).is_dir()})
        pruned: list[str] = []
        for d in dirs:
            if any(d != o and d.startswith(o + "/") for o in dirs):
                continue
            pruned.append(d)
        for rel in pruned:
            roots.append(ws / rel)
            in_scope_roots.append(rel)

    manifest_files, manifest_pairs = _load_manifest_pairs(ws)
    manifest_norm = set(manifest_pairs)

    rows: list[dict] = []
    n_excluded = 0
    by_lang: dict[str, int] = {}
    seen_files: set[Path] = set()

    for root in roots:
        for fp in _walk_candidates(root):
            if fp in seen_files:
                continue
            seen_files.add(fp)
            rel = _rel(ws, fp)
            # OOS exclusion: scope.json prefix (longest-prefix wins) ...
            if scope is not None and _oos_prefix_match(rel, oos_prefixes, in_prefixes):
                continue
            # ... plus the shared categorical-OOS markers (vendored/generated).
            # NOTE: we deliberately do NOT call is_test here - test files are
            # exactly what we WANT to scan (skipped tests live in test files).
            if _is_vendored(rel) or _is_generated(rel) or _is_tool_artifact(rel):
                continue
            lang = _lang_of(fp)
            if lang is None:
                continue
            text = _read_text(fp)
            if text is None:
                continue
            lines = text.splitlines()
            head = text[:4096]
            scanner = _SCANNERS[lang]
            matched_any = False
            scaffold = _is_scaffold(rel, head)
            for hit in scanner(lines):
                matched_any = True
                if scaffold:
                    continue
                attr = _attribute(hit, rel, lang, ws, manifest_files, manifest_norm)
                row = {
                    "schema": SCHEMA,
                    "file": rel,
                    "line": hit["line"],
                    "marker": hit["marker"],
                    "lang": lang,
                    "test_name": hit.get("test_name"),
                    "skip_reason": hit.get("skip_reason") or "",
                    "exercises_file": attr["exercises_file"],
                    "exercises_symbol": attr["exercises_symbol"],
                    "exercises_inscope_unit": attr["exercises_inscope_unit"],
                    "attribution": attr["attribution"],
                    "disposition": "open",
                }
                rows.append(row)
                by_lang[lang] = by_lang.get(lang, 0) + 1
            if scaffold and matched_any:
                n_excluded += 1

    n = len(rows)
    verdict = "pass-skipped-test-scan-clean" if n == 0 else "found-skipped-tests"
    result = {
        "schema": RESULT_SCHEMA,
        "workspace": str(ws),
        "verdict": verdict,
        "n_markers": n,
        "n_excluded_scaffold": n_excluded,
        "rows": rows,
        "by_lang": by_lang,
        "in_scope_roots": in_scope_roots,
        "reason": (
            "no skipped/disabled tests found in the in-scope test corpus"
            if n == 0 else
            f"{n} developer-confessed skipped/disabled test(s) found across "
            f"{len(by_lang)} language arm(s); each is a per-function hunt seed "
            "(disposition enforced by skipped-test-disposition-gate.py)"
        ),
    }

    if write:
        out_dir = ws / ".auditooor"
        try:
            out_dir.mkdir(parents=True, exist_ok=True)
            with (ws / ARTIFACT_REL).open("w", encoding="utf-8") as fh:
                for row in rows:
                    fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            (ws / RESULT_REL).write_text(
                json.dumps({k: v for k, v in result.items() if k != "rows"} |
                           {"n_rows": n}, indent=2),
                encoding="utf-8",
            )
        except OSError:
            pass

    return result


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Discovery scanner for developer-confessed skipped/disabled tests.")
    ap.add_argument("--workspace", "--ws", required=True, dest="workspace")
    ap.add_argument("--check", action="store_true",
                    help="exit 2 ONLY if the scan cannot run (scope unreadable); never on found markers")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--no-write", action="store_true",
                    help="do not write artifacts under <ws>/.auditooor/")
    args = ap.parse_args()

    ws = Path(args.workspace).expanduser().resolve()
    if not ws.is_dir():
        print(f"[skipped-test-marker-scan] ERROR: workspace not found: {ws}", file=sys.stderr)
        return 2

    res = analyze(ws, write=not args.no_write)

    if args.json:
        print(json.dumps(res, indent=2))
    else:
        print(f"[skipped-test-marker-scan] verdict={res['verdict']}")
        print(f"  in-scope roots: {res['in_scope_roots'] or 'NONE'}")
        print(f"  skipped tests found: {res['n_markers']}  (excluded scaffold files: {res['n_excluded_scaffold']})")
        for lang, c in sorted(res.get("by_lang", {}).items()):
            print(f"    [{lang}] {c}")
        for row in res.get("rows", [])[:40]:
            print(f"    {row['file']}:{row['line']} [{row['marker']}] "
                  f"{row.get('test_name') or '?'} -> "
                  f"{row.get('exercises_inscope_unit') or row.get('exercises_file') or 'unresolved'}")
        if res["verdict"] == "scan-error":
            print(f"  SCAN-ERROR: {res['reason']}", file=sys.stderr)

    # --check: rc 2 only on a genuine scan-cannot-run error; discovery != failure.
    if args.check and res["verdict"] == "scan-error":
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
