#!/usr/bin/env bash
# stop-criteria-check.sh — evaluate the auditooor stop criteria (R47).
#
# Each criterion is reported as PASS / FAIL / UNKNOWN with a short reason.
# Adding a criterion = adding one `check_Cx` function + one call in `main`.
#
# Current criteria:
#   C1  real-engagement TP count (≥ baseline + Δ)
#   C2  Tier-S detector count (≥ floor)
#   C3  DSL pattern count (≥ floor)
#   C4  cycle-time: mean scan_complete → draft_ready minutes ≤ threshold
#   C5  canonical flow reachable via `make engage` / `tools/engage.py --dry-run --summary`
#
# Source of truth for C4 is reference/timing_ledger.yaml, written by
# tools/time-engagement.sh.
#
# Usage:
#   ./tools/stop-criteria-check.sh [--json] [--threshold-minutes N]
#
# Exit code:
#   0 — all criteria PASS
#   1 — at least one criterion FAIL
#   2 — usage error

set -u

JSON=0
C4_THRESHOLD=180  # minutes; scan → first draft in under 3h is the target.

while [ $# -gt 0 ]; do
    case "$1" in
        --json) JSON=1; shift ;;
        --threshold-minutes) C4_THRESHOLD="$2"; shift 2 ;;
        -h|--help) sed -n '1,30p' "$0"; exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

AUDITOOOR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LEDGER="$AUDITOOOR_DIR/reference/timing_ledger.yaml"

# --- criteria state ---
declare -a KEYS STATUSES REASONS
emit() {
    KEYS+=("$1"); STATUSES+=("$2"); REASONS+=("$3")
}

# ---------- C1: real-engagement TP ----------
check_C1() {
    local hits="$AUDITOOOR_DIR/detectors/_hits_ledger.yaml"
    if [ ! -f "$hits" ]; then
        emit C1 UNKNOWN "detectors/_hits_ledger.yaml missing"
        return
    fi
    local tp
    tp=$(grep -E '^\s+tp: [0-9]+' "$hits" 2>/dev/null | awk '{s+=$2} END {print s+0}')
    if [ "$tp" -ge 2 ]; then
        emit C1 PASS "real_tp=$tp (baseline 2)"
    else
        emit C1 FAIL "real_tp=$tp < 2"
    fi
}

# ---------- C2: Tier-S count ----------
check_C2() {
    local reg="$AUDITOOOR_DIR/detectors/_tier_registry.yaml"
    if [ ! -f "$reg" ]; then
        emit C2 UNKNOWN "_tier_registry.yaml missing"
        return
    fi
    local s
    s=$(grep -c "^    tier: S$" "$reg" 2>/dev/null || echo 0)
    if [ "$s" -ge 1 ]; then
        emit C2 PASS "tier_s=$s"
    else
        emit C2 FAIL "tier_s=$s < 1"
    fi
}

# ---------- C3: TP-per-detector-hits ratio (R49) ----------
# R49: C3 is now the semantic stop criterion "≥1 TP per 50 detector hits".
# Source of truth: reference/c3_status.txt, written by tools/c3-compute.sh.
# The first non-comment line after the header table's GLOBAL row tells us the
# verdict. If c3_status.txt hasn't been regenerated by c3-compute.sh yet we
# fall back to UNKNOWN and tell the operator how to compute it.
check_C3() {
    local status_file="$AUDITOOOR_DIR/reference/c3_status.txt"
    if [ ! -f "$status_file" ]; then
        emit C3 UNKNOWN "reference/c3_status.txt missing — run tools/c3-compute.sh"
        return
    fi
    # Accepts either the legacy "Verdict: PASS|FAIL" (R49) or the R50 scoped
    # format "Verdict (scoped): PASS|FAIL"; scoped takes precedence when both
    # are present. If neither is found, emit UNKNOWN.
    local verdict reason
    verdict=$(grep -oE '^Verdict \(scoped\):[[:space:]]+(PASS|FAIL)' "$status_file" 2>/dev/null | head -1 | awk '{print $3}')
    if [ -z "${verdict:-}" ]; then
        verdict=$(grep -oE '^Verdict:[[:space:]]+(PASS|FAIL)' "$status_file" 2>/dev/null | head -1 | awk '{print $2}')
    fi
    if [ -z "${verdict:-}" ]; then
        emit C3 UNKNOWN "c3_status.txt has no Verdict line — run tools/c3-compute.sh"
        return
    fi
    # Parse GLOBAL row — R50 format has 6 columns (raw_hits scoped tp raw_ratio scoped_ratio),
    # R49 format has 4 (hits tp ratio). Detect by field count.
    reason=$(awk '/^GLOBAL \(sum\)/ {
                     if (NF >= 7) {
                         # R50 scoped: raw_hits scoped tp raw_ratio scoped_ratio
                         printf "scoped ratio=%s (tp=%s / scoped_hits=%s)", $NF, $(NF-2), $(NF-3)
                     } else {
                         # R49 legacy: hits tp ratio
                         printf "global ratio=%s (tp=%s / hits=%s)", $NF, $(NF-1), $(NF-2)
                     }
                     exit
                  }' "$status_file")
    [ -z "$reason" ] && reason="see reference/c3_status.txt"
    emit C3 "$verdict" "$reason"
}

# ---------- C3_DSL: DSL pattern count (kept as auxiliary signal) ----------
check_C3_DSL() {
    local n
    n=$(LC_ALL=C ls -1 "$AUDITOOOR_DIR/reference/patterns.dsl/" 2>/dev/null \
          | grep -E '\.yaml$' | grep -v '__pycache__' | wc -l | tr -d ' ')
    if [ "$n" -ge 186 ]; then
        emit C3_DSL PASS "dsl_patterns=$n (baseline 186)"
    else
        emit C3_DSL FAIL "dsl_patterns=$n < 186"
    fi
}

# ---------- C4: cycle-time (scan → draft) ----------
# Reads reference/timing_ledger.yaml; for each workspace, finds the earliest
# scan_complete and the earliest subsequent draft_ready, computes the delta in
# minutes, then means over all workspaces.
check_C4() {
    if [ ! -f "$LEDGER" ]; then
        emit C4 UNKNOWN "timing_ledger.yaml missing"
        return
    fi

    # Portable: use python if available (richer, handles ISO-8601 cleanly),
    # else an awk fallback. Python is present in every dev env we ship to.
    if command -v python3 >/dev/null 2>&1; then
        local out
        out=$(python3 - "$LEDGER" "$C4_THRESHOLD" <<'PY'
import sys, re, datetime as dt

path = sys.argv[1]
thresh = float(sys.argv[2])

# Minimal YAML parse — we control the schema via time-engagement.sh so a line
# grep is safe and avoids a PyYAML dep.
events = []
cur = {}
with open(path) as f:
    for line in f:
        line = line.rstrip("\n")
        m = re.match(r"\s*-\s+workspace:\s*(.+)", line)
        if m:
            if cur: events.append(cur)
            cur = {"workspace": m.group(1).strip()}
            continue
        m = re.match(r"\s+event:\s*(.+)", line)
        if m: cur["event"] = m.group(1).strip(); continue
        m = re.match(r"\s+timestamp:\s*(.+)", line)
        if m: cur["timestamp"] = m.group(1).strip(); continue
    if cur: events.append(cur)

def parse(ts):
    try:
        return dt.datetime.strptime(ts, "%Y-%m-%dT%H:%M:%SZ")
    except Exception:
        return None

by_ws = {}
for e in events:
    ws = e.get("workspace"); ev = e.get("event"); ts = parse(e.get("timestamp","") or "")
    if not ws or not ev or ts is None: continue
    by_ws.setdefault(ws, []).append((ts, ev))

deltas = []
for ws, rows in by_ws.items():
    rows.sort()
    scan_t = None
    for ts, ev in rows:
        if ev == "scan_complete" and scan_t is None:
            scan_t = ts
        elif ev == "draft_ready" and scan_t is not None:
            deltas.append((ts - scan_t).total_seconds() / 60.0)
            scan_t = None  # reset; next scan→draft cycle starts fresh

if not deltas:
    print("UNKNOWN|no scan→draft pairs in ledger")
else:
    mean = sum(deltas) / len(deltas)
    status = "PASS" if mean <= thresh else "FAIL"
    print(f"{status}|mean_scan_to_draft={mean:.1f}min "
          f"(n={len(deltas)}, threshold={thresh:.0f}min)")
PY
        )
        local status reason
        status="${out%%|*}"; reason="${out#*|}"
        emit C4 "$status" "$reason"
    else
        # Awk fallback: count paired events per workspace, don't compute minutes
        # (awk ISO-8601 arithmetic is painful — fail-soft to UNKNOWN).
        emit C4 UNKNOWN "python3 unavailable; install for timing stats"
    fi
}

# ---------- C5: canonical engage entrypoint ----------
check_C5() {
    local mk="$AUDITOOOR_DIR/Makefile"
    local engage_py="$AUDITOOOR_DIR/tools/engage.py"
    if [ ! -f "$mk" ]; then
        emit C5 FAIL "Makefile missing"
        return
    fi
    if [ ! -f "$engage_py" ]; then
        emit C5 FAIL "tools/engage.py missing"
        return
    fi
    if ! grep -q '^engage:' "$mk"; then
        emit C5 FAIL "Makefile has no engage target"
        return
    fi
    if ! grep -q 'argparse' "$engage_py" || ! grep -q -- '--dry-run' "$engage_py"; then
        emit C5 FAIL "tools/engage.py missing expected CLI surface (--dry-run)"
        return
    fi
    emit C5 PASS "canonical entrypoint present: make engage + tools/engage.py --dry-run --summary"
}

# ---------- main ----------
check_C1
check_C2
check_C3
check_C3_DSL
check_C4
check_C5

FAILS=0
for s in "${STATUSES[@]}"; do
    [ "$s" = "FAIL" ] && FAILS=$((FAILS+1))
done

if [ "$JSON" = 1 ]; then
    printf '{\n  "criteria": [\n'
    i=0
    last=$((${#KEYS[@]} - 1))
    for i in "${!KEYS[@]}"; do
        printf '    {"id": "%s", "status": "%s", "reason": %s}' \
            "${KEYS[$i]}" "${STATUSES[$i]}" \
            "$(printf '%s' "${REASONS[$i]}" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))' 2>/dev/null || echo \"${REASONS[$i]}\")"
        [ "$i" -lt "$last" ] && printf ','
        printf '\n'
    done
    printf '  ],\n  "fails": %d\n}\n' "$FAILS"
else
    echo "=== auditooor stop-criteria check ==="
    for i in "${!KEYS[@]}"; do
        printf "  [%s] %s — %s\n" "${STATUSES[$i]}" "${KEYS[$i]}" "${REASONS[$i]}"
    done
    echo ""
    echo "FAILs: $FAILS"
fi

[ "$FAILS" -gt 0 ] && exit 1
exit 0
