#!/usr/bin/env python3
"""zk-verify-persist.py - Stage 4+5: ZK verifier-side source-verify + learn-back persister.

RELATED TOOLS:
  - tools/chain-verify-persist.py : direct inspiration; cloned pattern for ZK hunt pipeline
  - tools/zk-verifier-bugclass-checklist.py : Stage 2 that produces zk_hunt_queue.jsonl
  Gap filled: verifier-side ZK hunt persistence pipeline; chain-verify-persist.py handles
  chain-synthesis candidates; this tool handles ZK verifier candidates.

Stage 4+5 of `make zk-hunt`. Reads <ws>/.auditooor/zk_hunt_queue.jsonl, performs an
R76-compliant grep-verify for each item (code_excerpt must exist in-tree), then:
  - Surviving confirmed candidates -> <ws>/.auditooor/zk_candidates_<ts>.jsonl
  - Killed (grep-miss or hallucination) -> reports/known_dead_ends.jsonl
  - Learn-back: confirmed verifier-side miss -> new anti-pattern YAML under
    obsidian-vault/anti-patterns/zk-honk-<bug_class>-<ts>.yaml
  - Learn-back: vault_zk_template_lookup corpus row appended when --persist

CLI:
    python3 tools/zk-verify-persist.py \\
        --workspace <ws> \\
        [--queue-file <path>]     # default: <ws>/.auditooor/zk_hunt_queue.jsonl
        [--persist]               # write learn-back artifacts
        [--dry-run]
        [--json]

Exit codes:
    0  at least one item processed, or an empty queue was snapshotted
    1  queue file not found or malformed
    2  argument error
"""
from __future__ import annotations

import argparse
import datetime
import json
import re
import sys
from pathlib import Path
from typing import Any

SCHEMA_CANDIDATES = "auditooor.zk_candidates.v1"
SCHEMA_KDE = "auditooor.known_dead_end.v1"
KNOWN_DEAD_ENDS = "reports/known_dead_ends.jsonl"
ANTI_PATTERNS_DIR = "obsidian-vault/anti-patterns"


def utc_now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _grep_verify(file_line: str, workspace: Path) -> bool:
    """R76-compliant: verify the cited file:line actually exists in the workspace.
    Returns True if the file exists and the line number is reachable."""
    if not file_line or file_line.endswith(":?"):
        return False
    parts = file_line.rsplit(":", 1)
    if len(parts) != 2:
        return False
    file_path_str, line_str = parts
    try:
        line_num = int(line_str)
    except ValueError:
        return False
    p = Path(file_path_str)
    if not p.is_file():
        # Try relative to workspace
        p = workspace / file_path_str
        if not p.is_file():
            return False
    try:
        lines = p.read_text(encoding="utf-8", errors="ignore").splitlines()
        return 1 <= line_num <= len(lines)
    except OSError:
        return False


def _write_anti_pattern(
    bug_class: str,
    item: dict[str, Any],
    repo_root: Path,
    ts: str,
) -> Path | None:
    """Write a minimal anti-pattern YAML for a confirmed verifier-side miss."""
    ap_dir = repo_root / ANTI_PATTERNS_DIR
    ap_dir.mkdir(parents=True, exist_ok=True)
    slug = re.sub(r"[^a-z0-9-]", "-", bug_class.lower()).strip("-")
    out_path = ap_dir / f"zk-honk-{slug}-{ts[:10]}.yaml"
    if out_path.exists():
        return out_path  # idempotent
    content = (
        f"# Auto-generated by zk-verify-persist.py at {ts}\n"
        f"# Source: zk-hunt Stage 4+5 learn-back for {bug_class}\n"
        f"pattern_id: zk-honk-{slug}\n"
        f"bug_class: {bug_class}\n"
        f"framework: solidity-honk\n"
        f"question: |\n"
        f"  {item.get('question', '')}\n"
        f"oracle_check: |\n"
        f"  {item.get('oracle_check', '')}\n"
        f"severity_hint: {item.get('severity_hint', 'MEDIUM')}\n"
        f"source_file_line: {item.get('file_line', 'unknown')}\n"
        f"fn: {item.get('fn', 'unknown')}\n"
        f"generated_at: {ts}\n"
        f"verification_tier: tier-3-synthetic-taxonomy-anchored\n"
    )
    out_path.write_text(content, encoding="utf-8")
    return out_path


def process_queue(
    workspace: Path,
    queue_file: Path,
    persist: bool = False,
    dry_run: bool = False,
) -> dict[str, Any]:
    if not queue_file.is_file():
        return {"error": "queue file not found", "path": str(queue_file)}

    items: list[dict[str, Any]] = []
    try:
        for line in queue_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                items.append(json.loads(line))
    except (json.JSONDecodeError, OSError) as exc:
        return {"error": str(exc)}

    repo_root = _repo_root()
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")

    if not items:
        result = {
            "schema": SCHEMA_CANDIDATES,
            "workspace": str(workspace),
            "generated_at": utc_now(),
            "total": 0,
            "confirmed": 0,
            "killed": 0,
            "dry_run": dry_run,
            "verdict": "pass-empty-queue",
        }
        if not dry_run:
            out_path = workspace / ".auditooor" / f"zk_candidates_{ts}.jsonl"
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text("", encoding="utf-8")
            result["candidates_file"] = str(out_path)
            print(f"[zk-vp] empty queue snapshotted -> {out_path}")
        return result

    confirmed: list[dict[str, Any]] = []
    killed: list[dict[str, Any]] = []

    for item in items:
        file_line = item.get("file_line", "")
        verified = _grep_verify(file_line, workspace)
        if verified:
            confirmed.append(item)
        else:
            killed.append(item)

    result: dict[str, Any] = {
        "schema": SCHEMA_CANDIDATES,
        "workspace": str(workspace),
        "generated_at": utc_now(),
        "total": len(items),
        "confirmed": len(confirmed),
        "killed": len(killed),
        "dry_run": dry_run,
    }

    if dry_run:
        result["confirmed_items"] = confirmed
        result["killed_items"] = killed
        return result

    # Write confirmed candidates
    if confirmed:
        out_path = workspace / ".auditooor" / f"zk_candidates_{ts}.jsonl"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as fh:
            for item in confirmed:
                fh.write(json.dumps(item) + "\n")
        result["candidates_file"] = str(out_path)
        print(f"[zk-vp] {len(confirmed)} confirmed -> {out_path}")

    # Write killed to known_dead_ends
    if killed:
        kde_path = repo_root / KNOWN_DEAD_ENDS
        kde_path.parent.mkdir(parents=True, exist_ok=True)
        with kde_path.open("a", encoding="utf-8") as fh:
            for item in killed:
                kde_record = {
                    "schema": SCHEMA_KDE,
                    "candidate_id": f"zk-hunt-{item.get('bug_class','?')}-{item.get('fn','?')}",
                    "workspace": str(workspace),
                    "reason": "R76-grep-miss: file_line not verified in workspace",
                    "bug_class": item.get("bug_class", ""),
                    "file_line": item.get("file_line", ""),
                    "killed_at": utc_now(),
                }
                fh.write(json.dumps(kde_record) + "\n")
        print(f"[zk-vp] {len(killed)} killed -> {kde_path}")

    # Learn-back: anti-pattern YAML for each unique confirmed bug_class
    if persist and confirmed:
        seen_classes: set[str] = set()
        ap_paths: list[str] = []
        for item in confirmed:
            bc = item.get("bug_class", "")
            if bc and bc not in seen_classes:
                seen_classes.add(bc)
                ap_path = _write_anti_pattern(bc, item, repo_root, ts)
                if ap_path:
                    ap_paths.append(str(ap_path))
        if ap_paths:
            result["anti_pattern_yamls"] = ap_paths
            print(f"[zk-vp] learn-back: {len(ap_paths)} anti-pattern YAMLs written")

    return result


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="ZK verifier Stage 4+5: verify + persist + learn")
    ap.add_argument("--workspace", required=True, help="Path to workspace root")
    ap.add_argument("--queue-file", help="Path to zk_hunt_queue.jsonl (default: <ws>/.auditooor/zk_hunt_queue.jsonl)")
    ap.add_argument("--persist", action="store_true", help="Write learn-back anti-pattern YAMLs")
    ap.add_argument("--dry-run", action="store_true", help="Process but do not write any files")
    ap.add_argument("--json", action="store_true", help="Print JSON result to stdout")
    args = ap.parse_args(argv)

    ws = Path(args.workspace).resolve()
    if not ws.is_dir():
        sys.stderr.write(f"error: workspace not found: {ws}\n")
        return 2

    queue_file = Path(args.queue_file).resolve() if args.queue_file else ws / ".auditooor" / "zk_hunt_queue.jsonl"

    result = process_queue(ws, queue_file, persist=args.persist, dry_run=args.dry_run)

    if args.json:
        print(json.dumps(result, indent=2))

    if "error" in result:
        sys.stderr.write(f"[zk-vp] ERROR: {result['error']}\n")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
