#!/usr/bin/env python3
"""capability-v3 iter-001 T4 — ERC4626 vault invariant campaign.

Concrete, compilable Foundry invariant harnesses emitted per
workspace. Unlike the v2 scaffolds under
`tools/invariants/families/vault/` these files are runnable: the
`setUp` wires a handler that pranks across a population of users,
and every `invariant_*` references a real ERC4626 property.

The `CANDIDATE HARNESS — NOT PROOF` banner stays in every file.
No harness elevates past candidate until `tools/fuzz-runner.sh`
(PR 107) runs it and a concrete status lands in the workspace
evidence matrix.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# ERC4626 detection
# ---------------------------------------------------------------------------

# A vault must expose enough of the ERC4626 surface to make all 5
# invariants meaningful. A contract that implements only one or two
# of these methods is not an ERC4626 vault and the campaign refuses
# to emit against it (hard-negative per the playbook).
ERC4626_REQUIRED_METHODS = (
    "convertToShares",
    "convertToAssets",
    "deposit",
    "withdraw",
    "redeem",
    "mint",
    "totalAssets",
    "totalSupply",
)


def detect_erc4626(source: str) -> tuple[bool, list[str]]:
    """Return (is_vault, missing_methods).

    Detection is intentionally cheap: a plain substring scan over the
    concatenated `src/**/*.sol` text. Importing an interface (e.g.
    `IERC4626`) is sufficient because the method names appear in the
    interface declaration. Sensitivity is preferred over precision
    here — false positives are cheap (the reviewer inspects the
    emitted harnesses) but false negatives miss real campaigns.
    """
    missing = [m for m in ERC4626_REQUIRED_METHODS if m not in source]
    return (not missing, missing)


# ---------------------------------------------------------------------------
# Harness bodies
# ---------------------------------------------------------------------------
#
# Each harness is a self-contained Foundry invariant file. The shared
# prelude deploys a mock ERC20 underlying, the vault under test, and
# a three-user handler that pranks across `deposit` / `withdraw` /
# `redeem` / `mint`. Every file carries the candidate-harness banner.
#
# `{ContractName}` is substituted per invocation and defaults to
# `Vault` when no --contract is supplied.

_BANNER = """// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

// =====================================================================
// CANDIDATE HARNESS — NOT PROOF
// ---------------------------------------------------------------------
// Generated by tools/attach-invariant.py --mode campaign --family vault.
// This file asserts one real ERC4626 property against the vault under
// test. It is a *candidate harness* only: a fuzz engine must exercise
// it and a concrete status must be recorded in the workspace evidence
// matrix before anyone cites the result as proof.
// =====================================================================
"""

# Shared prelude (imports + mock ERC20 + handler + common setUp). Every
# harness inlines it so each file is an independent Foundry test.
_SHARED_PRELUDE = r"""
import "forge-std/Test.sol";
import "forge-std/StdInvariant.sol";

import "../../src/{ContractName}.sol";

// Minimal mintable ERC20 used as the vault underlying asset. Living
// inline keeps the harness self-contained without depending on the
// workspace's own mock tree.
contract CampaignMockERC20 {
    string public name = "CampaignAsset";
    string public symbol = "CA";
    uint8 public decimals = 18;
    uint256 public totalSupply;
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);

    function mint(address to, uint256 amount) external {
        totalSupply += amount;
        balanceOf[to] += amount;
        emit Transfer(address(0), to, amount);
    }

    function approve(address spender, uint256 amount) external returns (bool) {
        allowance[msg.sender][spender] = amount;
        emit Approval(msg.sender, spender, amount);
        return true;
    }

    function transfer(address to, uint256 amount) external returns (bool) {
        _transfer(msg.sender, to, amount);
        return true;
    }

    function transferFrom(address from, address to, uint256 amount) external returns (bool) {
        uint256 a = allowance[from][msg.sender];
        require(a >= amount, "allowance");
        if (a != type(uint256).max) allowance[from][msg.sender] = a - amount;
        _transfer(from, to, amount);
        return true;
    }

    function _transfer(address from, address to, uint256 amount) internal {
        require(balanceOf[from] >= amount, "balance");
        balanceOf[from] -= amount;
        balanceOf[to] += amount;
        emit Transfer(from, to, amount);
    }
}

// Handler that pranks across a small user population and calls the
// four mutating ERC4626 paths. The fuzzer selects which path + user +
// amount to exercise; the handler bounds amounts to what the caller
// actually owns so the campaign is not dominated by trivial reverts.
contract VaultHandler is Test {
    CampaignMockERC20 public asset;
    address[] public users;
    address public vault;

    constructor(address vault_, address asset_, address[] memory users_) {
        vault = vault_;
        asset = CampaignMockERC20(asset_);
        users = users_;
    }

    function _pick(uint256 seed) internal view returns (address) {
        return users[seed % users.length];
    }

    function doDeposit(uint256 seed, uint256 amount) external {
        address u = _pick(seed);
        amount = bound(amount, 1, asset.balanceOf(u));
        if (amount == 0) return;
        vm.startPrank(u);
        asset.approve(vault, amount);
        (bool ok, ) = vault.call(
            abi.encodeWithSignature("deposit(uint256,address)", amount, u)
        );
        ok; // silence unused
        vm.stopPrank();
    }

    function doMint(uint256 seed, uint256 shares) external {
        address u = _pick(seed);
        shares = bound(shares, 1, 1_000 ether);
        vm.startPrank(u);
        asset.approve(vault, type(uint256).max);
        (bool ok, ) = vault.call(
            abi.encodeWithSignature("mint(uint256,address)", shares, u)
        );
        ok;
        vm.stopPrank();
    }

    function doWithdraw(uint256 seed, uint256 amount) external {
        address u = _pick(seed);
        (bool ok1, bytes memory data) = vault.staticcall(
            abi.encodeWithSignature("maxWithdraw(address)", u)
        );
        if (!ok1) return;
        uint256 cap = abi.decode(data, (uint256));
        if (cap == 0) return;
        amount = bound(amount, 1, cap);
        vm.startPrank(u);
        (bool ok, ) = vault.call(
            abi.encodeWithSignature("withdraw(uint256,address,address)", amount, u, u)
        );
        ok;
        vm.stopPrank();
    }

    function doRedeem(uint256 seed, uint256 shares) external {
        address u = _pick(seed);
        (bool ok1, bytes memory data) = vault.staticcall(
            abi.encodeWithSignature("maxRedeem(address)", u)
        );
        if (!ok1) return;
        uint256 cap = abi.decode(data, (uint256));
        if (cap == 0) return;
        shares = bound(shares, 1, cap);
        vm.startPrank(u);
        (bool ok, ) = vault.call(
            abi.encodeWithSignature("redeem(uint256,address,address)", shares, u, u)
        );
        ok;
        vm.stopPrank();
    }
}

abstract contract VaultCampaignBase is StdInvariant, Test {
    CampaignMockERC20 internal asset;
    {ContractName} internal vault;
    VaultHandler internal handler;

    address internal alice = address(0xA11CE);
    address internal bob = address(0xB0B);
    address internal carol = address(0xCAC01);

    address[] internal users;

    function _baseSetUp() internal {
        asset = new CampaignMockERC20();
        vault = new {ContractName}(address(asset));
        users.push(alice);
        users.push(bob);
        users.push(carol);
        for (uint256 i = 0; i < users.length; i++) {
            asset.mint(users[i], 1_000_000 ether);
        }
        // Prime: one seed deposit so share price is well-defined and
        // the first-deposit inflation path is already crossed before
        // the fuzzer starts.
        vm.startPrank(alice);
        asset.approve(address(vault), 100 ether);
        vault.deposit(100 ether, alice);
        vm.stopPrank();

        handler = new VaultHandler(address(vault), address(asset), users);
        targetContract(address(handler));
    }
}
"""


# --- I1: convertToShares ∘ convertToAssets ≈ identity (small amounts) ------
I1_BODY = r"""
contract VaultCampaignI1 is VaultCampaignBase {
    function setUp() public {
        _baseSetUp();
    }

    /// Round-trip no-profit: converting a small share amount to assets
    /// and back to shares returns at most the original share count.
    /// Strict equality is rare because of floor-division; the invariant
    /// permits a single-wei loss but no gain.
    function invariant_I1_convert_round_trip_no_profit() public view {
        uint256[5] memory probes = [uint256(1), 1e6, 1e12, 1e18, 7 * 1e18];
        for (uint256 i = 0; i < probes.length; i++) {
            uint256 assets = vault.convertToAssets(probes[i]);
            uint256 shares = vault.convertToShares(assets);
            assertLe(
                shares,
                probes[i],
                "I1: round-trip produced more shares than input"
            );
        }
    }
}
"""

# --- I2: totalAssets >= sum(convertToAssets(balanceOf(u)) for u) -----------
I2_BODY = r"""
contract VaultCampaignI2 is VaultCampaignBase {
    function setUp() public {
        _baseSetUp();
    }

    /// Share-asset accounting solvency: the vault's reported assets
    /// must be at least the sum of every user's redemption value. If
    /// this fails the vault has minted shares it cannot back.
    function invariant_I2_share_asset_solvency() public view {
        uint256 sumAssets;
        for (uint256 i = 0; i < users.length; i++) {
            uint256 s = vault.balanceOf(users[i]);
            if (s == 0) continue;
            sumAssets += vault.convertToAssets(s);
        }
        assertGe(
            vault.totalAssets(),
            sumAssets,
            "I2: sum of user redemption values exceeds totalAssets"
        );
    }
}
"""

# --- I3: preview bounds execute ---------------------------------------------
I3_BODY = r"""
contract VaultCampaignI3 is VaultCampaignBase {
    uint256 internal constant PROBE = 1 ether;

    function setUp() public {
        _baseSetUp();
        // Give alice enough for a preview/deposit round-trip below.
        vm.prank(alice);
        asset.approve(address(vault), type(uint256).max);
    }

    /// previewDeposit reports the shares a caller will receive for a
    /// given asset amount. A real deposit must produce at least that
    /// many shares (no hidden slippage).
    function invariant_I3a_preview_deposit_lower_bounds_execute() public {
        uint256 predicted = vault.previewDeposit(PROBE);
        uint256 balBefore = vault.balanceOf(alice);
        vm.prank(alice);
        try vault.deposit(PROBE, alice) returns (uint256 /* minted */) {
            uint256 minted = vault.balanceOf(alice) - balBefore;
            assertGe(
                minted,
                predicted,
                "I3a: deposit returned fewer shares than previewDeposit"
            );
        } catch {
            // deposit reverted (insufficient allowance / cap) — skip.
        }
    }

    /// previewWithdraw reports the shares that a withdrawal of a given
    /// asset amount will burn. A real withdraw must burn at most that
    /// many (no hidden penalty).
    function invariant_I3b_preview_withdraw_upper_bounds_execute() public {
        uint256 ta = vault.maxWithdraw(alice);
        if (ta < PROBE) return;
        uint256 predicted = vault.previewWithdraw(PROBE);
        uint256 balBefore = vault.balanceOf(alice);
        vm.prank(alice);
        try vault.withdraw(PROBE, alice, alice) returns (uint256 /* burned */) {
            uint256 burned = balBefore - vault.balanceOf(alice);
            assertLe(
                burned,
                predicted,
                "I3b: withdraw burned more shares than previewWithdraw"
            );
        } catch {
            // withdraw reverted — skip.
        }
    }
}
"""

# --- I4: share price monotonicity ------------------------------------------
I4_BODY = r"""
contract VaultCampaignI4 is VaultCampaignBase {
    // ghost state tracking the highest share price seen so far.
    uint256 internal highWater;

    function setUp() public {
        _baseSetUp();
        highWater = _sharePrice();
    }

    function _sharePrice() internal view returns (uint256) {
        uint256 ts = vault.totalSupply();
        if (ts == 0) return 0;
        // Scale up to resist integer-divide collapse when totalAssets
        // is close to totalSupply.
        return (vault.totalAssets() * 1e18) / ts;
    }

    /// Share price `totalAssets / totalSupply` must never strictly
    /// decrease in a campaign with no yield and no realized losses.
    /// A drop indicates accounting drift — shares and assets falling
    /// out of step during a deposit/withdraw path.
    function invariant_I4_share_price_non_decreasing() public {
        uint256 now_ = _sharePrice();
        if (now_ == 0) return;
        assertGe(
            now_,
            highWater,
            "I4: share price regressed (accounting drift)"
        );
        if (now_ > highWater) highWater = now_;
    }
}
"""

# --- I5: redeem bounded by balance -----------------------------------------
I5_BODY = r"""
contract VaultCampaignI5 is VaultCampaignBase {
    function setUp() public {
        _baseSetUp();
    }

    /// A user can never redeem more shares than they own. maxRedeem
    /// reports the concrete bound the vault will honour; it must be
    /// less than or equal to that user's share balance.
    function invariant_I5_max_redeem_bounded_by_balance() public view {
        for (uint256 i = 0; i < users.length; i++) {
            uint256 bal = vault.balanceOf(users[i]);
            uint256 cap = vault.maxRedeem(users[i]);
            assertLe(
                cap,
                bal,
                "I5: maxRedeem exceeds user share balance"
            );
        }
    }
}
"""


# Per-invariant metadata: (filename, body). Ordered I1..I5.
INVARIANTS: list[tuple[str, str]] = [
    ("vault_campaign_I1.t.sol", I1_BODY),
    ("vault_campaign_I2.t.sol", I2_BODY),
    ("vault_campaign_I3.t.sol", I3_BODY),
    ("vault_campaign_I4.t.sol", I4_BODY),
    ("vault_campaign_I5.t.sol", I5_BODY),
]


def render_file(body: str, contract_name: str) -> str:
    """Render one harness: banner + shared prelude + invariant body."""
    parts = _BANNER + _SHARED_PRELUDE + body
    return parts.replace("{ContractName}", contract_name)
